# Generated by Django 5.2.4 on 2026-04-14 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integracoes', '0006_integracaoapi_api_key'),
        ('sistema', '0008_alter_logsistema_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversaAssistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('modelo', models.CharField(default='gpt-4o-mini', max_length=50, verbose_name='Modelo IA')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Inicio')),
                ('data_ultima_mensagem', models.DateTimeField(auto_now=True, verbose_name='Ultima mensagem')),
                ('integracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integracoes.integracaoapi', verbose_name='Integracao IA')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas_assistente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Conversa do Assistente',
                'verbose_name_plural': 'Conversas do Assistente',
                'db_table': 'assistente_conversas',
                'ordering': ['-data_ultima_mensagem'],
            },
        ),
        migrations.CreateModel(
            name='MensagemAssistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Assistente'), ('system', 'Sistema')], max_length=10, verbose_name='Tipo')),
                ('conteudo', models.TextField(verbose_name='Conteudo')),
                ('tool_chamada', models.CharField(blank=True, default='', help_text='Nome da tool executada (se houver)', max_length=50, verbose_name='Tool chamada')),
                ('tool_resultado', models.TextField(blank=True, default='', verbose_name='Resultado da tool')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='assistente.conversaassistente', verbose_name='Conversa')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Mensagem do Assistente',
                'verbose_name_plural': 'Mensagens do Assistente',
                'db_table': 'assistente_mensagens',
                'ordering': ['data'],
            },
        ),
    ]
