# Generated by Django 5.2.4 on 2026-04-14 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistente', '0002_configuracaoassistente'),
        ('integracoes', '0006_integracaoapi_api_key'),
        ('sistema', '0008_alter_logsistema_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAssistenteGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False, verbose_name='Assistente ativo globalmente')),
                ('mensagem_boas_vindas', models.TextField(blank=True, default='Ola {nome}! Sou o assistente Hubtrix. Como posso ajudar?', help_text='Use {nome} para o nome do usuario', verbose_name='Mensagem de boas-vindas')),
                ('mensagem_acesso_restrito', models.TextField(blank=True, default='Este numero e de uso exclusivo para usuarios do sistema Hubtrix.', verbose_name='Mensagem de acesso restrito')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('integracao_whatsapp', models.ForeignKey(blank=True, help_text='Numero da Hubtrix usado pelo assistente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistente_whatsapp', to='integracoes.integracaoapi', verbose_name='Integracao WhatsApp (Uazapi)')),
            ],
            options={
                'verbose_name': 'Configuracao Global do Assistente',
                'verbose_name_plural': 'Configuracao Global do Assistente',
                'db_table': 'assistente_configuracao_global',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoAssistenteTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo para este tenant')),
                ('modelo_ia', models.CharField(default='gpt-4o-mini', max_length=50, verbose_name='Modelo IA')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('integracao_ia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistente_ia', to='integracoes.integracaoapi', verbose_name='Integracao IA (OpenAI, etc.)')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_assistente', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Configuracao Assistente (Tenant)',
                'verbose_name_plural': 'Configuracoes Assistente (Tenant)',
                'db_table': 'assistente_configuracao_tenant',
            },
        ),
        migrations.DeleteModel(
            name='ConfiguracaoAssistente',
        ),
    ]
