# Generated by Django 5.2.4 on 2026-03-29 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0002_clientehubsoft_servicoclientehubsoft_and_more'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracaoapi',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integracoes', to='sistema.tenant', verbose_name='Tenant'),
        ),
    ]
