# Generated by Django 5.2.4 on 2026-06-17 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0012_perfilusuario_login_matrix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descricao')),
                ('icone', models.CharField(default='bi-bar-chart', max_length=50, verbose_name='Icone (Bootstrap Icons)')),
                ('compartilhado', models.BooleanField(default=False, help_text='Se True, todos os usuarios do tenant veem (so admin pode marcar).', verbose_name='Compartilhado')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('config', models.JSONField(blank=True, default=dict, help_text='JSON com filtros padrao + layout do GridStack.', verbose_name='Config (filtros globais, layout grid)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboards_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'db_table': 'relatorios_dashboard',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Titulo')),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('data_source', models.CharField(help_text='Chave do registry em apps.relatorios.data_sources (ex: "oportunidade", "lead").', max_length=50, verbose_name='Data Source')),
                ('metrica', models.JSONField(default=dict, help_text='Ex: {"tipo": "count"} ou {"tipo": "sum", "campo": "valor_estimado"}.', verbose_name='Metrica')),
                ('agrupamento', models.JSONField(blank=True, default=dict, help_text='Ex: {"dimensao": "estagio.nome"} ou {"dimensao": "data_criacao", "granularidade": "mes"}.', verbose_name='Agrupamento')),
                ('filtros', models.JSONField(blank=True, default=list, help_text='Lista: [{"campo": X, "operador": "igual|diferente|maior|menor|entre|contem", "valor": Y}].', verbose_name='Filtros')),
                ('visualizacao', models.CharField(choices=[('numero', 'Numero grande'), ('barra', 'Barra'), ('linha', 'Linha (serie temporal)'), ('pizza', 'Pizza'), ('tabela', 'Tabela'), ('funil', 'Funil')], default='numero', max_length=30, verbose_name='Tipo de visualizacao')),
                ('layout', models.JSONField(blank=True, default=dict, help_text='Posicao no GridStack: {x, y, w, h}.', verbose_name='Layout no grid')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('config_extra', models.JSONField(blank=True, default=dict, help_text='Ex: {"cor_serie": "#2563eb", "limite_top": 10}.', verbose_name='Config extra')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='relatorios.dashboard', verbose_name='Dashboard')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'db_table': 'relatorios_widget',
                'ordering': ['dashboard', 'ordem', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['tenant', 'compartilhado'], name='relatorios__tenant__79b215_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['tenant', 'criado_por'], name='relatorios__tenant__43e5dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboard',
            unique_together={('tenant', 'criado_por', 'nome')},
        ),
    ]
