# Generated by Django 5.2.4 on 2026-06-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='setor',
            field=models.CharField(choices=[('comercial', 'Comercial'), ('atendimento', 'Atendimento'), ('marketing', 'Marketing'), ('cs', 'Customer Success'), ('financeiro', 'Financeiro'), ('tecnico', 'Tecnico / Operacional'), ('executivo', 'Executivo'), ('outros', 'Outros')], db_index=True, default='outros', help_text='Agrupa o dashboard por area da empresa na sidebar.', max_length=20, verbose_name='Setor'),
        ),
    ]
