# Generated by Django 5.2.14 on 2026-06-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapturaAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.CharField(db_index=True, max_length=20)),
                ('registro_id', models.IntegerField(blank=True, null=True)),
                ('metodo', models.CharField(max_length=8)),
                ('endpoint', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('resposta', models.JSONField(blank=True, default=dict)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Captura de API',
                'verbose_name_plural': 'Capturas de API',
                'db_table': 'posvenda_captura_api',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ExecucaoHubsoft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.CharField(choices=[('conversao', 'Conversão prospecto → cliente'), ('novo_servico', 'Novo serviço'), ('upgrade', 'Upgrade de plano')], db_index=True, max_length=20)),
                ('registro_id', models.IntegerField(db_index=True, help_text='ID do NewService / UpgradePlano / prospecto processado')),
                ('executor', models.CharField(choices=[('api_interna', 'API interna'), ('webdriver', 'Webdriver')], max_length=20)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('falha', 'Falha'), ('dry_run', 'Dry-run (não salvou)')], db_index=True, max_length=10)),
                ('dry_run', models.BooleanField(default=True)),
                ('tentativa_fallback', models.BooleanField(default=False, help_text='True se esta execução foi o fallback após o primário falhar')),
                ('etapa', models.CharField(blank=True, default='', max_length=80)),
                ('erro', models.TextField(blank=True, default='')),
                ('metadados', models.JSONField(blank=True, default=dict, help_text='ids criados no HubSoft, etc.')),
                ('duracao_ms', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Execução HubSoft',
                'verbose_name_plural': 'Execuções HubSoft',
                'db_table': 'posvenda_execucao_hubsoft',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['processo', 'registro_id'], name='posvenda_ex_process_cec963_idx'), models.Index(fields=['status', 'criado_em'], name='posvenda_ex_status_c2e31d_idx')],
            },
        ),
    ]
