# Generated by Django 5.2.4 on 2026-06-19 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0001_initial'),
        ('sistema', '0012_perfilusuario_login_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxo',
            name='webhook_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='ExecucaoFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('rodando', 'rodando'), ('aguardando', 'aguardando'), ('completado', 'completado'), ('erro', 'erro')], db_index=True, default='rodando', max_length=20)),
                ('estado', models.JSONField(default=dict)),
                ('retomar_em', models.CharField(blank=True, default='', max_length=200)),
                ('agendado_para', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('trace', models.JSONField(default=list)),
                ('erro', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='automacao.fluxo')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'db_table': 'automacao_execucao',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', 'agendado_para'], name='automacao_e_status_bf6f6e_idx')],
            },
        ),
    ]
