# Generated by Django 5.2.4 on 2026-06-20 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0002_fluxo_webhook_token_execucaofluxo'),
        ('leads', '0008_leadprospecto_atendido_em'),
        ('sistema', '0012_perfilusuario_login_matrix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execucaofluxo',
            name='retomar_em',
        ),
        migrations.AddField(
            model_name='execucaofluxo',
            name='chave',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='execucaofluxo',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.leadprospecto'),
        ),
        migrations.AddField(
            model_name='execucaofluxo',
            name='modo_espera',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='execucaofluxo',
            name='no_pausado',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddIndex(
            model_name='execucaofluxo',
            index=models.Index(fields=['status', 'modo_espera', 'chave'], name='automacao_e_status_201acd_idx'),
        ),
    ]
