# Generated by Django 5.2.4 on 2026-06-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0003_remove_execucaofluxo_retomar_em_execucaofluxo_chave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxo',
            name='gatilho_evento',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='execucaofluxo',
            name='status',
            field=models.CharField(choices=[('pendente', 'pendente'), ('rodando', 'rodando'), ('aguardando', 'aguardando'), ('completado', 'completado'), ('erro', 'erro')], db_index=True, default='rodando', max_length=20),
        ),
    ]
