# Generated by Django 5.2.4 on 2026-06-23 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0004_fluxo_gatilho_evento_alter_execucaofluxo_status'),
        ('integracoes', '0017_atendimentohubsoft_faturahubsoft_ordemservicohubsoft'),
        ('sistema', '0012_perfilusuario_login_matrix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('modelo', models.CharField(blank=True, default='', max_length=100)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('tools', models.JSONField(blank=True, default=list)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('integracao_ia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='integracoes.integracaoapi')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Agente IA',
                'verbose_name_plural': 'Agentes IA',
                'db_table': 'automacao_agente',
                'ordering': ['nome'],
            },
        ),
    ]
