# Generated by Django 5.2.4 on 2026-06-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0005_agente'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='base_categorias',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
