# Generated by Django 5.2.4 on 2026-06-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0006_agente_base_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxo',
            name='origem_regra',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
