# Generated by Django 5.2.4 on 2026-06-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0007_fluxo_origem_regra'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='memoria',
            field=models.CharField(blank=True, default='conversa', max_length=30),
        ),
    ]
