# Generated by Django 5.2.4 on 2026-06-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0008_agente_memoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agente',
            options={'ordering': ['equipe', 'ordem', 'nome'], 'verbose_name': 'Agente IA', 'verbose_name_plural': 'Agentes IA'},
        ),
        migrations.AddField(
            model_name='agente',
            name='cor',
            field=models.CharField(blank=True, default='', help_text='Cor hex do card (ex: #1e3a8a).', max_length=7),
        ),
        migrations.AddField(
            model_name='agente',
            name='descricao',
            field=models.TextField(blank=True, default='', help_text='Resumo curto do papel do agente.'),
        ),
        migrations.AddField(
            model_name='agente',
            name='equipe',
            field=models.CharField(blank=True, choices=[('executivo', 'Executivo'), ('produto', 'Produto'), ('comercial', 'Comercial'), ('marketing', 'Marketing'), ('tech', 'Tech'), ('operacoes', 'Operações'), ('fluxo', 'Fluxos / Bot')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='agente',
            name='icone',
            field=models.CharField(blank=True, default='bi-robot', help_text='Bootstrap Icon (bi-*).', max_length=40),
        ),
        migrations.AddField(
            model_name='agente',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Ordem de exibicao dentro do time.'),
        ),
        migrations.AddField(
            model_name='agente',
            name='prompt_autonomo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
