# Generated by Django 5.2.4 on 2026-07-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0009_alter_agente_options_agente_cor_agente_descricao_and_more'),
        ('leads', '0013_migrar_origem_canal_fonte'),
        ('sistema', '0014_perfilusuario_cod_talk'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaofluxo',
            name='claimed_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execucaofluxo',
            name='tentativas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='execucaofluxo',
            index=models.Index(fields=['status', 'claimed_em'], name='automacao_e_status_bb6e62_idx'),
        ),
        migrations.AddIndex(
            model_name='execucaofluxo',
            index=models.Index(fields=['fluxo', 'lead', 'criado_em'], name='automacao_e_fluxo_i_a62c6d_idx'),
        ),
    ]
