# Generated by Django 5.2.4 on 2026-07-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0010_execucaofluxo_claimed_em_execucaofluxo_tentativas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxo',
            name='agenda_intervalo_minutos',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='fluxo',
            name='agenda_ultima_rodada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
