# Generated by Django 5.2.4 on 2026-07-18 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0012_renomear_marcadores_internos'),
        ('leads', '0014_alter_historicocontato_status'),
        ('sistema', '0015_alter_alertasistema_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('descricao', models.TextField(blank=True, default='')),
                ('contexto', models.CharField(choices=[('bot_vendas', 'Bot de vendas'), ('onboarding', 'Onboarding'), ('suporte', 'Suporte'), ('visita_tecnica', 'Visita técnica'), ('outro', 'Outro')], db_index=True, default='bot_vendas', max_length=30)),
                ('modo_preenchimento', models.CharField(choices=[('ia', 'IA (bot)'), ('humano', 'Humano'), ('ambos', 'Ambos')], default='ia', max_length=20)),
                ('entidade_alvo', models.CharField(choices=[('lead', 'Lead'), ('oportunidade', 'Oportunidade')], default='lead', max_length=20)),
                ('bloqueia_avanco', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
                'db_table': 'automacao_checklist',
                'ordering': ['nome'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(db_index=True, default=0)),
                ('chave', models.CharField(max_length=60)),
                ('pergunta', models.TextField()),
                ('ajuda', models.CharField(blank=True, default='', max_length=200)),
                ('tipo_resposta', models.CharField(choices=[('texto_livre', 'Texto livre'), ('opcoes', 'Múltipla escolha')], default='texto_livre', max_length=20)),
                ('opcoes', models.JSONField(blank=True, default=list)),
                ('ura_titulo', models.CharField(blank=True, choices=[('', 'Nenhum (menu comum)'), ('confirmacao_plano_620', 'Confirmação plano 620'), ('confirmacao_plano_1g', 'Confirmação plano 1G'), ('confirmacao_plano_1g_ponto_adc', 'Confirmação plano 1G + ponto adicional')], default='', max_length=60)),
                ('tipo_validacao', models.CharField(choices=[('nenhuma', 'Nenhuma'), ('email', 'E-mail'), ('cpf_cnpj', 'CPF/CNPJ'), ('cep', 'CEP'), ('numero', 'Número'), ('data', 'Data'), ('regex', 'Regex customizado'), ('ia', 'IA (julgamento livre)')], default='nenhuma', max_length=20)),
                ('regex_validacao', models.CharField(blank=True, default='', max_length=200)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('condicao', models.JSONField(blank=True, null=True)),
                ('max_tentativas', models.PositiveSmallIntegerField(default=3)),
                ('estrategia_erro', models.CharField(choices=[('repetir', 'Repetir a pergunta'), ('pular', 'Pular o item'), ('transbordar', 'Transbordar pra humano'), ('finalizar', 'Finalizar o checklist')], default='repetir', max_length=20)),
                ('mensagem_erro', models.TextField(blank=True, default='')),
                ('mensagem_sucesso', models.TextField(blank=True, default='')),
                ('mensagem_recontato', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('campo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.campocustomizado')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='automacao.checklist')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Item de checklist',
                'verbose_name_plural': 'Itens de checklist',
                'db_table': 'automacao_checklist_item',
                'ordering': ['ordem', 'id'],
                'unique_together': {('checklist', 'chave')},
            },
        ),
        migrations.CreateModel(
            name='RespostaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade_tipo', models.CharField(db_index=True, max_length=30)),
                ('entidade_id', models.PositiveIntegerField(db_index=True)),
                ('valor', models.TextField(blank=True, default='')),
                ('valor_processado', models.JSONField(blank=True, null=True)),
                ('origem', models.CharField(choices=[('bot', 'Bot'), ('humano', 'Humano'), ('importacao', 'Importação')], default='bot', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='automacao.checklist')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='automacao.itemchecklist')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Resposta de checklist',
                'verbose_name_plural': 'Respostas de checklist',
                'db_table': 'automacao_checklist_resposta',
                'indexes': [models.Index(fields=['tenant', 'entidade_tipo', 'entidade_id'], name='automacao_c_tenant__4c86ab_idx'), models.Index(fields=['checklist', 'entidade_tipo', 'entidade_id'], name='automacao_c_checkli_f04673_idx')],
                'unique_together': {('item', 'entidade_tipo', 'entidade_id')},
            },
        ),
    ]
