# Generated by Django 5.2.4 on 2026-07-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0013_checklist_itemchecklist_respostachecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchecklist',
            name='instrucoes_ia',
            field=models.TextField(blank=True, default='', help_text='Instrucoes especificas pra IA validar ESTE item (ex: "aceite apenas nomes de pessoa fisica, recuse nome de empresa"). Preenchido, habilita a IA como segunda opiniao quando a validacao deterministica falhar.'),
        ),
    ]
