# Generated by Django 5.2.4 on 2026-04-01 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineestagio',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('tipo', models.CharField(choices=[('vendas', 'Vendas'), ('suporte', 'Suporte'), ('onboarding', 'Onboarding'), ('custom', 'Personalizado')], default='vendas', max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('cor_hex', models.CharField(default='#667eea', max_length=7, verbose_name='Cor')),
                ('icone_fa', models.CharField(default='fa-funnel-dollar', max_length=50, verbose_name='Ícone')),
                ('padrao', models.BooleanField(default=False, help_text='Pipeline usado ao criar oportunidades automaticamente', verbose_name='Pipeline padrão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': '📊 00. Pipelines',
                'db_table': 'crm_pipelines',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='configuracaocrm',
            name='pipeline_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.pipeline', verbose_name='Pipeline Padrão'),
        ),
        migrations.AddField(
            model_name='oportunidadevenda',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_pipeline', to='crm.pipeline', verbose_name='Pipeline'),
        ),
        migrations.AddField(
            model_name='pipelineestagio',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estagios', to='crm.pipeline', verbose_name='Pipeline'),
        ),
        migrations.AlterUniqueTogether(
            name='pipelineestagio',
            unique_together={('pipeline', 'slug')},
        ),
    ]
