# Generated by Django 5.2.4 on 2026-04-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_pipelineestagio_slug_pipeline_and_more'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcrm',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterUniqueTogether(
            name='tagcrm',
            unique_together={('tenant', 'nome')},
        ),
    ]
