# Generated by Django 5.2.4 on 2026-04-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_tagcrm_nome_alter_tagcrm_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidadevenda',
            name='dados_custom',
            field=models.JSONField(blank=True, default=dict, help_text='Campos personalizados definidos pelo tenant', verbose_name='Dados Customizados'),
        ),
    ]
