# Generated by Django 5.2.4 on 2026-04-12 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_initial'),
        ('crm', '0004_oportunidadevenda_dados_custom'),
        ('sistema', '0007_codigorecuperacaosenha_configuracaorecuperacaosenha'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('codigo', models.CharField(blank=True, default='', max_length=50, verbose_name='Código/SKU')),
                ('categoria', models.CharField(choices=[('plano', 'Plano'), ('servico', 'Serviço'), ('equipamento', 'Equipamento'), ('addon', 'Adicional'), ('outro', 'Outro')], default='servico', max_length=20, verbose_name='Categoria')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)')),
                ('recorrencia', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('avulso', 'Avulso (único)')], default='mensal', max_length=15, verbose_name='Recorrência')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('id_externo', models.CharField(blank=True, default='', help_text='ID do produto no sistema integrado', max_length=100, verbose_name='ID no Sistema Externo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('plano_internet', models.ForeignKey(blank=True, help_text='Vincular a um plano para integração com HubSoft', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_crm', to='cadastro.planointernet', verbose_name='Plano de Internet (HubSoft)')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Produto/Serviço',
                'verbose_name_plural': '📦 13. Produtos e Serviços',
                'db_table': 'crm_produtos',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('tenant', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='ItemOportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário (R$)')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto (R$)')),
                ('observacao', models.CharField(blank=True, default='', max_length=255, verbose_name='Observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='crm.oportunidadevenda', verbose_name='Oportunidade')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_oportunidade', to='crm.produtoservico', verbose_name='Produto/Serviço')),
            ],
            options={
                'verbose_name': 'Item da Oportunidade',
                'verbose_name_plural': 'Item da Oportunidade',
                'db_table': 'crm_itens_oportunidade',
                'ordering': ['data_criacao'],
            },
        ),
    ]
