# Generated by Django 5.2.4 on 2026-04-13 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_cadastrocliente_produto_and_more'),
        ('crm', '0005_produtoservico_itemoportunidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoservico',
            name='dados_erp',
            field=models.JSONField(blank=True, default=dict, help_text='Campos específicos do ERP (velocidade, tecnologia, etc.)', verbose_name='Dados do ERP'),
        ),
        migrations.AddField(
            model_name='produtoservico',
            name='destaque',
            field=models.CharField(blank=True, choices=[('', 'Sem Destaque'), ('popular', 'Mais Popular'), ('premium', 'Premium'), ('economico', 'Mais Econômico'), ('recomendado', 'Recomendado')], default='', max_length=50, verbose_name='Destaque'),
        ),
        migrations.AlterField(
            model_name='produtoservico',
            name='id_externo',
            field=models.CharField(blank=True, default='', help_text='ID do produto no ERP integrado', max_length=100, verbose_name='ID no Sistema Externo'),
        ),
        migrations.AlterField(
            model_name='produtoservico',
            name='plano_internet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_crm', to='cadastro.planointernet', verbose_name='Plano de Internet (legado)'),
        ),
    ]
