# Generated by Django 5.2.4 on 2026-04-13 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_produtoservico_dados_erp_produtoservico_destaque_and_more'),
        ('sistema', '0008_alter_logsistema_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcaoVencimentoCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveIntegerField(verbose_name='Dia do Vencimento')),
                ('descricao', models.CharField(blank=True, default='', max_length=100, verbose_name='Descrição')),
                ('id_externo', models.CharField(blank=True, default='', help_text='ID desta opção no sistema integrado (HubSoft, etc.)', max_length=100, verbose_name='ID no ERP')),
                ('dados_erp', models.JSONField(blank=True, default=dict, help_text='Campos extras do ERP para este vencimento', verbose_name='Dados do ERP')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Opção de Vencimento',
                'verbose_name_plural': '📅 14. Opções de Vencimento',
                'db_table': 'crm_opcoes_vencimento',
                'ordering': ['ordem', 'dia'],
                'unique_together': {('tenant', 'dia')},
            },
        ),
    ]
