# Generated by Django 5.2.4 on 2026-04-13 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_opcaovencimentocrm'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaocrm',
            name='distribuicao_equipe',
            field=models.ForeignKey(blank=True, help_text='Equipe cujos membros receberão oportunidades automaticamente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.equipevendas', verbose_name='Equipe para Distribuição'),
        ),
        migrations.AddField(
            model_name='configuracaocrm',
            name='distribuicao_modo',
            field=models.CharField(choices=[('desativado', 'Desativado (sem atribuição)'), ('round_robin', 'Round Robin (rodízio)')], default='desativado', max_length=15, verbose_name='Distribuição de Oportunidades'),
        ),
        migrations.AddField(
            model_name='configuracaocrm',
            name='distribuicao_ultimo_vendedor_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Último vendedor atribuído (round robin)'),
        ),
    ]
