# Generated by Django 5.2.4 on 2026-04-21 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_configuracaocrm_distribuicao_equipe_and_more'),
        ('sistema', '0009_perfilusuario_senha_temporaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraPipelineEstagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Descrição curta (ex: 'Serviço habilitado + doc validada')", max_length=150, verbose_name='Nome da Regra')),
                ('condicoes', models.JSONField(blank=True, default=list, help_text='Lista de condições AND: [{tipo, campo, operador, valor}, ...]', verbose_name='Condições')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('prioridade', models.PositiveIntegerField(default=0, help_text='Menor valor = avaliada primeiro dentro do estágio', verbose_name='Prioridade')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('estagio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='crm.pipelineestagio', verbose_name='Estágio')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Regra do Pipeline',
                'verbose_name_plural': '🎯 13. Automações do Pipeline',
                'db_table': 'crm_regras_pipeline_estagio',
                'ordering': ['estagio__ordem', 'prioridade'],
            },
        ),
    ]
