# Generated by Django 5.2.4 on 2026-04-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_regrapipelineestagio'),
    ]

    operations = [
        migrations.AddField(
            model_name='regrapipelineestagio',
            name='total_disparos',
            field=models.PositiveIntegerField(default=0, help_text='Quantas vezes a regra já moveu uma oportunidade', verbose_name='Total de disparos'),
        ),
        migrations.AddField(
            model_name='regrapipelineestagio',
            name='ultima_execucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última execução'),
        ),
    ]
