# Generated by Django 5.2.4 on 2026-04-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_regrapipelineestagio_total_disparos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaocrm',
            name='preview_regras_max',
            field=models.PositiveIntegerField(default=500, help_text='Quantas oportunidades o preview de regra avalia. Aumentar dá amostra maior mas deixa mais lento.', verbose_name='Preview de regras — oportunidades avaliadas'),
        ),
    ]
