# Generated by Django 5.2.4 on 2026-05-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_configuracaocrm_preview_regras_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidadevenda',
            name='motivo_ganho_categoria',
            field=models.CharField(blank=True, choices=[('preco', 'Preço competitivo'), ('atendimento', 'Atendimento / experiência'), ('viabilidade', 'Viabilidade / cobertura'), ('combo_plano', 'Plano / combo certo'), ('indicacao', 'Indicação / boca-a-boca'), ('marca', 'Reputação / marca'), ('outro', 'Outro')], db_index=True, max_length=30, null=True, verbose_name='Categoria do motivo de ganho'),
        ),
        migrations.AddField(
            model_name='oportunidadevenda',
            name='motivo_perda_categoria',
            field=models.CharField(blank=True, choices=[('preco', 'Preço'), ('concorrente', 'Concorrente'), ('timing', 'Timing / não era o momento'), ('sem_orcamento', 'Sem orçamento / poder de decisão'), ('viabilidade_tecnica', 'Sem viabilidade técnica'), ('sem_resposta', 'Sumiu / sem resposta'), ('outro', 'Outro')], db_index=True, max_length=30, null=True, verbose_name='Categoria do motivo de perda'),
        ),
        migrations.AlterField(
            model_name='oportunidadevenda',
            name='motivo_perda',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Perda (texto livre)'),
        ),
    ]
