# Generated by Django 5.2.4 on 2026-05-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_oportunidadevenda_motivo_ganho_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidadevenda',
            name='proxima_acao_sugerida',
            field=models.JSONField(blank=True, default=dict, help_text='Estrutura: {tipo, titulo, mensagem_sugerida, justificativa, urgencia, gerada_em, estado}', verbose_name='Próxima ação sugerida (IA)'),
        ),
    ]
