# Generated by Django 5.2.4 on 2026-05-22 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_oportunidadevenda_proxima_acao_sugerida'),
        ('sistema', '0010_tenant_modulo_workspace_tenant_plano_workspace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidadevenda',
            name='motivo_perda_categoria',
            field=models.CharField(blank=True, choices=[('preco', 'Preço'), ('concorrente', 'Concorrente'), ('timing', 'Timing / não era o momento'), ('sem_orcamento', 'Sem orçamento / poder de decisão'), ('viabilidade_tecnica', 'Sem viabilidade técnica'), ('sem_resposta', 'Sumiu / sem resposta'), ('outro', 'Outro')], db_index=True, max_length=30, null=True, verbose_name='Categoria do motivo de perda (legado)'),
        ),
        migrations.CreateModel(
            name='MotivoPerda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Motivo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Motivo de Perda',
                'verbose_name_plural': '📉 Motivos de Perda',
                'db_table': 'crm_motivos_perda',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('tenant', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='oportunidadevenda',
            name='motivo_perda_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='crm.motivoperda', verbose_name='Motivo de perda'),
        ),
    ]
