# Generated by Django 5.2.4 on 2026-05-23 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_cadastrocliente_produto_and_more'),
        ('crm', '0015_seed_motivos_perda'),
        ('leads', '0003_alter_campocustomizado_options_and_more'),
        ('sistema', '0010_tenant_modulo_workspace_tenant_plano_workspace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor (R$)')),
                ('status', models.CharField(choices=[('pendente_erp', 'Pendente envio ERP'), ('enviado_erp', 'Enviado ao ERP'), ('ativo', 'Ativo'), ('erro_erp', 'Erro no envio')], db_index=True, default='pendente_erp', max_length=20, verbose_name='Status ERP')),
                ('data_venda', models.DateTimeField(auto_now_add=True, verbose_name='Data da venda')),
                ('enviado_erp_em', models.DateTimeField(blank=True, null=True, verbose_name='Enviado ao ERP em')),
                ('erro_erp_msg', models.TextField(blank=True, verbose_name='Mensagem de erro ERP')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='leads.leadprospecto', verbose_name='Lead')),
                ('oportunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='crm.oportunidadevenda', verbose_name='Oportunidade')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='cadastro.planointernet', verbose_name='Plano contratado')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': '💰 14. Vendas',
                'db_table': 'crm_vendas',
                'ordering': ['-data_venda'],
            },
        ),
    ]
