# Generated by Django 5.2.4 on 2026-06-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_regrapipelineestagio_acoes_estagio_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaocrm',
            name='motivo_perda_obrigatorio',
            field=models.BooleanField(default=False, help_text="Quando ativo, exige preenchimento do motivo ao mover oportunidade para o estágio 'Perdida'. Backend rejeita salvar sem motivo.", verbose_name='Motivo de perda obrigatório'),
        ),
        migrations.AddField(
            model_name='configuracaocrm',
            name='motivo_perda_pede_concorrente',
            field=models.BooleanField(default=True, help_text='Quando motivo escolhido for relacionado a concorrente, exibe campo extra para identificar qual.', verbose_name="Pedir 'qual concorrente?' quando motivo for Concorrente"),
        ),
    ]
