# Generated by Django 5.2.4 on 2026-06-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_configuracaocrm_motivo_perda_obrigatorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidadevenda',
            name='motivo_perda_origem',
            field=models.CharField(blank=True, choices=[('humano', 'Humano (vendedor/operador)'), ('llm_backfill', 'LLM — backfill historico'), ('bot', 'Bot (captura automatica no fluxo)')], default='humano', help_text='De onde veio o motivo: preenchimento humano, backfill por LLM, ou captura automatica via bot.', max_length=20, verbose_name='Origem do motivo de perda'),
        ),
    ]
