# Generated by Django 5.2.4 on 2026-06-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_oportunidadevenda_motivo_perda_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='regrapipelineestagio',
            name='total_acoes_efetivas',
            field=models.PositiveIntegerField(default=0, help_text='Quantas vezes a ação rodou de fato (criou Venda, enviou WhatsApp, etc — exclui pulos idempotentes)', verbose_name='Total de ações efetivas'),
        ),
        migrations.AlterField(
            model_name='regrapipelineestagio',
            name='total_disparos',
            field=models.PositiveIntegerField(default=0, help_text='Quantas vezes as condições da regra bateram (mesmo que a ação tenha pulado por idempotência)', verbose_name='Total de avaliações com match'),
        ),
    ]
