# Generated by Django 5.2.4 on 2026-06-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_score_externo_gate_nuvyon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineestagio',
            name='campos_obrigatorios',
            field=models.JSONField(blank=True, default=list, help_text='Lista de campos que devem estar preenchidos pra avancar pra este estagio. Formato: ["lead.cpf_cnpj", "lead.cep", "oportunidade.valor_estimado"]', verbose_name='Campos obrigatorios para entrar'),
        ),
    ]
