# Generated by Django 5.2.4 on 2026-06-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_pipelineestagio_campos_obrigatorios'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaocrm',
            name='estagio_proposta_slug',
            field=models.CharField(blank=True, default='', help_text="Slug do estagio do pipeline padrao que marca o momento da 'proposta enviada' (usado no relatorio Velocidade de atendimento). Ex: 'em-negociacao', 'plano-escolhido'.", max_length=80, verbose_name="Estagio que representa 'Proposta enviada'"),
        ),
    ]
