# Generated by Django 5.2.4 on 2026-06-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_configuracaocrm_estagio_proposta_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidadevenda',
            name='is_rascunho',
            field=models.BooleanField(db_index=True, default=False, help_text='True quando a oportunidade foi criada automaticamente pra leads novos que ainda nao bateram score/status de qualificacao. Escondida do funil/kanban padrao. Vira False quando o lead qualifica.', verbose_name='Rascunho (lead nao qualificado ainda)'),
        ),
    ]
