# Generated by Django 5.2.4 on 2026-06-18 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_oportunidadevenda_is_rascunho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oportunidadevenda',
            name='is_rascunho',
        ),
    ]
