# Generated by Django 5.2.4 on 2026-06-25 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_remove_oportunidadevenda_is_rascunho'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaocrm',
            name='campos_card_padrao',
            field=models.JSONField(blank=True, default=list, help_text='Campos visiveis em cada card do kanban (max 5). Default global do tenant; cada vendedor pode personalizar.', verbose_name='Campos padrao do card no kanban'),
        ),
        migrations.CreateModel(
            name='PreferenciaUsuarioKanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campos', models.JSONField(blank=True, default=list, help_text='Lista ordenada de slugs de campos (max 5). Veja apps.comercial.crm.cards_config.CAMPOS_CARD_DISPONIVEIS.', verbose_name='Campos visiveis no card')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_kanban', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de Kanban',
                'verbose_name_plural': 'Preferencias de Kanban',
                'db_table': 'crm_preferencia_kanban',
            },
        ),
    ]
