# Generated by Django 5.2.4 on 2026-06-29 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0003_alter_campanhatrafego_codigo_and_more'),
        ('crm', '0027_rename_valor_estimado_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidadevenda',
            name='campanha_atribuicao',
            field=models.ForeignKey(blank=True, help_text='Campanha que trouxe esta op (pode diferir de lead.campanha_origem).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_atribuicao', to='campanhas.campanhatrafego', verbose_name='Campanha de Atribuicao'),
        ),
        migrations.AddField(
            model_name='oportunidadevenda',
            name='canal_atribuicao',
            field=models.CharField(blank=True, db_index=True, help_text='Meio fisico que trouxe esta op. Herda de lead.canal na criacao.', max_length=20, null=True, verbose_name='Canal de Atribuicao'),
        ),
        migrations.AddField(
            model_name='oportunidadevenda',
            name='fonte_atribuicao',
            field=models.CharField(blank=True, db_index=True, help_text='Plataforma que trouxe esta op. Herda de lead.fonte na criacao.', max_length=30, null=True, verbose_name='Fonte de Atribuicao'),
        ),
        migrations.AddField(
            model_name='oportunidadevenda',
            name='metadata_atribuicao',
            field=models.JSONField(blank=True, default=dict, help_text='Dados extras da atribuicao (utm_content, utm_term, protocolo, etc).', verbose_name='Metadata de Atribuicao'),
        ),
    ]
