# Generated by Django 5.2.4 on 2026-07-20 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0015_alter_alertasistema_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_experiencia_padrao', models.PositiveSmallIntegerField(default=90, help_text='Duracao total do periodo de experiencia, em dias corridos.', verbose_name='Dias de experiencia (total)')),
                ('dias_primeiro_periodo_experiencia', models.PositiveSmallIntegerField(default=45, help_text='Primeiro trecho da experiencia. Ex: 45 em um 45 mais 45.', verbose_name='Dias do primeiro periodo')),
                ('exige_cpf_no_autocadastro', models.BooleanField(default=True, help_text='CPF e o que garante o dedup. Afrouxar so quando a operacao exigir.', verbose_name='Exigir CPF no auto cadastro')),
                ('texto_consentimento_lgpd', models.TextField(blank=True, default='', help_text='Exibido no formulario publico. O colaborador precisa aceitar.', verbose_name='Texto do consentimento LGPD')),
                ('versao_consentimento_lgpd', models.CharField(default='1.0', help_text='Gravada junto do aceite. Mudou o texto, suba a versao.', max_length=20, verbose_name='Versao do consentimento')),
                ('link_expira_em_dias', models.PositiveSmallIntegerField(default=0, help_text='0 significa que o link nao expira sozinho.', verbose_name='Validade do link de cadastro (dias)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Configuracao do People',
                'verbose_name_plural': 'Configuracoes do People',
                'db_table': 'people_configuracao',
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='people_configuracao_unica_por_tenant')],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('codigo', models.SlugField(help_text='Identificador curto e estavel. Ex: loja-centro.', max_length=40, verbose_name='Codigo')),
                ('cnpj', models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ')),
                ('cep', models.CharField(blank=True, default='', max_length=9, verbose_name='CEP')),
                ('rua', models.CharField(blank=True, default='', max_length=200, verbose_name='Rua')),
                ('numero', models.CharField(blank=True, default='', max_length=20, verbose_name='Numero')),
                ('complemento', models.CharField(blank=True, default='', max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, default='', max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, default='', max_length=2, verbose_name='Estado')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('dias_experiencia_padrao', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Dias de experiencia (override)')),
                ('dias_primeiro_periodo_experiencia', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Dias do primeiro periodo (override)')),
                ('exige_cpf_no_autocadastro', models.BooleanField(blank=True, null=True, verbose_name='Exigir CPF no auto cadastro (override)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_unidades_geridas', to=settings.AUTH_USER_MODEL, verbose_name='Responsavel')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'db_table': 'people_unidade',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['tenant', 'ativo'], name='people_und_tenant_ativo_idx'), models.Index(fields=['tenant', 'nome'], name='people_und_tenant_nome_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'codigo'), name='people_unidade_codigo_unico_por_tenant')],
            },
        ),
    ]
