# Generated by Django 5.2.4 on 2026-07-20 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('sistema', '0015_alter_alertasistema_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, default=None, help_text='So digitos. Nulo quando ausente, nunca string vazia.', max_length=11, null=True, verbose_name='CPF')),
                ('cpf_valido', models.BooleanField(default=False, help_text='CPF invalido nao bloqueia o cadastro, cai na fila de revisao.', verbose_name='CPF com digito verificador valido')),
                ('rg', models.CharField(blank=True, default='', max_length=20, verbose_name='RG')),
                ('pis', models.CharField(blank=True, default='', max_length=11, verbose_name='PIS')),
                ('telefone', models.CharField(blank=True, default='', help_text='E.164 sem o mais. Ex: 5586999998888.', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('primeiro_nome', models.CharField(blank=True, default='', help_text='Derivado do nome completo quando vazio.', max_length=60, verbose_name='Primeiro nome')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('cep', models.CharField(blank=True, default='', max_length=9, verbose_name='CEP')),
                ('rua', models.CharField(blank=True, default='', max_length=200, verbose_name='Rua')),
                ('numero', models.CharField(blank=True, default='', max_length=20, verbose_name='Numero')),
                ('complemento', models.CharField(blank=True, default='', max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, default='', max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, default='', max_length=2, verbose_name='Estado')),
                ('tipo_chave_pix', models.CharField(blank=True, choices=[('cpf', 'CPF'), ('celular', 'Celular'), ('email', 'Email'), ('aleatoria', 'Chave aleatoria')], default='', max_length=20, verbose_name='Tipo de chave Pix')),
                ('chave_pix', models.CharField(blank=True, default='', max_length=140, verbose_name='Chave Pix')),
                ('situacao', models.CharField(choices=[('cadastro', 'Cadastro'), ('em_admissao', 'Em admissao'), ('em_experiencia', 'Em experiencia'), ('efetivado', 'Efetivado'), ('em_desligamento', 'Em desligamento'), ('desligado', 'Desligado'), ('freelancer', 'Freelancer')], db_index=True, default='cadastro', help_text='So muda por mover_situacao(). Ver apps/people/estados.py.', max_length=20, verbose_name='Situacao')),
                ('ponto_entrada', models.CharField(choices=[('so_cadastro', 'So cadastrar por enquanto'), ('em_admissao', 'Ainda em admissao'), ('ja_trabalhando', 'Ja esta trabalhando'), ('link_publico', 'Auto cadastro por link')], default='so_cadastro', help_text='Por qual porta a pessoa entrou no ciclo. Nao muda depois.', max_length=20, verbose_name='Ponto de entrada')),
                ('origem_cadastro', models.CharField(choices=[('rh', 'RH'), ('link_publico', 'Link publico'), ('importacao', 'Importacao'), ('api', 'API')], default='rh', max_length=20, verbose_name='Origem do cadastro')),
                ('pendente_revisao', models.BooleanField(default=False, help_text='Marcado quando falta CPF, o CPF e invalido, ou houve suspeita de duplicata nao resolvida.', verbose_name='Pendente de revisao do RH')),
                ('consentimento_lgpd', models.BooleanField(default=False, verbose_name='Consentimento LGPD')),
                ('consentimento_lgpd_em', models.DateTimeField(blank=True, null=True, verbose_name='Consentimento em')),
                ('consentimento_lgpd_ip', models.CharField(blank=True, default='', max_length=64, verbose_name='IP do consentimento')),
                ('consentimento_lgpd_versao', models.CharField(blank=True, default='', max_length=20, verbose_name='Versao do texto aceito')),
                ('consentimento_lgpd_user_agent', models.CharField(blank=True, default='', max_length=300, verbose_name='User agent do consentimento')),
                ('cargo', models.CharField(blank=True, default='', help_text='Texto livre por enquanto. Vira FK quando Recrutamento chegar.', max_length=120, verbose_name='Cargo')),
                ('regime_contratacao', models.CharField(blank=True, choices=[('clt', 'CLT'), ('pj', 'PJ'), ('estagio', 'Estagio'), ('aprendiz', 'Jovem aprendiz'), ('temporario', 'Temporario'), ('freelancer', 'Freelancer')], default='', max_length=20, verbose_name='Regime de contratacao')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='Data de admissao')),
                ('data_fim_experiencia', models.DateField(blank=True, null=True, verbose_name='Fim da experiencia')),
                ('prorrogacoes_experiencia', models.PositiveSmallIntegerField(default=0, verbose_name='Prorrogacoes da experiencia')),
                ('data_desligamento', models.DateField(blank=True, null=True, verbose_name='Data de desligamento')),
                ('motivo_desligamento', models.CharField(blank=True, default='', max_length=40, verbose_name='Motivo do desligamento')),
                ('elegivel_recontratacao', models.BooleanField(default=True, help_text='False impede o dedup de reativar a pessoa numa readmissao.', verbose_name='Elegivel a recontratacao')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_colaboradores_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('unidade', models.ForeignKey(help_text='PROTECT de proposito: apagar loja nao pode orfanar pessoa. Pra tirar de circulacao, desative a unidade.', on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='people.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'db_table': 'people_colaborador',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoSituacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de', models.CharField(blank=True, default='', help_text='Vazio quando e a entrada na maquina de estados.', max_length=20, verbose_name='Situacao anterior')),
                ('para', models.CharField(max_length=20, verbose_name='Situacao nova')),
                ('motivo', models.CharField(blank=True, default='', max_length=200, verbose_name='Motivo')),
                ('dados', models.JSONField(blank=True, default=dict, help_text='O que a transicao mexeu, inclusive o que foi limpo.', verbose_name='Snapshot da transicao')),
                ('origem', models.CharField(choices=[('painel', 'Painel'), ('link_publico', 'Link publico'), ('automacao', 'Automacao'), ('cron', 'Cron'), ('importacao', 'Importacao')], default='painel', max_length=20, verbose_name='Origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_situacao', to='people.colaborador', verbose_name='Colaborador')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_transicoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historico de situacao',
                'verbose_name_plural': 'Historico de situacoes',
                'db_table': 'people_historico_situacao',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['tenant', 'situacao'], name='people_col_tenant_sit_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['tenant', 'unidade', 'situacao'], name='people_col_tenant_und_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['tenant', 'cpf'], name='people_col_tenant_cpf_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['tenant', 'telefone'], name='people_col_tenant_fone_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['tenant', 'pendente_revisao', '-criado_em'], name='people_col_tenant_rev_idx'),
        ),
        migrations.AddConstraint(
            model_name='colaborador',
            constraint=models.UniqueConstraint(fields=('tenant', 'cpf'), name='people_colaborador_cpf_unico_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='colaborador',
            constraint=models.CheckConstraint(condition=models.Q(('cpf__isnull', True), ('cpf__regex', '^\\d{11}$'), _connector='OR'), name='people_colaborador_cpf_formato'),
        ),
        migrations.AddConstraint(
            model_name='colaborador',
            constraint=models.CheckConstraint(condition=models.Q(('situacao__in', ['cadastro', 'em_admissao', 'em_experiencia', 'efetivado', 'em_desligamento', 'desligado', 'freelancer'])), name='people_colaborador_situacao_valida'),
        ),
        migrations.AddIndex(
            model_name='historicosituacao',
            index=models.Index(fields=['tenant', 'colaborador', '-criado_em'], name='people_hist_col_idx'),
        ),
        migrations.AddIndex(
            model_name='historicosituacao',
            index=models.Index(fields=['tenant', 'para', '-criado_em'], name='people_hist_para_idx'),
        ),
    ]
