# Generated by Django 5.2.4 on 2026-07-20 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_colaborador_historicosituacao_and_more'),
        ('sistema', '0017_tenant_modulo_people_tenant_plano_people_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCadastroUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='secrets.token_urlsafe(32). Nao editar na mao.', max_length=64, unique=True, verbose_name='Token')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('expira_em', models.DateTimeField(blank=True, help_text='Nulo significa que nao expira sozinho.', null=True, verbose_name='Expira em')),
                ('max_submissoes', models.PositiveIntegerField(blank=True, help_text='Nulo significa ilimitado. Ao estourar, o link se desativa.', null=True, verbose_name='Maximo de submissoes')),
                ('submissoes', models.PositiveIntegerField(default=0, verbose_name='Submissoes')),
                ('ultima_submissao_em', models.DateTimeField(blank=True, null=True, verbose_name='Ultima submissao')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('desativado_em', models.DateTimeField(blank=True, null=True, verbose_name='Desativado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_links_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('rotacionado_de', models.ForeignKey(blank=True, help_text='Link anterior, quando este nasceu de um Novo Link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotacoes', to='people.linkcadastrounidade', verbose_name='Rotacionado de')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_cadastro', to='people.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Link de cadastro',
                'verbose_name_plural': 'Links de cadastro',
                'db_table': 'people_link_cadastro',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SubmissaoLinkCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('criado', 'Criado'), ('reaproveitado', 'Reaproveitado'), ('reativado', 'Reativado'), ('rejeitado', 'Rejeitado')], max_length=20, verbose_name='Resultado')),
                ('erro', models.CharField(blank=True, default='', max_length=200, verbose_name='Erro')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload (CPF mascarado)')),
                ('ip_origem', models.CharField(blank=True, default='', max_length=64, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=300, verbose_name='User agent')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissoes', to='people.colaborador', verbose_name='Colaborador')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissoes_registro', to='people.linkcadastrounidade', verbose_name='Link')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Submissao de link',
                'verbose_name_plural': 'Submissoes de link',
                'db_table': 'people_submissao_link',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='linkcadastrounidade',
            index=models.Index(fields=['tenant', 'unidade', 'ativo'], name='people_link_und_idx'),
        ),
        migrations.AddConstraint(
            model_name='linkcadastrounidade',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('unidade',), name='people_link_ativo_unico_por_unidade'),
        ),
        migrations.AddIndex(
            model_name='submissaolinkcadastro',
            index=models.Index(fields=['tenant', 'link', '-criado_em'], name='people_subm_link_idx'),
        ),
        migrations.AddIndex(
            model_name='submissaolinkcadastro',
            index=models.Index(fields=['tenant', 'resultado', '-criado_em'], name='people_subm_res_idx'),
        ),
    ]
