# Generated by Django 5.2.4 on 2026-07-20 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def converter_cargos_texto_em_entidade(apps, schema_editor):
    """
    Cria um Cargo por texto distinto e aponta a FK do colaborador.

    Agrupa por nome normalizado (sem espaco sobrando, sem diferenca de caixa),
    que e justamente o problema que motivou tirar cargo de texto livre:
    "Atendente", "atendente" e "Atendente " sao o mesmo cargo e viravam tres.
    O nome que fica e a primeira grafia encontrada.
    """
    Colaborador = apps.get_model('people', 'Colaborador')
    Cargo = apps.get_model('people', 'Cargo')

    por_tenant_e_chave = {}
    for colaborador in Colaborador.objects.exclude(cargo='').exclude(cargo=None).iterator():
        nome = ' '.join((colaborador.cargo or '').split())
        if not nome:
            continue
        chave = (colaborador.tenant_id, nome.casefold())

        cargo = por_tenant_e_chave.get(chave)
        if cargo is None:
            cargo, _ = Cargo.objects.get_or_create(
                tenant_id=colaborador.tenant_id, nome=nome,
                defaults={'descricao': '', 'ativo': True, 'ordem': 0},
            )
            por_tenant_e_chave[chave] = cargo

        Colaborador.objects.filter(pk=colaborador.pk).update(cargo_ref=cargo.pk)


def reverter_cargos_entidade_em_texto(apps, schema_editor):
    """Volta o nome do cargo pra coluna de texto, sem apagar os Cargo criados."""
    Colaborador = apps.get_model('people', 'Colaborador')
    for colaborador in Colaborador.objects.exclude(cargo_ref=None).select_related('cargo_ref'):
        Colaborador.objects.filter(pk=colaborador.pk).update(cargo=colaborador.cargo_ref.nome)


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_linkcadastrounidade_submissaolinkcadastro_and_more'),
        ('sistema', '0017_tenant_modulo_people_tenant_plano_people_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do cargo')),
                ('descricao', models.TextField(blank=True, default='', help_text='Responsabilidades. Aparece na abertura de vaga.', verbose_name='Descricao do cargo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'people_cargo',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='MensagemEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('cadastro', 'Cadastro'), ('em_admissao', 'Em admissao'), ('em_experiencia', 'Em experiencia'), ('efetivado', 'Efetivado'), ('ferias', 'Ferias'), ('afastamento', 'Afastamento'), ('em_desligamento', 'Em desligamento'), ('desligado', 'Desligado'), ('freelancer', 'Freelancer')], help_text='Situacao em que a mensagem fica disponivel.', max_length=20, verbose_name='Etapa')),
                ('texto', models.TextField(help_text='Aceita {{nome}}, {{primeiro_nome}}, {{unidade}} e {{cargo}}.', verbose_name='Mensagem padrao')),
                ('escopo', models.CharField(choices=[('tenant', 'Toda a empresa'), ('unidades', 'Unidades especificas')], default='tenant', max_length=10, verbose_name='Aplicado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mensagem de etapa',
                'verbose_name_plural': 'Mensagens de etapa',
                'db_table': 'people_mensagem_etapa',
                'ordering': ['etapa'],
            },
        ),
        migrations.CreateModel(
            name='TemplateFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do template')),
                ('descricao', models.CharField(blank=True, default='', max_length=200, verbose_name='Descricao')),
                ('campos', models.JSONField(blank=True, default=dict, help_text='Por campo: solicitar, obrigatorio e rotulo.', verbose_name='Configuracao dos campos')),
                ('padrao', models.BooleanField(default=False, help_text='Usado quando o link nao aponta pra nenhum template.', verbose_name='Template padrao')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de formulario',
                'verbose_name_plural': 'Templates de formulario',
                'db_table': 'people_template_formulario',
                'ordering': ['-padrao', 'nome'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='colaborador',
            name='people_colaborador_situacao_valida',
        ),
        migrations.RemoveConstraint(
            model_name='linkcadastrounidade',
            name='people_link_ativo_unico_por_unidade',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='fim_previsto_afastamento',
            field=models.DateField(blank=True, null=True, verbose_name='Retorno previsto'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='inicio_afastamento',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio do afastamento ou das ferias'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='motivo_afastamento',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Motivo do afastamento'),
        ),
        migrations.AddField(
            model_name='linkcadastrounidade',
            name='nome',
            field=models.CharField(blank=True, default='', help_text='Como o RH distingue este link dos outros da mesma loja. Ex: Mutirao de julho, Turno da noite.', max_length=120, verbose_name='Nome do link'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='situacao',
            field=models.CharField(choices=[('cadastro', 'Cadastro'), ('em_admissao', 'Em admissao'), ('em_experiencia', 'Em experiencia'), ('efetivado', 'Efetivado'), ('ferias', 'Ferias'), ('afastamento', 'Afastamento'), ('em_desligamento', 'Em desligamento'), ('desligado', 'Desligado'), ('freelancer', 'Freelancer')], db_index=True, default='cadastro', help_text='So muda por mover_situacao(). Ver apps/people/estados.py.', max_length=20, verbose_name='Situacao'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cargo_ref',
            field=models.ForeignKey(blank=True, help_text='PROTECT: apagar cargo com gente dentro reescreveria historico. Pra tirar de circulacao, desative o cargo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='people.cargo', verbose_name='Cargo'),
        ),
        migrations.AddConstraint(
            model_name='colaborador',
            constraint=models.CheckConstraint(condition=models.Q(('situacao__in', ['cadastro', 'em_admissao', 'em_experiencia', 'efetivado', 'ferias', 'afastamento', 'em_desligamento', 'desligado', 'freelancer'])), name='people_colaborador_situacao_valida'),
        ),
        migrations.AddField(
            model_name='mensagemetapa',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='mensagemetapa',
            name='unidades',
            field=models.ManyToManyField(blank=True, help_text='So vale quando o escopo e por unidades.', related_name='mensagens_etapa', to='people.unidade', verbose_name='Unidades'),
        ),
        migrations.AddField(
            model_name='templateformulario',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='linkcadastrounidade',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Qual formulario o colaborador preenche. Vazio usa o padrao do tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='people.templateformulario', verbose_name='Formulario'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['tenant', 'ativo'], name='people_cargo_ativo_idx'),
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(fields=('tenant', 'nome'), name='people_cargo_nome_unico_por_tenant'),
        ),
        migrations.AddIndex(
            model_name='mensagemetapa',
            index=models.Index(fields=['tenant', 'etapa', 'ativo'], name='people_msg_etapa_idx'),
        ),
        migrations.AddIndex(
            model_name='templateformulario',
            index=models.Index(fields=['tenant', 'ativo'], name='people_tpl_ativo_idx'),
        ),
        migrations.AddConstraint(
            model_name='templateformulario',
            constraint=models.UniqueConstraint(fields=('tenant', 'nome'), name='people_template_nome_unico_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='templateformulario',
            constraint=models.UniqueConstraint(condition=models.Q(('padrao', True)), fields=('tenant',), name='people_template_um_padrao_por_tenant'),
        ),

        # ── Cargo: de texto pra entidade ────────────────────────────────────
        #
        # Nao da pra converter CharField em ForeignKey num AlterField: o banco
        # nao sabe transformar "Gerente" no id de uma linha que ainda nao existe.
        # Por isso os tres passos: cria o cargo a partir do texto, aponta a FK, e
        # so entao derruba a coluna antiga.
        migrations.RunPython(converter_cargos_texto_em_entidade,
                             reverter_cargos_entidade_em_texto),
        migrations.RemoveField(
            model_name='colaborador',
            name='cargo',
        ),
        migrations.RenameField(
            model_name='colaborador',
            old_name='cargo_ref',
            new_name='cargo',
        ),
    ]
