# Generated by Django 5.2.4 on 2026-07-20 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_cargo_mensagemetapa_templateformulario_and_more'),
        ('sistema', '0017_tenant_modulo_people_tenant_plano_people_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicosituacao',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Histórico de situação', 'verbose_name_plural': 'Histórico de situações'},
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='origem_cadastro',
            field=models.CharField(choices=[('rh', 'RH'), ('link_publico', 'Link público'), ('importacao', 'Importação'), ('api', 'API')], default='rh', max_length=20, verbose_name='Origem do cadastro'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='ponto_entrada',
            field=models.CharField(choices=[('so_cadastro', 'Só cadastrar por enquanto'), ('em_admissao', 'Ainda em admissão'), ('ja_trabalhando', 'Já está trabalhando'), ('link_publico', 'Auto cadastro por link')], default='so_cadastro', help_text='Por qual porta a pessoa entrou no ciclo. Nao muda depois.', max_length=20, verbose_name='Ponto de entrada'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='regime_contratacao',
            field=models.CharField(blank=True, choices=[('clt', 'CLT'), ('pj', 'PJ'), ('estagio', 'Estágio'), ('aprendiz', 'Jovem aprendiz'), ('temporario', 'Temporário'), ('freelancer', 'Freelancer')], default='', max_length=20, verbose_name='Regime de contratacao'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='situacao',
            field=models.CharField(choices=[('cadastro', 'Cadastro'), ('em_admissao', 'Em admissão'), ('em_experiencia', 'Em experiência'), ('efetivado', 'Efetivado'), ('ferias', 'Férias'), ('afastamento', 'Afastamento'), ('em_desligamento', 'Em desligamento'), ('desligado', 'Desligado'), ('freelancer', 'Freelancer')], db_index=True, default='cadastro', help_text='So muda por mover_situacao(). Ver apps/people/estados.py.', max_length=20, verbose_name='Situacao'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='tipo_chave_pix',
            field=models.CharField(blank=True, choices=[('cpf', 'CPF'), ('celular', 'Celular'), ('email', 'Email'), ('aleatoria', 'Chave aleatória')], default='', max_length=20, verbose_name='Tipo de chave Pix'),
        ),
        migrations.AlterField(
            model_name='historicosituacao',
            name='origem',
            field=models.CharField(choices=[('painel', 'Painel'), ('link_publico', 'Link público'), ('automacao', 'Automação'), ('cron', 'Cron'), ('importacao', 'Importação')], default='painel', max_length=20, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='mensagemetapa',
            name='escopo',
            field=models.CharField(choices=[('tenant', 'Toda a empresa'), ('unidades', 'Unidades específicas')], default='tenant', max_length=10, verbose_name='Aplicado em'),
        ),
        migrations.AlterField(
            model_name='mensagemetapa',
            name='etapa',
            field=models.CharField(choices=[('cadastro', 'Cadastro'), ('em_admissao', 'Em admissão'), ('em_experiencia', 'Em experiência'), ('efetivado', 'Efetivado'), ('ferias', 'Férias'), ('afastamento', 'Afastamento'), ('em_desligamento', 'Em desligamento'), ('desligado', 'Desligado'), ('freelancer', 'Freelancer')], help_text='Situacao em que a mensagem fica disponivel.', max_length=20, verbose_name='Etapa'),
        ),
        migrations.CreateModel(
            name='EtapaPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome da etapa')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('ativa', models.BooleanField(default=True, help_text='Etapa desativada some do board pra novos candidatos, porem quem ja esta nela continua visivel.', verbose_name='Ativa')),
                ('sla_dias', models.PositiveSmallIntegerField(blank=True, help_text='Depois disso o candidato aparece como atrasado nesta etapa.', null=True, verbose_name='Prazo máximo (dias)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('unidade', models.ForeignKey(blank=True, help_text='Em branco significa que a etapa vale pro tenant inteiro.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etapas_pipeline', to='people.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Etapa do pipeline',
                'verbose_name_plural': 'Etapas do pipeline',
                'db_table': 'people_etapa_pipeline',
                'ordering': ['ordem', 'id'],
                'indexes': [models.Index(fields=['tenant', 'unidade', 'ordem'], name='people_etapa_escopo_idx'), models.Index(fields=['tenant', 'ativa'], name='people_etapa_ativa_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'unidade', 'nome'), name='people_etapa_nome_unico_por_escopo', nulls_distinct=False)],
            },
        ),
    ]
