# Generated by Django 5.2.4 on 2026-07-20 18:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_historicosituacao_options_and_more'),
        ('sistema', '0017_tenant_modulo_people_tenant_plano_people_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', help_text='Em branco usa o nome do cargo. Preencha quando a mesma função tiver recortes diferentes, tipo Atendente noturno.', max_length=140, verbose_name='Título da vaga')),
                ('tipo_contratacao', models.CharField(blank=True, default='', max_length=20, verbose_name='Tipo de contratação')),
                ('turno', models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('integral', 'Integral'), ('escala', 'Escala')], default='', max_length=20, verbose_name='Turno esperado')),
                ('justificativa', models.CharField(choices=[('aumento_quadro', 'Aumento de quadro'), ('substituicao', 'Substituição')], max_length=20, verbose_name='Justificativa')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('limite_aprovados', models.PositiveSmallIntegerField(default=50, help_text='Ao atingir, a triagem para. A captação continua.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Limite de aprovados')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicada', 'Publicada'), ('pausada', 'Pausada'), ('encerrada', 'Encerrada')], db_index=True, default='rascunho', max_length=20, verbose_name='Status')),
                ('publicada_em', models.DateTimeField(blank=True, null=True)),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vagas', to='people.cargo', verbose_name='Cargo')),
                ('colaborador_substituido', models.ForeignKey(blank=True, help_text='So faz sentido quando a justificativa e substituição.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vagas_de_substituicao', to='people.colaborador', verbose_name='Colaborador substituído')),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas_criadas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vagas', to='people.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'db_table': 'people_vaga',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RequisitoVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200, verbose_name='Requisito')),
                ('obrigatorio', models.BooleanField(default=True, help_text='Obrigatório ou desejável.', verbose_name='Obrigatório')),
                ('aparece_no_anuncio', models.BooleanField(default=True, verbose_name='Aparece no anúncio')),
                ('usar_na_triagem', models.BooleanField(default=False, verbose_name='Usar como critério de triagem')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='people.vaga', verbose_name='Vaga')),
            ],
            options={
                'verbose_name': 'Requisito da vaga',
                'verbose_name_plural': 'Requisitos da vaga',
                'db_table': 'people_requisito_vaga',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='vaga',
            index=models.Index(fields=['tenant', 'status', '-criado_em'], name='people_vaga_status_idx'),
        ),
        migrations.AddIndex(
            model_name='vaga',
            index=models.Index(fields=['tenant', 'unidade', 'status'], name='people_vaga_unidade_idx'),
        ),
        migrations.AddConstraint(
            model_name='vaga',
            constraint=models.CheckConstraint(condition=models.Q(('limite_aprovados__gte', 1)), name='people_vaga_limite_aprovados_minimo'),
        ),
        migrations.AddConstraint(
            model_name='vaga',
            constraint=models.CheckConstraint(condition=models.Q(('justificativa', 'substituicao'), ('colaborador_substituido__isnull', True), _connector='OR'), name='people_vaga_substituido_exige_justificativa'),
        ),
        migrations.AddIndex(
            model_name='requisitovaga',
            index=models.Index(fields=['tenant', 'vaga', 'ordem'], name='people_requisito_vaga_idx'),
        ),
        migrations.AddConstraint(
            model_name='requisitovaga',
            constraint=models.CheckConstraint(condition=models.Q(('aparece_no_anuncio', True), ('usar_na_triagem', True), _connector='OR'), name='people_requisito_precisa_de_um_uso'),
        ),
    ]
