# Generated by Django 5.2.4 on 2026-07-20 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_vaga_requisitovaga_vaga_people_vaga_status_idx_and_more'),
        ('sistema', '0017_tenant_modulo_people_tenant_plano_people_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCandidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('cartaz', 'Cartaz ou QR impresso'), ('indicacao', 'Indicação'), ('outro', 'Outro')], help_text='Onde este link vai ser divulgado. É o que permite saber depois qual canal trouxe candidato.', max_length=20, verbose_name='Canal')),
                ('apelido_interno', models.CharField(blank=True, default='', help_text='Como o RH distingue este link dos outros. Ex: Grupo de empregos da zona sul.', max_length=120, verbose_name='Apelido interno')),
                ('token', models.CharField(db_index=True, help_text='secrets.token_urlsafe(32). Nao editar na mao.', max_length=64, unique=True, verbose_name='Token')),
                ('cta', models.CharField(blank=True, default='', help_text='Frase que abre o anúncio.', max_length=140, verbose_name='Chamada para ação')),
                ('telefone_contato', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone de contato')),
                ('texto_compartilhamento', models.TextField(blank=True, default='', help_text='Gerado a partir da vaga e editável. A vaga continua sendo a fonte da verdade.', verbose_name='Texto de divulgação')),
                ('candidaturas', models.PositiveIntegerField(default=0, help_text='Quantas chegaram por este link. É a atribuição de canal.', verbose_name='Candidaturas')),
                ('ultima_candidatura_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('desativado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links_candidatura_criados', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_candidatura', to='people.unidade', verbose_name='Unidade')),
                ('vaga', models.ForeignKey(blank=True, help_text='Em branco, o link e de banco de talentos: capta sem vaga aberta.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='people.vaga', verbose_name='Vaga')),
            ],
            options={
                'verbose_name': 'Link de candidatura',
                'verbose_name_plural': 'Links de candidatura',
                'db_table': 'people_link_candidatura',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tenant', 'vaga', 'ativo'], name='people_link_cand_vaga_idx'), models.Index(fields=['tenant', 'unidade', 'canal'], name='people_link_cand_canal_idx')],
            },
        ),
    ]
