# Generated by Django 5.2.4 on 2026-07-20 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_seed_pipeline_tenants_existentes'),
        ('sistema', '0017_tenant_modulo_people_tenant_plano_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaopeople',
            name='dias_retencao_candidato',
            field=models.PositiveSmallIntegerField(default=365, help_text='Depois deste prazo sem movimentacao, o candidato nao contratado e anonimizado. O prazo e declarado no consentimento do formulario publico. 0 desliga o expurgo.', verbose_name='Retencao do banco de talentos (dias)'),
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('whatsapp', models.CharField(blank=True, default=None, help_text='So digitos, E.164 sem o mais. Ex: 5586999998888.', max_length=15, null=True, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('cidade', models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, default='', max_length=2, verbose_name='Estado')),
                ('bairro', models.CharField(blank=True, default='', max_length=100, verbose_name='Bairro')),
                ('experiencia_previa', models.CharField(blank=True, default='', max_length=200, verbose_name='Experiência prévia')),
                ('disponibilidade_horario', models.CharField(blank=True, default='', max_length=200, verbose_name='Disponibilidade de horário')),
                ('curriculo', models.FileField(blank=True, null=True, upload_to='people/curriculos/%Y/%m/', verbose_name='Currículo')),
                ('saida', models.CharField(blank=True, choices=[('admitido', 'Admitido'), ('banco_talentos', 'Banco de talentos'), ('inapto', 'Inapto'), ('arquivado', 'Arquivado')], db_index=True, default='', help_text='Vazio significa que ainda esta no pipeline.', max_length=20, verbose_name='Saída')),
                ('motivo_saida', models.TextField(blank=True, default='', verbose_name='Motivo da saída')),
                ('consentimento_lgpd', models.BooleanField(default=False)),
                ('consentimento_em', models.DateTimeField(blank=True, null=True)),
                ('consentimento_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('consentimento_versao', models.CharField(blank=True, default='', max_length=20)),
                ('consentimento_user_agent', models.TextField(blank=True, default='')),
                ('retencao_ate', models.DateField(blank=True, help_text='Depois desta data o cron anonimiza. Prazo declarado no consentimento.', null=True, verbose_name='Reter até')),
                ('anonimizado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(blank=True, help_text='Preenchido na admissão. Ver a ponte no docstring da classe.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidaturas', to='people.colaborador', verbose_name='Colaborador')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatos', to='people.etapapipeline', verbose_name='Etapa')),
                ('link_origem', models.ForeignKey(blank=True, help_text='Como a atribuição de canal sobrevive à exclusão do link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatos', to='people.linkcandidatura', verbose_name='Link de origem')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatos', to='people.unidade', verbose_name='Unidade')),
                ('vaga', models.ForeignKey(blank=True, help_text='Nulo quando veio por link de banco de talentos.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidatos', to='people.vaga', verbose_name='Vaga')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'db_table': 'people_candidato',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tenant', 'vaga', 'etapa'], name='people_cand_pipeline_idx'), models.Index(fields=['tenant', 'saida'], name='people_cand_saida_idx'), models.Index(fields=['tenant', 'retencao_ate'], name='people_cand_retencao_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'whatsapp'), name='people_candidato_whatsapp_unico_por_tenant'), models.CheckConstraint(condition=models.Q(('whatsapp__isnull', True), ('whatsapp__regex', '^\\d{10,15}$'), _connector='OR'), name='people_candidato_whatsapp_formato')],
            },
        ),
    ]
