# Generated by Django 5.2.4 on 2026-07-20 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_configuracaopeople_dias_retencao_candidato_candidato'),
        ('sistema', '0017_tenant_modulo_people_tenant_plano_people_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_etapa', models.CharField(blank=True, default='', max_length=80, verbose_name='De (etapa)')),
                ('para_etapa', models.CharField(blank=True, default='', max_length=80, verbose_name='Para (etapa)')),
                ('para_saida', models.CharField(blank=True, choices=[('admitido', 'Admitido'), ('banco_talentos', 'Banco de talentos'), ('inapto', 'Inapto'), ('arquivado', 'Arquivado')], default='', max_length=20, verbose_name='Para (saída)')),
                ('motivo', models.TextField(blank=True, default='', verbose_name='Motivo')),
                ('origem', models.CharField(default='painel', max_length=20, verbose_name='Origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='people.candidato', verbose_name='Candidato')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico do candidato',
                'verbose_name_plural': 'Histórico dos candidatos',
                'db_table': 'people_historico_candidato',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tenant', 'candidato', '-criado_em'], name='people_hist_cand_idx'), models.Index(fields=['tenant', 'para_saida', '-criado_em'], name='people_hist_cand_saida_idx')],
            },
        ),
    ]
