# Generated by Django 5.2.4 on 2026-07-20 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_historicocandidato'),
        ('sistema', '0017_tenant_modulo_people_tenant_plano_people_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadroUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quadro_definido', models.PositiveSmallIntegerField(default=0, help_text='Quantas posições deste cargo a unidade deve ter.', verbose_name='Quadro definido')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadros', to='people.cargo', verbose_name='Cargo')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadros', to='people.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Quadro da unidade',
                'verbose_name_plural': 'Quadros das unidades',
                'db_table': 'people_quadro_unidade',
                'ordering': ['unidade__nome', 'cargo__nome'],
                'indexes': [models.Index(fields=['tenant', 'unidade'], name='people_quadro_und_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'unidade', 'cargo'), name='people_quadro_unico_por_unidade_cargo')],
            },
        ),
    ]
