# Generated by Django 5.2.4 on 2026-07-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_quadrounidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='carga_horaria',
            field=models.CharField(blank=True, default='', help_text='Ex: 30h semanais (6h/dia).', max_length=80, verbose_name='Carga horária'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='descricao',
            field=models.TextField(blank=True, default='', help_text='Narrativa que o candidato lê: sobre a vaga, o que vai fazer, o que a empresa oferece.', verbose_name='Descrição da vaga'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='modelo_trabalho',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('hibrido', 'Híbrido'), ('remoto', 'Remoto')], default='', max_length=20, verbose_name='Modelo de trabalho'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='remuneracao',
            field=models.CharField(blank=True, default='', help_text='Ex: Bolsa-auxílio de R$ 700,00. Texto livre porque varia muito (fixo, faixa, mais comissão).', max_length=80, verbose_name='Remuneração'),
        ),
    ]
