# Generated by Django 5.2.4 on 2026-07-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_vaga_carga_horaria_vaga_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='config_campos',
            field=models.JSONField(blank=True, default=dict, help_text='Quais campos a candidatura pede e quais sao obrigatorios. Vazio usa o padrao. Ver apps/people/campos_candidatura.py.', verbose_name='Campos do formulário'),
        ),
    ]
