# Generated by Django 5.2.4 on 2026-07-21 04:38

import apps.people.models_recrutamento
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_vaga_config_campos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='curriculo',
            field=models.FileField(blank=True, help_text='Storage privado, fora de /media/. Servido só pela view auth-gated.', null=True, storage=apps.people.models_recrutamento.PrivateCurriculoStorage(), upload_to='%Y/%m/', verbose_name='Currículo'),
        ),
    ]
