# Generated by Django 5.2.4 on 2026-07-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_alter_candidato_curriculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapapipeline',
            name='cor',
            field=models.CharField(blank=True, default='', help_text='Chave da paleta (ver CORES_ETAPA). Vazio usa a cor da ordem.', max_length=20, verbose_name='Cor'),
        ),
    ]
