# Generated by Django 5.2.4 on 2026-07-21 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_etapapipeline_cor'),
        ('sistema', '0017_tenant_modulo_people_tenant_plano_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='dados_custom',
            field=models.JSONField(blank=True, default=dict, help_text='Chave e o slug do CampoCandidatura. Vive em JSON porque o tenant inventa o campo e nao da pra virar coluna.', verbose_name='Respostas dos campos custom'),
        ),
        migrations.CreateModel(
            name='CampoCandidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='O que o candidato le. Ex: Tem CNH categoria B?', max_length=100, verbose_name='Rótulo do campo')),
                ('slug', models.SlugField(help_text='Identificador em dados_custom. Nao muda depois de criado.', max_length=60, verbose_name='Chave')),
                ('tipo', models.CharField(choices=[('text', 'Texto curto'), ('textarea', 'Texto longo'), ('number', 'Número'), ('date', 'Data'), ('select', 'Lista de opções'), ('bool', 'Sim ou não')], default='text', max_length=20, verbose_name='Tipo')),
                ('opcoes', models.JSONField(blank=True, default=list, help_text='Só para o tipo lista. Uma opção por linha.', verbose_name='Opções')),
                ('ajuda', models.CharField(blank=True, default='', max_length=200, verbose_name='Texto de ajuda')),
                ('secao', models.CharField(default='experiencia', help_text='Em que bloco do formulário o campo aparece.', max_length=20, verbose_name='Seção')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, help_text='Desativado some do formulário, sem apagar o que já foi respondido.', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Campo de candidatura',
                'verbose_name_plural': 'Campos de candidatura',
                'db_table': 'people_campo_candidatura',
                'ordering': ['ordem', 'nome'],
                'indexes': [models.Index(fields=['tenant', 'ativo', 'ordem'], name='people_campo_cand_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'slug'), name='people_campo_cand_slug_unico_por_tenant')],
            },
        ),
    ]
