# Generated by Django 5.2.4 on 2026-07-21 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_linkcandidatura_medindo_visitas_desde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkcandidatura',
            name='medindo_visitas_desde',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Link criado antes da medicao tem candidatura sem visita correspondente, e a taxa mentiria. Guardar a data permite dizer isso em vez de exibir um numero quebrado.', null=True, verbose_name='Medindo visitas desde'),
        ),
    ]
