# Generated by Django 5.2.4 on 2026-07-21 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_alter_linkcandidatura_medindo_visitas_desde'),
        ('sistema', '0017_tenant_modulo_people_tenant_plano_people_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemRecrutamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida', models.CharField(blank=True, choices=[('admitido', 'Admitido'), ('banco_talentos', 'Banco de talentos'), ('inapto', 'Inapto'), ('arquivado', 'Arquivado')], default='', help_text='Mensagem sugerida quando o candidato sai por este motivo.', max_length=20, verbose_name='Saída')),
                ('texto', models.TextField(help_text='Aceita {{nome}}, {{primeiro_nome}}, {{vaga}}, {{unidade}} e {{cargo}}.', verbose_name='Mensagem padrão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('etapa', models.ForeignKey(blank=True, help_text='Mensagem sugerida quando o candidato chega nesta etapa.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='people.etapapipeline', verbose_name='Etapa')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Mensagem de recrutamento',
                'verbose_name_plural': 'Mensagens de recrutamento',
                'db_table': 'people_mensagem_recrutamento',
                'ordering': ['saida', 'etapa__ordem'],
                'indexes': [models.Index(fields=['tenant', 'ativo'], name='people_msg_recr_ativo_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('etapa__isnull', False), ('saida', '')), models.Q(('etapa__isnull', True), models.Q(('saida', ''), _negated=True)), _connector='OR'), name='people_msg_recr_etapa_ou_saida'), models.UniqueConstraint(condition=models.Q(('etapa__isnull', False)), fields=('tenant', 'etapa'), name='people_msg_recr_uma_por_etapa'), models.UniqueConstraint(condition=models.Q(('saida', ''), _negated=True), fields=('tenant', 'saida'), name='people_msg_recr_uma_por_saida')],
            },
        ),
    ]
