# Generated by Django 5.2.4 on 2026-07-21 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0020_mensagemrecrutamento'),
        ('sistema', '0017_tenant_modulo_people_tenant_plano_people_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veredito', models.CharField(choices=[('apto', 'Apto'), ('atencao', 'Apto com ressalvas'), ('inapto', 'Fora dos requisitos'), ('insuficiente', 'Informação insuficiente')], max_length=20, verbose_name='Veredito sugerido')),
                ('resumo', models.TextField(blank=True, default='', help_text='Duas ou tres linhas sobre o perfil.', verbose_name='Resumo')),
                ('sinais_de_atencao', models.JSONField(blank=True, default=list, help_text='Lista de pontos que o RH deve conferir na entrevista.', verbose_name='Sinais de atenção')),
                ('requisitos_avaliados', models.JSONField(blank=True, default=list, help_text='Por requisito: texto, se atende e por que. É a rastreabilidade da sugestão.', verbose_name='Requisitos avaliados')),
                ('modelo', models.CharField(blank=True, default='', max_length=60, verbose_name='Modelo usado')),
                ('tokens_entrada', models.PositiveIntegerField(default=0)),
                ('tokens_saida', models.PositiveIntegerField(default=0)),
                ('usou_curriculo', models.BooleanField(default=False, help_text='Falso quando o arquivo não pôde ser lido (imagem, PDF protegido). A análise sai só com o formulário.', verbose_name='Leu o currículo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='people.candidato', verbose_name='Candidato')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_candidato', to=settings.AUTH_USER_MODEL, verbose_name='Pedida por')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Análise de candidato',
                'verbose_name_plural': 'Análises de candidato',
                'db_table': 'people_analise_candidato',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tenant', 'candidato', '-criado_em'], name='people_analise_cand_idx')],
            },
        ),
    ]
