# Generated by Django 5.2.4 on 2026-07-21 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0021_analisecandidato'),
        ('sistema', '0017_tenant_modulo_people_tenant_plano_people_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotacaoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, default='', verbose_name='Anotações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anotacoes_etapa', to=settings.AUTH_USER_MODEL, verbose_name='Última edição de')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='people.candidato', verbose_name='Candidato')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='people.etapapipeline', verbose_name='Etapa')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Anotação de etapa',
                'verbose_name_plural': 'Anotações de etapa',
                'db_table': 'people_anotacao_etapa',
                'ordering': ['etapa__ordem'],
                'indexes': [models.Index(fields=['tenant', 'candidato'], name='people_anot_etapa_idx')],
                'constraints': [models.UniqueConstraint(fields=('candidato', 'etapa'), name='people_anotacao_uma_por_etapa')],
            },
        ),
    ]
