# Generated by Django 5.2.4 on 2026-07-21 23:24

"""
Blocos por etapa: e o que faz cada aba da ficha ter conteudo proprio.

O BACK-FILL importa mais que os campos. Sem ele, toda etapa que ja existe fica
com `blocos=[]` e a aba nasce VAZIA, inclusive em producao. Casa pelo NOME com
as sete etapas padrao; etapa que o cliente criou (nome fora da lista) recebe o
conjunto minimo (anotacao mais mensagem), que serve pra qualquer coisa e nao
inventa comportamento que ninguem pediu.
"""
from django.db import migrations, models


def preencher_blocos(apps, schema_editor):
    from apps.people import estados_recrutamento as estados_rs

    Etapa = apps.get_model('people', 'EtapaPipeline')

    por_nome = {e['nome']: e for e in estados_rs.ETAPAS_PADRAO}

    # Nomes ANTIGOS, que sairam da spec de handoff e foram semeados antes de a
    # gente confrontar com o print do produto rodando. Tenant provisionado
    # naquela epoca tem esses nomes gravados, e sem este mapa o back-fill nao
    # os reconheceria e daria o conjunto minimo a todas as etapas.
    #
    # Nao depender da ordem entre renomear em prod e rodar a migration: o
    # operador nao deveria precisar acertar a sequencia pra o dado sair certo.
    APELIDOS = {
        'Triagem': 'Análise de inscrição',
        'Teste Comportamental': 'Perfil comportamental',
        'Seleção': 'Entrevista / Seleção',
        'Teste prático': 'Teste Prático',
        # "Histórico" nao tem equivalente: nao existe no produto real. Cai no
        # minimo, e o cliente decide se apaga.
    }

    minimo = [estados_rs.BLOCO_ANOTACAO, estados_rs.BLOCO_MENSAGEM]

    atualizadas = []
    for etapa in Etapa.objects.all():
        if etapa.blocos:
            continue
        padrao = por_nome.get(etapa.nome) or por_nome.get(
            APELIDOS.get(etapa.nome, ''))
        etapa.blocos = padrao['blocos'] if padrao else minimo
        if estados_rs.BLOCO_ROTEIRO in etapa.blocos and not etapa.roteiro:
            etapa.roteiro = estados_rs.ROTEIRO_PADRAO
        if estados_rs.BLOCO_CHECKLIST in etapa.blocos and not etapa.checklist:
            etapa.checklist = estados_rs.CHECKLIST_PADRAO
        atualizadas.append(etapa)

    if atualizadas:
        Etapa.objects.bulk_update(atualizadas,
                                  ['blocos', 'roteiro', 'checklist'],
                                  batch_size=200)


def desfazer(apps, schema_editor):
    """Nada a desfazer: as colunas saem no reverse dos AddField."""


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_anotacaoetapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacaoetapa',
            name='agendado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Agendado para'),
        ),
        migrations.AddField(
            model_name='anotacaoetapa',
            name='agendado_local',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='anotacaoetapa',
            name='decisao',
            field=models.CharField(blank=True, choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='', max_length=20, verbose_name='Decisão'),
        ),
        migrations.AddField(
            model_name='anotacaoetapa',
            name='itens_marcados',
            field=models.JSONField(blank=True, default=list, help_text='Perguntas do roteiro e requisitos do checklist ja cobertos.', verbose_name='Itens já verificados'),
        ),
        migrations.AddField(
            model_name='etapapipeline',
            name='blocos',
            field=models.JSONField(blank=True, default=list, help_text='O que aparece na aba desta etapa. Ver BLOCOS em estados_recrutamento.py.', verbose_name='Blocos da ficha'),
        ),
        migrations.AddField(
            model_name='etapapipeline',
            name='checklist',
            field=models.JSONField(blank=True, default=list, help_text='Itens objetivos do bloco de checklist, um por linha.', verbose_name='Requisitos a validar'),
        ),
        migrations.AddField(
            model_name='etapapipeline',
            name='roteiro',
            field=models.JSONField(blank=True, default=list, help_text='Perguntas do bloco de roteiro, uma por linha.', verbose_name='Roteiro da conversa'),
        ),
            migrations.RunPython(preencher_blocos, desfazer),
    ]
