# Generated by Django 5.2.4 on 2026-07-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_anotacaoetapa_agendado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='motivo_saida_codigo',
            field=models.CharField(blank=True, choices=[('perfil_fora', 'Perfil fora dos requisitos mínimos'), ('desistiu', 'Desistiu do processo'), ('nao_retornou', 'Não retornou o contato'), ('falta_entrevista', 'Não compareceu à entrevista'), ('falta_teste', 'Não compareceu ao teste prático'), ('indisponibilidade', 'Indisponibilidade de horário'), ('sem_vaga', 'Sem vaga aberta no momento'), ('outro', 'Outro')], default='', help_text="Lista fechada. Com texto livre nunca da pra responder 'por que a gente reprova', porque cada RH escreve diferente.", max_length=30, verbose_name='Motivo da saída'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='motivo_saida',
            field=models.TextField(blank=True, default='', help_text="Complemento em texto livre. Obrigatorio quando o motivo e 'Outro', que sozinho nao diz nada.", verbose_name='Detalhe do motivo'),
        ),
    ]
