# Generated by Django 5.2.4 on 2026-07-24 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0024_candidato_motivo_saida_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='aprovada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovada ou rejeitada por'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='decidida_em',
            field=models.DateTimeField(blank=True, help_text='Quando o RH aprovou ou rejeitou a requisição.', null=True, verbose_name='Decidida em'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, default='', help_text='Obrigatório ao rejeitar. É o que o gestor lê para corrigir e reenviar.', verbose_name='Motivo da rejeição'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('aguardando_aprovacao', 'Aguardando aprovação'), ('rascunho', 'Rascunho'), ('publicada', 'Publicada'), ('pausada', 'Pausada'), ('encerrada', 'Encerrada'), ('rejeitada', 'Rejeitada')], db_index=True, default='rascunho', max_length=20, verbose_name='Status'),
        ),
    ]
