# Generated by Django 5.2.4 on 2026-03-31 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clube', '0001_initial'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicacaoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Megalink', help_text='Título principal da página', max_length=255)),
                ('subtitulo', models.CharField(default='Clube de Fidelidade', help_text='Subtítulo abaixo do título', max_length=255)),
                ('texto_indicador', models.CharField(default='Você foi indicado por', help_text='Texto acima do nome do indicador', max_length=255)),
                ('texto_botao', models.CharField(default='Enviar Indicação', help_text='Texto do botão de envio', max_length=100)),
                ('texto_sucesso_titulo', models.CharField(default='Indicação Registrada!', help_text='Título da mensagem de sucesso', max_length=255)),
                ('texto_sucesso_msg', models.TextField(default='Sua indicação foi recebida com sucesso. Em breve a equipe da Megalink entrará em contato.', help_text='Mensagem de sucesso')),
                ('logo', models.ImageField(blank=True, help_text='Logo exibida no topo da página', null=True, upload_to='indicacoes/')),
                ('imagem_fundo', models.ImageField(blank=True, help_text='Imagem de fundo da página', null=True, upload_to='indicacoes/')),
                ('cor_fundo', models.CharField(default='#0f1b2d', help_text='Cor de fundo (hex). Ignorada se tiver imagem de fundo', max_length=7)),
                ('cor_botao', models.CharField(default='#0f1b2d', help_text='Cor do botão de envio (hex)', max_length=7)),
                ('mostrar_campo_cpf', models.BooleanField(default=True, help_text='Exibir campo de CPF no formulário')),
                ('mostrar_campo_cidade', models.BooleanField(default=True, help_text='Exibir campo de Cidade no formulário')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Configuração de Indicação',
                'verbose_name_plural': 'Configurações de Indicação',
                'db_table': 'indicacoes_indicacaoconfig',
            },
        ),
        migrations.CreateModel(
            name='Indicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_indicado', models.CharField(max_length=255)),
                ('telefone_indicado', models.CharField(max_length=20)),
                ('cpf_indicado', models.CharField(blank=True, max_length=14)),
                ('cidade_indicado', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('contato_feito', 'Contato Feito'), ('convertido', 'Convertido'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20)),
                ('pontos_creditados', models.BooleanField(default=False)),
                ('data_indicacao', models.DateTimeField(auto_now_add=True)),
                ('data_conversao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('membro_indicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicacao_recebida', to='clube.membroclube')),
                ('membro_indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicacoes_feitas', to='clube.membroclube')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Indicação',
                'verbose_name_plural': 'Indicações',
                'db_table': 'indicacoes_indicacao',
                'ordering': ['-data_indicacao'],
                'unique_together': {('membro_indicador', 'telefone_indicado')},
            },
        ),
    ]
