# Generated by Django 5.2.4 on 2026-03-12 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas_web', '0029_alter_configuracaoempresa_nome_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracaoAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Hubsoft Megalink', max_length=200, verbose_name='Nome da Integração')),
                ('tipo', models.CharField(choices=[('hubsoft', 'Hubsoft'), ('outro', 'Outro')], db_index=True, default='hubsoft', max_length=50, verbose_name='Tipo')),
                ('base_url', models.URLField(help_text='Ex: https://api.megalinktelecom.hubsoft.com.br', max_length=500, verbose_name='URL Base da API')),
                ('client_id', models.CharField(max_length=200, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=500, verbose_name='Client Secret')),
                ('username', models.CharField(max_length=200, verbose_name='Usuário')),
                ('password', models.CharField(max_length=200, verbose_name='Senha')),
                ('grant_type', models.CharField(default='password', max_length=50, verbose_name='Grant Type')),
                ('access_token', models.TextField(blank=True, default='', help_text='Preenchido automaticamente ao autenticar', verbose_name='Access Token (cache)')),
                ('token_expira_em', models.DateTimeField(blank=True, null=True, verbose_name='Token Expira Em')),
                ('ativa', models.BooleanField(default=True, help_text='Desmarque para desabilitar esta integração', verbose_name='Ativa')),
                ('configuracoes_extras', models.JSONField(blank=True, default=dict, help_text='JSON com parâmetros adicionais (id_origem_cliente, id_vendedor padrão, etc.)', verbose_name='Configurações Extras')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Integração de API',
                'verbose_name_plural': '🔗 01. Integrações de API',
                'db_table': 'integracoes_api',
                'ordering': ['-ativa', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='LogIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='Ex: /api/v1/integracao/prospecto', max_length=500, verbose_name='Endpoint')),
                ('metodo', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='POST', max_length=10, verbose_name='Método HTTP')),
                ('payload_enviado', models.JSONField(blank=True, default=dict, verbose_name='Payload Enviado')),
                ('resposta_recebida', models.JSONField(blank=True, default=dict, verbose_name='Resposta Recebida')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Status Code HTTP')),
                ('sucesso', models.BooleanField(default=False, verbose_name='Sucesso')),
                ('mensagem_erro', models.TextField(blank=True, default='', verbose_name='Mensagem de Erro')),
                ('tempo_resposta_ms', models.IntegerField(blank=True, null=True, verbose_name='Tempo de Resposta (ms)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('integracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integracoes.integracaoapi', verbose_name='Integração')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_integracao', to='vendas_web.leadprospecto', verbose_name='Lead Relacionado')),
            ],
            options={
                'verbose_name': 'Log de Integração',
                'verbose_name_plural': '📋 02. Logs de Integração',
                'db_table': 'logs_integracao',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['integracao', 'sucesso'], name='logs_integr_integra_d3d746_idx'), models.Index(fields=['lead'], name='logs_integr_lead_id_6eb2cb_idx'), models.Index(fields=['-data_criacao'], name='logs_integr_data_cr_27afbf_idx'), models.Index(fields=['status_code'], name='logs_integr_status__70424f_idx')],
            },
        ),
    ]
