# Generated by Django 5.2.4 on 2026-03-31 17:16

import apps.sistema.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracaoapi',
            name='access_token',
            field=apps.sistema.encrypted_fields.EncryptedTextField(blank=True, default='', help_text='Preenchido automaticamente ao autenticar', verbose_name='Access Token (cache)'),
        ),
        migrations.AlterField(
            model_name='integracaoapi',
            name='client_secret',
            field=apps.sistema.encrypted_fields.EncryptedCharField(max_length=500, verbose_name='Client Secret'),
        ),
        migrations.AlterField(
            model_name='integracaoapi',
            name='password',
            field=apps.sistema.encrypted_fields.EncryptedCharField(max_length=200, verbose_name='Senha'),
        ),
    ]
