# Generated by Django 5.2.4 on 2026-04-06 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0002_alter_integracaoapi_access_token_and_more'),
        ('sistema', '0004_funcionalidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracaoapi',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integracoes', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='integracaoapi',
            name='tipo',
            field=models.CharField(choices=[('hubsoft', 'HubSoft'), ('uazapi', 'Uazapi (WhatsApp)'), ('evolution', 'Evolution API (WhatsApp)'), ('meta_cloud', 'Meta Cloud API (WhatsApp)'), ('twilio_whatsapp', 'Twilio (WhatsApp)'), ('n8n', 'N8N (Automação)'), ('outro', 'Outro')], db_index=True, default='hubsoft', max_length=50, verbose_name='Tipo'),
        ),
    ]
