# Generated by Django 5.2.4 on 2026-04-07 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0003_integracaoapi_tenant_alter_integracaoapi_tipo'),
        ('sistema', '0005_logsistema_acao_logsistema_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientehubsoft',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='logintegracao',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='servicoclientehubsoft',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='integracaoapi',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='integracaoapi',
            name='tipo',
            field=models.CharField(choices=[('hubsoft', 'HubSoft'), ('uazapi', 'Uazapi (WhatsApp)'), ('evolution', 'Evolution API (WhatsApp)'), ('meta_cloud', 'Meta Cloud API (WhatsApp)'), ('twilio_whatsapp', 'Twilio (WhatsApp)'), ('n8n', 'N8N (Automação)'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('groq', 'Groq'), ('google_ai', 'Google AI (Gemini)'), ('outro', 'Outro')], db_index=True, default='hubsoft', max_length=50, verbose_name='Tipo'),
        ),
    ]
