# Generated by Django 5.2.4 on 2026-04-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0004_clientehubsoft_tenant_logintegracao_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracaoapi',
            name='api_token',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Token unico para autenticar chamadas externas. Identifica o tenant automaticamente.', max_length=100, verbose_name='Token de API'),
        ),
    ]
