# Generated by Django 5.2.4 on 2026-04-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0005_integracaoapi_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracaoapi',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='Chave de API do provider (OpenAI, Anthropic, Groq, etc.)', max_length=500, verbose_name='API Key'),
        ),
    ]
