# Generated by Django 5.2.4 on 2026-04-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0006_integracaoapi_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracaoapi',
            name='base_url',
            field=models.URLField(blank=True, default='', help_text='Opcional para OpenAI/Anthropic/Groq (usa URL padrao)', max_length=500, verbose_name='URL Base da API'),
        ),
    ]
