# Generated by Django 5.2.4 on 2026-04-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0007_alter_integracaoapi_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracaoapi',
            name='tipo',
            field=models.CharField(choices=[('hubsoft', 'HubSoft'), ('sgp', 'SGP (inSystem)'), ('uazapi', 'Uazapi (WhatsApp)'), ('evolution', 'Evolution API (WhatsApp)'), ('meta_cloud', 'Meta Cloud API (WhatsApp)'), ('twilio_whatsapp', 'Twilio (WhatsApp)'), ('n8n', 'N8N (Automação)'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('groq', 'Groq'), ('google_ai', 'Google AI (Gemini)'), ('outro', 'Outro')], db_index=True, default='hubsoft', max_length=50, verbose_name='Tipo'),
        ),
    ]
