# Generated by Django 5.2.4 on 2026-04-26 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0008_alter_integracaoapi_tipo'),
        ('leads', '0003_alter_campocustomizado_options_and_more'),
        ('sistema', '0009_perfilusuario_senha_temporaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteSGP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente_sgp', models.IntegerField(db_index=True, help_text='Retornado em new_cliente_id ao cadastrar e em consultas.', verbose_name='ID Cliente no SGP')),
                ('precadastro_id', models.IntegerField(blank=True, help_text='So preenchido quando o cliente veio via cadastrar_prospecto_pf.', null=True, verbose_name='ID Pre-cadastro SGP')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('cpf_cnpj', models.CharField(db_index=True, max_length=20, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone')),
                ('cep', models.CharField(blank=True, default='', max_length=10, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, default='', max_length=255, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, default='', max_length=20, verbose_name='Numero')),
                ('bairro', models.CharField(blank=True, default='', max_length=120, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, default='', max_length=2, verbose_name='UF')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo no SGP')),
                ('contratos', models.JSONField(blank=True, default=list, verbose_name='Contratos')),
                ('dados_completos', models.JSONField(blank=True, default=dict, help_text='JSON cru de POST /api/ura/consultacliente/ — fonte de verdade.', verbose_name='Snapshot da resposta SGP')),
                ('data_sync', models.DateTimeField(auto_now=True, verbose_name='Ultima sync')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('houve_alteracao', models.BooleanField(default=False, verbose_name='Houve alteracao na ultima sync')),
                ('historico_alteracoes', models.JSONField(blank=True, default=list, verbose_name='Historico de alteracoes')),
                ('integracao', models.ForeignKey(help_text='Garante que id_cliente_sgp e unico por integracao, nao globalmente.', on_delete=django.db.models.deletion.CASCADE, related_name='clientes_sgp', to='integracoes.integracaoapi', verbose_name='Integracao SGP de origem')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_sgp', to='leads.leadprospecto', verbose_name='Lead de origem')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Cliente SGP',
                'verbose_name_plural': '👤 05. Clientes SGP',
                'db_table': 'clientes_sgp',
                'ordering': ['-data_sync'],
                'indexes': [models.Index(fields=['cpf_cnpj'], name='clientes_sg_cpf_cnp_489bb4_idx'), models.Index(fields=['lead'], name='clientes_sg_lead_id_da1cd0_idx'), models.Index(fields=['integracao', 'id_cliente_sgp'], name='clientes_sg_integra_5c4bea_idx')],
                'constraints': [models.UniqueConstraint(fields=('integracao', 'id_cliente_sgp'), name='unique_cliente_sgp_por_integracao')],
            },
        ),
    ]
