# Generated by Django 5.2.4 on 2026-05-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0009_clientesgp'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientehubsoft',
            name='churn_atualizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Score atualizado em'),
        ),
        migrations.AddField(
            model_name='clientehubsoft',
            name='churn_score',
            field=models.IntegerField(blank=True, db_index=True, help_text='Quanto maior, maior o risco de cancelamento. Threshold sugerido: 60+', null=True, verbose_name='Score de Churn (0-100)'),
        ),
        migrations.AddField(
            model_name='clientehubsoft',
            name='churn_sinais',
            field=models.JSONField(blank=True, default=dict, help_text="Breakdown dos sinais que compuseram o score. Ex: {'inadimplente': 25, 'tickets_abertos': 30}", verbose_name='Sinais de churn'),
        ),
    ]
