# Generated by Django 5.2.4 on 2026-05-05 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0010_clientehubsoft_churn_atualizado_em_and_more'),
        ('leads', '0003_alter_campocustomizado_options_and_more'),
        ('sistema', '0010_tenant_modulo_workspace_tenant_plano_workspace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteConsolidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('hubsoft', 'HubSoft'), ('sgp', 'SGP / inSystem'), ('voalle', 'Voalle'), ('mk_auth', 'MK-Auth'), ('ixc', 'IXC'), ('manual', 'Cadastro manual no Hubtrix')], db_index=True, max_length=20, verbose_name='Origem')),
                ('id_origem', models.CharField(db_index=True, max_length=100, verbose_name='ID no ERP de origem')),
                ('cpf_cnpj', models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='CPF/CNPJ')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome / Razão Social')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone')),
                ('data_virou_cliente', models.DateTimeField(blank=True, help_text='Quando assinou primeiro contrato', null=True, verbose_name='Data de início do relacionamento')),
                ('meses_como_cliente', models.FloatField(blank=True, null=True, verbose_name='Meses como cliente')),
                ('cliente_ativo', models.BooleanField(db_index=True, default=True, verbose_name='Cliente ativo')),
                ('cliente_suspenso', models.BooleanField(default=False, verbose_name='Cliente suspenso')),
                ('contratos_ativos_qtd', models.IntegerField(default=0, verbose_name='Contratos ativos')),
                ('valor_mensal_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor mensal total (R$)')),
                ('planos_resumo', models.JSONField(blank=True, default=list, help_text='[{nome, valor, velocidade, status}]', verbose_name='Resumo de planos')),
                ('inadimplente', models.BooleanField(db_index=True, default=False, verbose_name='Inadimplente')),
                ('dias_em_atraso', models.IntegerField(blank=True, null=True, verbose_name='Dias em atraso')),
                ('historico_atrasos_qtd', models.IntegerField(default=0, verbose_name='Histórico de atrasos')),
                ('forma_cobranca', models.CharField(blank=True, choices=[('boleto', 'Boleto'), ('pix', 'Pix'), ('cartao', 'Cartão'), ('misto', 'Misto'), ('outro', 'Outro / não informado')], default='', max_length=20, verbose_name='Forma de cobrança predominante')),
                ('tickets_abertos_qtd', models.IntegerField(default=0, verbose_name='Tickets abertos')),
                ('tickets_30d_qtd', models.IntegerField(default=0, verbose_name='Tickets últimos 30d')),
                ('tecnologia', models.CharField(blank=True, choices=[('fibra', 'Fibra óptica'), ('radio', 'Rádio'), ('cabo', 'Cabo metálico'), ('outro', 'Outro')], default='', max_length=20, verbose_name='Tecnologia')),
                ('cto_id_origem', models.CharField(blank=True, default='', max_length=100, verbose_name='CTO/POP ID no ERP')),
                ('uso_banda_pct_queda_60d', models.FloatField(blank=True, help_text='% de queda no uso médio nos últimos 60d vs 60d anteriores', null=True, verbose_name='Queda no uso de banda 60d (%)')),
                ('ultima_conversa_em', models.DateTimeField(blank=True, null=True, verbose_name='Última conversa no Inbox')),
                ('nps_ultimo', models.IntegerField(blank=True, help_text='0-10. Detrator <= 6, neutro 7-8, promotor 9-10.', null=True, verbose_name='Última nota NPS')),
                ('sincronizado_em', models.DateTimeField(auto_now=True, verbose_name='Último sync no Hubtrix')),
                ('sync_origem_em', models.DateTimeField(blank=True, null=True, verbose_name='Quando dado foi puxado do ERP')),
                ('dados_brutos', models.JSONField(blank=True, default=dict, verbose_name='Dados brutos do ERP (debug)')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_consolidados', to='leads.leadprospecto', verbose_name='Lead vinculado')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Cliente Consolidado',
                'verbose_name_plural': '🌐 Clientes Consolidados (multi-ERP)',
                'db_table': 'integracoes_cliente_consolidado',
                'indexes': [models.Index(fields=['cpf_cnpj'], name='integracoes_cpf_cnp_941b80_idx'), models.Index(fields=['inadimplente', '-dias_em_atraso'], name='integracoes_inadimp_dd5741_idx'), models.Index(fields=['cliente_ativo', 'origem'], name='integracoes_cliente_534381_idx'), models.Index(fields=['-sincronizado_em'], name='integracoes_sincron_026d91_idx')],
                'unique_together': {('origem', 'id_origem')},
            },
        ),
    ]
