# Generated by Django 5.2.4 on 2026-05-05 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0011_clienteconsolidado'),
        ('sistema', '0010_tenant_modulo_workspace_tenant_plano_workspace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoChurnScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inadimplencia_ativo', models.BooleanField(default=True, verbose_name='Inadimplência: ativo')),
                ('inadimplencia_peso', models.PositiveSmallIntegerField(default=25, verbose_name='Inadimplência: peso')),
                ('multiplos_tickets_ativo', models.BooleanField(default=True, verbose_name='Múltiplos tickets: ativo')),
                ('multiplos_tickets_peso', models.PositiveSmallIntegerField(default=30, verbose_name='Múltiplos tickets: peso')),
                ('multiplos_tickets_minimo', models.PositiveSmallIntegerField(default=2, help_text='Quantidade mínima de tickets abertos pra acionar este sinal', verbose_name='Múltiplos tickets: qtd mínima')),
                ('ticket_aberto_ativo', models.BooleanField(default=True, verbose_name='Ticket aberto: ativo')),
                ('ticket_aberto_peso', models.PositiveSmallIntegerField(default=10, verbose_name='Ticket aberto: peso')),
                ('sem_atividade_ativo', models.BooleanField(default=True, verbose_name='Sem atividade: ativo')),
                ('sem_atividade_peso', models.PositiveSmallIntegerField(default=20, verbose_name='Sem atividade: peso')),
                ('sem_atividade_dias', models.PositiveSmallIntegerField(default=30, help_text='Sem conversas nos últimos N dias = aciona', verbose_name='Sem atividade: janela em dias')),
                ('cliente_novo_ativo', models.BooleanField(default=True, verbose_name='Cliente novo: ativo')),
                ('cliente_novo_peso', models.PositiveSmallIntegerField(default=10, verbose_name='Cliente novo: peso')),
                ('cliente_novo_meses', models.PositiveSmallIntegerField(default=6, help_text='Cliente com menos de N meses entra na curva da banheira inicial', verbose_name='Cliente novo: corte em meses')),
                ('cliente_longo_ativo', models.BooleanField(default=True, verbose_name='Cliente longo: ativo')),
                ('cliente_longo_peso', models.PositiveSmallIntegerField(default=5, verbose_name='Cliente longo: peso')),
                ('cliente_longo_meses', models.PositiveSmallIntegerField(default=36, help_text='Cliente com mais de N meses na outra ponta da banheira', verbose_name='Cliente longo: corte em meses')),
                ('nps_detrator_ativo', models.BooleanField(default=False, help_text='Ative quando módulo NPS estiver configurado', verbose_name='NPS detrator: ativo')),
                ('nps_detrator_peso', models.PositiveSmallIntegerField(default=25, verbose_name='NPS detrator: peso')),
                ('threshold_atencao', models.PositiveSmallIntegerField(default=40, help_text='Score >= este valor mas < alto_risco classifica como atenção', verbose_name='Threshold atenção')),
                ('threshold_alto_risco', models.PositiveSmallIntegerField(default=60, help_text='Score >= este valor classifica como alto risco. Notifica gerentes.', verbose_name='Threshold alto risco')),
                ('notificar_em_alto_risco', models.BooleanField(default=True, verbose_name='Notificar gerentes ao entrar em alto risco')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Configuração de Churn Score',
                'verbose_name_plural': '⚙️ Config Churn Score (1 por tenant)',
                'db_table': 'integracoes_config_churn_score',
            },
        ),
    ]
