# Generated by Django 5.2.4 on 2026-06-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0012_configuracaochurnscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogWebhookN8N',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('metodo', models.CharField(max_length=10)),
                ('status_code', models.PositiveIntegerField(db_index=True)),
                ('duracao_ms', models.PositiveIntegerField()),
                ('ip_origem', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('body_preview', models.TextField(blank=True, help_text='Primeiros 2000 chars do body')),
                ('criado_em', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'integracoes_log_webhook_n8n',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['endpoint', 'status_code'], name='integracoes_endpoin_1cbf97_idx'), models.Index(fields=['-criado_em', 'status_code'], name='integracoes_criado__3a3215_idx')],
            },
        ),
    ]
