# Generated by Django 5.2.4 on 2026-06-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0013_logwebhookn8n'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicoclientehubsoft',
            name='id_cliente_servico_contrato',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID do contrato gerado via /api/v1/integracao/cliente/contrato/adicionar_contrato. Preenchido pela acao de automacao gerar_contrato_hubsoft.', null=True, verbose_name='ID Contrato HubSoft'),
        ),
    ]
