# Generated by Django 5.2.4 on 2026-06-14 18:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0014_id_cliente_servico_contrato'),
        ('leads', '0006_alter_leadprospecto_cep_alter_leadprospecto_estado_and_more'),
        ('sistema', '0011_alertaconfig_alertasistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServicoTentativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_tentativas_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Agrupa todas as tentativas do mesmo id_atendimento_hubsoft')),
                ('tentativa_numero', models.PositiveSmallIntegerField(default=1)),
                ('id_atendimento_hubsoft', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('id_ordem_servico_hubsoft', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('sucesso', 'Sucesso'), ('falha', 'Falha')], db_index=True, default='pendente', max_length=10)),
                ('motivo_falha_categoria', models.CharField(blank=True, choices=[('tecnico_ocupado', 'Tecnico ocupado'), ('slot_indisponivel', 'Horario indisponivel'), ('data_invalida', 'Data invalida'), ('id_invalido', 'ID de atendimento invalido'), ('outro', 'Outro')], db_index=True, max_length=20)),
                ('motivo_falha_mensagem', models.TextField(blank=True)),
                ('payload_enviado', models.JSONField(blank=True, default=dict)),
                ('resposta_hubsoft', models.JSONField(blank=True, default=dict)),
                ('data_inicio_programado', models.DateField(blank=True, db_index=True, null=True)),
                ('hora_inicio_programado', models.TimeField(blank=True, null=True)),
                ('data_termino_programado', models.DateField(blank=True, null=True)),
                ('hora_termino_programado', models.TimeField(blank=True, null=True)),
                ('id_tecnico', models.IntegerField(blank=True, db_index=True, null=True)),
                ('tecnico_nome', models.CharField(blank=True, max_length=200)),
                ('cidade', models.CharField(blank=True, db_index=True, max_length=120)),
                ('duracao_ms', models.PositiveIntegerField(default=0)),
                ('origem', models.CharField(choices=[('matrix', 'Matrix (automatico)'), ('retry_manual', 'Retry manual')], default='matrix', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cliente_hubsoft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_tentativas', to='integracoes.clientehubsoft')),
                ('integracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='os_tentativas', to='integracoes.integracaoapi')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_tentativas', to='leads.leadprospecto')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_tentativas', to='integracoes.servicoclientehubsoft')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('usuario_retry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_retries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentativa de OS',
                'verbose_name_plural': 'Tentativas de OS',
                'db_table': 'integracoes_ordem_servico_tentativa',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tenant', '-criado_em'], name='os_tent_tenant_data_idx'), models.Index(fields=['tenant', 'status', '-criado_em'], name='os_tent_tenant_status_idx'), models.Index(fields=['tenant', 'id_atendimento_hubsoft'], name='os_tent_atend_idx')],
                'constraints': [models.UniqueConstraint(fields=('grupo_tentativas_id', 'tentativa_numero'), name='uniq_tentativa_por_grupo')],
            },
        ),
    ]
