# Generated by Django 5.2.4 on 2026-06-14 18:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_regrapipelineestagio_total_acoes_efetivas_and_more'),
        ('integracoes', '0015_ordemservicotentativa'),
        ('leads', '0006_alter_leadprospecto_cep_alter_leadprospecto_estado_and_more'),
        ('sistema', '0011_alertaconfig_alertasistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoTentativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_tentativas_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Agrupa todas as tentativas do mesmo lead/oportunidade')),
                ('tentativa_numero', models.PositiveSmallIntegerField(default=1)),
                ('acao', models.CharField(choices=[('gerar', 'Gerar contrato (criar + anexar docs + aceitar)'), ('assinar', 'Assinar contrato (aceitar existente)')], db_index=True, max_length=10)),
                ('etapa', models.CharField(blank=True, choices=[('criar', 'Criar contrato'), ('anexar', 'Anexar documentos'), ('aceitar', 'Aceitar contrato'), ('completo', 'Fluxo completo')], help_text='Em qual subtarefa parou (so faz sentido pra acao=gerar)', max_length=12)),
                ('id_cliente_servico', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('id_cliente_servico_contrato', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('id_modelo_contrato', models.IntegerField(blank=True, null=True)),
                ('id_empresa', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('sucesso', 'Sucesso'), ('falha', 'Falha'), ('pulado_idempotente', 'Pulado (ja feito)')], db_index=True, default='pendente', max_length=20)),
                ('motivo_falha_categoria', models.CharField(blank=True, choices=[('contrato_ja_existe', 'Contrato ja existe'), ('cliente_sem_servico', 'Cliente sem servico'), ('modelo_nao_encontrado', 'Modelo nao encontrado'), ('documento_rejeitado', 'Documento rejeitado'), ('dados_invalidos', 'Dados invalidos'), ('token_expirado', 'Token expirado'), ('cliente_inexistente', 'Cliente inexistente'), ('outro', 'Outro')], db_index=True, max_length=25)),
                ('motivo_falha_mensagem', models.TextField(blank=True)),
                ('payload_enviado', models.JSONField(blank=True, default=dict)),
                ('resposta_hubsoft', models.JSONField(blank=True, default=dict)),
                ('anexos_enviados', models.JSONField(blank=True, default=list, help_text='Lista de {nome, tamanho_bytes, mime} quando etapa=anexar')),
                ('duracao_ms', models.PositiveIntegerField(default=0)),
                ('origem', models.CharField(choices=[('automacao_pipeline', 'Automacao do pipeline'), ('retry_manual', 'Retry manual')], default='automacao_pipeline', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cliente_hubsoft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_tentativas', to='integracoes.clientehubsoft')),
                ('integracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrato_tentativas', to='integracoes.integracaoapi')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_tentativas', to='leads.leadprospecto')),
                ('oportunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_tentativas', to='crm.oportunidadevenda')),
                ('regra_automacao', models.ForeignKey(blank=True, help_text='Regra que disparou (quando origem=automacao_pipeline)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_tentativas', to='crm.regrapipelineestagio')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_tentativas', to='integracoes.servicoclientehubsoft')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('usuario_retry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_retries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentativa de Contrato',
                'verbose_name_plural': 'Tentativas de Contrato',
                'db_table': 'integracoes_contrato_tentativa',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tenant', '-criado_em'], name='contrato_tent_tenant_data_idx'), models.Index(fields=['tenant', 'status', '-criado_em'], name='contrato_tent_status_idx'), models.Index(fields=['tenant', 'acao', '-criado_em'], name='contrato_tent_acao_idx')],
                'constraints': [models.UniqueConstraint(fields=('grupo_tentativas_id', 'tentativa_numero'), name='uniq_contrato_tent_por_grupo')],
            },
        ),
    ]
