# Generated by Django 5.2.4 on 2026-06-17 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0016_contratotentativa'),
        ('sistema', '0012_perfilusuario_login_matrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoHubsoft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_atendimento_hubsoft', models.BigIntegerField(db_index=True, verbose_name='ID Atendimento HubSoft')),
                ('status', models.CharField(db_index=True, default='', max_length=80)),
                ('status_prefixo', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('tipo', models.CharField(blank=True, default='', max_length=120)),
                ('descricao', models.TextField(blank=True, default='')),
                ('data_abertura', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('dados_completos', models.JSONField(blank=True, default=dict)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='integracoes.clientehubsoft')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Atendimento HubSoft',
                'verbose_name_plural': 'Atendimentos HubSoft',
                'db_table': 'integracoes_atendimento_hubsoft',
                'ordering': ['-data_abertura'],
                'indexes': [models.Index(fields=['tenant', 'status', 'data_abertura'], name='integracoes_tenant__9e8e75_idx')],
                'unique_together': {('tenant', 'id_atendimento_hubsoft')},
            },
        ),
        migrations.CreateModel(
            name='FaturaHubsoft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fatura_hubsoft', models.BigIntegerField(db_index=True, verbose_name='ID Fatura HubSoft')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_emissao', models.DateField(blank=True, db_index=True, null=True)),
                ('data_vencimento', models.DateField(db_index=True)),
                ('data_pagamento', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada'), ('outro', 'Outro')], db_index=True, default='aberta', max_length=20)),
                ('forma_pagamento', models.CharField(blank=True, default='', max_length=80)),
                ('linha_digitavel', models.CharField(blank=True, default='', max_length=120)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('dados_completos', models.JSONField(blank=True, default=dict)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='integracoes.clientehubsoft')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Fatura HubSoft',
                'verbose_name_plural': 'Faturas HubSoft',
                'db_table': 'integracoes_fatura_hubsoft',
                'ordering': ['-data_vencimento'],
                'indexes': [models.Index(fields=['tenant', 'status', 'data_vencimento'], name='integracoes_tenant__25bde1_idx'), models.Index(fields=['tenant', 'data_vencimento'], name='integracoes_tenant__3e78b8_idx'), models.Index(fields=['cliente', 'status'], name='integracoes_cliente_b3c71d_idx')],
                'unique_together': {('tenant', 'id_fatura_hubsoft')},
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoHubsoft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_os_hubsoft', models.BigIntegerField(db_index=True, verbose_name='ID OS HubSoft')),
                ('status', models.CharField(db_index=True, default='', max_length=80)),
                ('status_prefixo', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('tipo', models.CharField(blank=True, default='', max_length=120)),
                ('tecnico_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('tecnico_nome', models.CharField(blank=True, default='', max_length=120)),
                ('data_abertura', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('data_agendamento', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, default='')),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('dados_completos', models.JSONField(blank=True, default=dict)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='integracoes.clientehubsoft')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='integracoes.servicoclientehubsoft')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Ordem de Servico HubSoft',
                'verbose_name_plural': 'Ordens de Servico HubSoft',
                'db_table': 'integracoes_ordem_servico_hubsoft',
                'ordering': ['-data_abertura'],
                'indexes': [models.Index(fields=['tenant', 'status', 'data_abertura'], name='integracoes_tenant__1dead8_idx'), models.Index(fields=['tenant', 'tecnico_id'], name='integracoes_tenant__b6da2f_idx')],
                'unique_together': {('tenant', 'id_os_hubsoft')},
            },
        ),
    ]
