# Generated by Django 5.2.4 on 2026-07-22 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0018_alter_integracaoapi_tipo'),
        ('sistema', '0017_tenant_modulo_people_tenant_plano_people_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoCRMHubsoft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('nome_arquivo', models.CharField(blank=True, default='', max_length=255, verbose_name='Arquivo')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total de cards')),
                ('cards', models.JSONField(blank=True, default=list, verbose_name='Cards parseados')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes_crm_hubsoft', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Importacao CRM HubSoft',
                'verbose_name_plural': 'Importacoes CRM HubSoft',
                'db_table': 'integracoes_importacao_crm',
                'ordering': ['-enviado_em'],
                'indexes': [models.Index(fields=['tenant', '-enviado_em'], name='integracoes_tenant__a2dde1_idx')],
            },
        ),
    ]
