# Generated by Django 5.2.4 on 2026-07-24 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0019_importacaocrmhubsoft'),
        ('sistema', '0017_tenant_modulo_people_tenant_plano_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracaoapi',
            name='tipo',
            field=models.CharField(choices=[('hubsoft', 'HubSoft'), ('hubsoft_painel', 'HubSoft Painel (operador)'), ('sgp', 'SGP (inSystem)'), ('uazapi', 'Uazapi (WhatsApp)'), ('evolution', 'Evolution API (WhatsApp)'), ('meta_cloud', 'Meta Cloud API (WhatsApp)'), ('twilio_whatsapp', 'Twilio (WhatsApp)'), ('n8n', 'N8N (Automação)'), ('talk', 'Talk (Matrix do Brasil - PABX)'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('groq', 'Groq'), ('google_ai', 'Google AI (Gemini)'), ('outro', 'Outro')], db_index=True, default='hubsoft', max_length=50, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='PerfilConversaoHubsoft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.SlugField(help_text='Identificador por tenant. Ex: padrao, conversao, upsell.', max_length=60, verbose_name='Nome do perfil')),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('vendedor_id_conversao', models.IntegerField(blank=True, null=True, verbose_name='Vendedor da conversao (id HubSoft)')),
                ('vendedor_id_novo_servico', models.IntegerField(blank=True, null=True, verbose_name='Vendedor do novo servico/upgrade (id HubSoft)')),
                ('grupo_servico_id', models.IntegerField(blank=True, help_text='Ex: Varejo. O objeto completo fica em grupo_servico_obj.', null=True, verbose_name='Grupo do servico (id HubSoft)')),
                ('grupo_servico_obj', models.JSONField(blank=True, default=dict, help_text='Objeto completo do grupo que o painel exige no payload.', verbose_name='Grupo do servico (objeto)')),
                ('status_servico_novo_id', models.IntegerField(default=6, help_text='Padrao 6 = Aguardando Instalacao.', verbose_name='Status do servico novo (id)')),
                ('status_servico_migrado_id', models.IntegerField(default=11, help_text='Padrao 11 = Servico Habilitado (upgrade nasce habilitado).', verbose_name='Status do servico migrado (id)')),
                ('forma_cobranca_id', models.IntegerField(blank=True, null=True, verbose_name='Forma de cobranca (id HubSoft)')),
                ('vencimentos_map', models.JSONField(blank=True, default=dict, help_text='Ex: {"1": 28, "5": 9, "10": 4}. Traduz o dia escolhido no id_vencimento do ERP.', verbose_name='Mapa de vencimentos (dia -> id)')),
                ('id_empresa', models.IntegerField(blank=True, help_text='Usado em contrato/cancelamento.', null=True, verbose_name='Empresa (id HubSoft)')),
                ('motivo_cancelamento_id', models.IntegerField(blank=True, null=True, verbose_name='Motivo de cancelamento (id HubSoft)')),
                ('validade_meses', models.PositiveSmallIntegerField(default=12, verbose_name='Validade do contrato (meses)')),
                ('tipo_cobranca', models.CharField(default='postecipada', max_length=40, verbose_name='Tipo de cobranca')),
                ('agrupamento_fatura', models.CharField(default='agrupado_cliente', max_length=40, verbose_name='Agrupamento de fatura')),
                ('dry_run_forcado', models.BooleanField(default=True, help_text='Enquanto ligado, so os CPFs da allowlist executam de verdade. Todo o resto simula.', verbose_name='Dry run forcado')),
                ('cpf_allowlist', models.JSONField(blank=True, default=list, help_text='Lista de CPFs liberados pra escrita real enquanto o dry run forcado estiver ligado.', verbose_name='Allowlist de CPF (execucao real)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('integracao_api', models.ForeignKey(blank=True, help_text='Usada so pra leitura/espelho (consultar_cliente, sincronizar).', limit_choices_to={'tipo': 'hubsoft'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfis_conversao_api', to='integracoes.integracaoapi', verbose_name='Integracao HubSoft (API oficial)')),
                ('integracao_painel', models.ForeignKey(blank=True, help_text='Credencial do operador do painel, usada pelas escritas (conversao/servico).', limit_choices_to={'tipo': 'hubsoft_painel'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfis_conversao_painel', to='integracoes.integracaoapi', verbose_name='Integracao HubSoft Painel (operador)')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Perfil de conversao HubSoft',
                'verbose_name_plural': '🔁 Perfis de conversao HubSoft',
                'db_table': 'integracoes_perfil_conversao_hubsoft',
                'ordering': ['nome'],
                'unique_together': {('tenant', 'nome')},
            },
        ),
    ]
