# Generated by Django 5.2.4 on 2026-07-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0020_alter_integracaoapi_tipo_perfilconversaohubsoft'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilconversaohubsoft',
            name='template_conversao',
            field=models.JSONField(blank=True, default=dict, help_text='Payload base do POST /api/v1/cliente capturado UMA vez no painel deste HubSoft (objeto completo: servico, contratos, forma_cobranca, empresa). A rotina faz deepcopy e sobrepoe so os campos do lead (identidade, endereco, vencimento, vendedor). Nada de ID magico no codigo: cada tenant captura o seu. Vazio = conversao indisponivel pro perfil.', verbose_name='Template do payload de conversao'),
        ),
    ]
