# Generated by Django 5.2.4 on 2026-07-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0021_perfilconversaohubsoft_template_conversao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilconversaohubsoft',
            name='forma_cobranca_obj',
            field=models.JSONField(blank=True, default=dict, help_text='Objeto completo da forma de cobranca que o painel exige no payload de novo servico/upgrade. Vazio = o no busca pelo id no schema do painel.', verbose_name='Forma de cobranca (objeto)'),
        ),
        migrations.AlterField(
            model_name='perfilconversaohubsoft',
            name='forma_cobranca_id',
            field=models.IntegerField(blank=True, help_text='Ex: BANCO ITAU. O objeto completo fica em forma_cobranca_obj.', null=True, verbose_name='Forma de cobranca (id HubSoft)'),
        ),
    ]
