# Generated by Django 5.2.4 on 2026-04-01 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('icone', models.CharField(default='fa-tag', max_length=50, verbose_name='Ícone FontAwesome')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Categoria de Ticket',
                'verbose_name_plural': 'Categorias de Ticket',
                'db_table': 'suporte_categorias',
                'ordering': ['ordem'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False, verbose_name='Número')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('aguardando_cliente', 'Aguardando Cliente'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='aberto', max_length=20, verbose_name='Status')),
                ('sla_horas', models.PositiveIntegerField(blank=True, null=True, verbose_name='SLA (horas)')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_primeira_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Primeira Resposta')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_atribuidos', to=settings.AUTH_USER_MODEL, verbose_name='Atendente')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='suporte.categoriaticket', verbose_name='Categoria')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_abertos', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('tenant_cliente', models.ForeignKey(blank=True, help_text='Qual provedor abriu este ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_suporte', to='sistema.tenant', verbose_name='Tenant Cliente')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'suporte_tickets',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('interno', models.BooleanField(default=False, help_text='Visível apenas para a equipe de suporte', verbose_name='Comentário Interno')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='suporte.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'db_table': 'suporte_comentarios',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SLAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano_tier', models.CharField(choices=[('starter', 'Starter'), ('start', 'Start'), ('pro', 'Pro')], max_length=10, verbose_name='Plano')),
                ('tempo_primeira_resposta_horas', models.PositiveIntegerField(verbose_name='SLA Primeira Resposta (horas)')),
                ('tempo_resolucao_horas', models.PositiveIntegerField(verbose_name='SLA Resolução (horas)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Configuração de SLA',
                'verbose_name_plural': 'Configurações de SLA',
                'db_table': 'suporte_sla_config',
                'unique_together': {('tenant', 'plano_tier')},
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'prioridade'], name='suporte_tic_status_4c7729_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['atendente', 'status'], name='suporte_tic_atenden_9b5de9_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tenant_cliente'], name='suporte_tic_tenant__e16e06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('tenant', 'numero')},
        ),
    ]
