# Generated by Django 5.2.4 on 2026-04-06 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_funcionalidade_and_more'),
        ('suporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('icone', models.CharField(default='fa-book', max_length=50, verbose_name='Ícone FA')),
                ('cor_hex', models.CharField(default='#3b82f6', max_length=7, verbose_name='Cor')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Categoria (Base de Conhecimento)',
                'verbose_name_plural': 'Categorias (Base de Conhecimento)',
                'db_table': 'suporte_categorias_conhecimento',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ArtigoConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('conteudo', models.TextField(help_text='Suporta Markdown para formatação', verbose_name='Conteúdo')),
                ('resumo', models.CharField(blank=True, help_text='Resumo curto exibido na listagem', max_length=300, verbose_name='Resumo')),
                ('tags', models.CharField(blank=True, help_text='Separadas por vírgula (ex: roteador, instalacao, fibra)', max_length=500, verbose_name='Tags')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('destaque', models.BooleanField(default=False, help_text='Aparece em destaque no topo da base', verbose_name='Destaque')),
                ('visualizacoes', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('util_sim', models.PositiveIntegerField(default=0, verbose_name='Útil: Sim')),
                ('util_nao', models.PositiveIntegerField(default=0, verbose_name='Útil: Não')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos_conhecimento', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos_conhecimento', to='suporte.categoriaconhecimento', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Artigo (Base de Conhecimento)',
                'verbose_name_plural': 'Artigos (Base de Conhecimento)',
                'db_table': 'suporte_artigos_conhecimento',
                'ordering': ['-destaque', '-atualizado_em'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
    ]
