# Generated by Django 5.2.4 on 2026-04-10 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_logsistema_acao_logsistema_categoria_and_more'),
        ('suporte', '0002_categoriaconhecimento_artigoconhecimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('status', 'Mudanca de Status'), ('atribuicao', 'Atribuicao'), ('prioridade', 'Mudanca de Prioridade'), ('categoria', 'Mudanca de Categoria'), ('comentario', 'Comentario'), ('criacao', 'Criacao'), ('sla', 'SLA'), ('escalacao', 'Escalacao')], max_length=20, verbose_name='Tipo')),
                ('campo', models.CharField(blank=True, max_length=50, verbose_name='Campo alterado')),
                ('valor_anterior', models.CharField(blank=True, max_length=200, verbose_name='Valor anterior')),
                ('valor_novo', models.CharField(blank=True, max_length=200, verbose_name='Valor novo')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descricao')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='suporte.ticket', verbose_name='Ticket')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historico do Ticket',
                'verbose_name_plural': 'Historico de Tickets',
                'db_table': 'suporte_historico_ticket',
                'ordering': ['-data'],
            },
        ),
    ]
