# Generated by Django 5.2.4 on 2026-04-10 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0006_alter_horarioatendimento_unique_together_and_more'),
        ('suporte', '0003_historicoticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaticket',
            name='fila_padrao',
            field=models.ForeignKey(blank=True, help_text='Tickets desta categoria serao atribuidos automaticamente a esta fila', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_ticket', to='inbox.filainbox', verbose_name='Fila Padrao'),
        ),
    ]
