# Generated by Django 5.2.4 on 2026-04-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0004_categoriaticket_fila_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='csat_comentario',
            field=models.TextField(blank=True, default='', verbose_name='Comentario CSAT'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='csat_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data CSAT'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='csat_nota',
            field=models.PositiveIntegerField(blank=True, help_text='1 a 5 estrelas', null=True, verbose_name='Nota CSAT'),
        ),
    ]
