# Generated by Django 5.2.4 on 2026-04-12 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0006_alter_horarioatendimento_unique_together_and_more'),
        ('leads', '0003_alter_campocustomizado_options_and_more'),
        ('sistema', '0007_codigorecuperacaosenha_configuracaorecuperacaosenha'),
        ('suporte', '0005_ticket_csat_comentario_ticket_csat_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaSemResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('respondida', 'Respondida'), ('ignorada', 'Ignorada')], default='pendente', max_length=15, verbose_name='Status')),
                ('ocorrencias', models.PositiveIntegerField(default=1, help_text='Quantas vezes essa pergunta (ou similar) foi feita', verbose_name='Ocorrências')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('artigo_criado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas_origem', to='suporte.artigoconhecimento', verbose_name='Artigo Criado')),
                ('conversa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inbox.conversa', verbose_name='Conversa')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas_sem_resposta', to='leads.leadprospecto', verbose_name='Lead')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Pergunta sem Resposta',
                'verbose_name_plural': '❓ Perguntas sem Resposta',
                'db_table': 'suporte_perguntas_sem_resposta',
                'ordering': ['-ocorrencias', '-data_criacao'],
            },
        ),
    ]
