# Generated by Django 5.2.4 on 2026-06-01 00:23

import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_tenant_modulo_workspace_tenant_plano_workspace_and_more'),
        ('suporte', '0007_pgvector_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artigoconhecimento',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True, verbose_name='Embedding'),
        ),
        migrations.AddField(
            model_name='artigoconhecimento',
            name='embedding_atualizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Embedding atualizado em'),
        ),
        migrations.AddIndex(
            model_name='artigoconhecimento',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='artigo_emb_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
