# Generated by Django 5.2.4 on 2026-04-03 23:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0003_alter_tagcrm_nome_alter_tagcrm_unique_together'),
        ('leads', '0001_initial'),
        ('sistema', '0001_initial'),
        ('suporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('widget', 'Chat Widget'), ('email', 'E-mail'), ('interno', 'Interno')], max_length=20, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('configuracao', models.JSONField(blank=True, default=dict, help_text="URLs de webhook, tokens, etc. Ex: {webhook_envio_url: '...'}", verbose_name='Configuração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canais',
                'db_table': 'inbox_canais',
                'unique_together': {('tenant', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='EtiquetaConversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cor_hex', models.CharField(default='#667eea', max_length=7, verbose_name='Cor')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'db_table': 'inbox_etiquetas',
                'unique_together': {('tenant', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False, verbose_name='Número')),
                ('contato_nome', models.CharField(blank=True, max_length=255, verbose_name='Nome do Contato')),
                ('contato_telefone', models.CharField(blank=True, db_index=True, max_length=17, verbose_name='Telefone')),
                ('contato_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('pendente', 'Pendente'), ('resolvida', 'Resolvida'), ('arquivada', 'Arquivada')], default='aberta', max_length=15, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade')),
                ('identificador_externo', models.CharField(blank=True, db_index=True, help_text='Thread ID do WhatsApp ou referência externa', max_length=100, verbose_name='ID Externo')),
                ('ultima_mensagem_em', models.DateTimeField(blank=True, null=True, verbose_name='Última mensagem')),
                ('ultima_mensagem_preview', models.CharField(blank=True, max_length=255, verbose_name='Preview')),
                ('mensagens_nao_lidas', models.PositiveIntegerField(default=0, verbose_name='Não lidas')),
                ('tempo_primeira_resposta_seg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo 1ª resposta (seg)')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('data_arquivamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Arquivamento')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversas', to='inbox.canalinbox', verbose_name='Canal')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas', to='leads.leadprospecto', verbose_name='Lead')),
                ('oportunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas', to='crm.oportunidadevenda', verbose_name='Oportunidade')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas', to='suporte.ticket', verbose_name='Ticket')),
                ('etiquetas', models.ManyToManyField(blank=True, to='inbox.etiquetaconversa', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'db_table': 'inbox_conversas',
                'ordering': ['-ultima_mensagem_em'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente_tipo', models.CharField(choices=[('contato', 'Contato'), ('agente', 'Agente'), ('sistema', 'Sistema'), ('bot', 'Bot')], max_length=10, verbose_name='Tipo do Remetente')),
                ('remetente_nome', models.CharField(blank=True, max_length=255, verbose_name='Nome do Remetente')),
                ('tipo_conteudo', models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem'), ('arquivo', 'Arquivo'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('localizacao', 'Localização'), ('sistema', 'Mensagem de Sistema')], default='texto', max_length=15, verbose_name='Tipo de Conteúdo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('arquivo_url', models.URLField(blank=True, verbose_name='URL do Arquivo')),
                ('arquivo_nome', models.CharField(blank=True, max_length=255, verbose_name='Nome do Arquivo')),
                ('arquivo_tamanho', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Envio')),
                ('data_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('identificador_externo', models.CharField(blank=True, db_index=True, help_text='Message ID do WhatsApp ou referência externa', max_length=100, verbose_name='ID Externo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('erro_envio', models.TextField(blank=True, verbose_name='Erro de Envio')),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='inbox.conversa', verbose_name='Conversa')),
                ('remetente_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Remetente')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'db_table': 'inbox_mensagens',
                'ordering': ['data_envio'],
            },
        ),
        migrations.CreateModel(
            name='NotaInternaConversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_internas', to='inbox.conversa', verbose_name='Conversa')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Nota Interna',
                'verbose_name_plural': 'Notas Internas',
                'db_table': 'inbox_notas_internas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='RespostaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('atalho', models.CharField(blank=True, help_text='Comando rápido, ex: /saudacao', max_length=50, verbose_name='Atalho')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('categoria', models.CharField(blank=True, max_length=50, verbose_name='Categoria')),
                ('uso_count', models.PositiveIntegerField(default=0, verbose_name='Vezes usado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Resposta Rápida',
                'verbose_name_plural': 'Respostas Rápidas',
                'db_table': 'inbox_respostas_rapidas',
                'ordering': ['-uso_count'],
            },
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['status', 'agente'], name='inbox_conve_status_8761fc_idx'),
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['canal', 'status'], name='inbox_conve_canal_i_3d4b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['ultima_mensagem_em'], name='inbox_conve_ultima__7f6860_idx'),
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['contato_telefone'], name='inbox_conve_contato_dfa0c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversa',
            unique_together={('tenant', 'numero')},
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['conversa', 'data_envio'], name='inbox_mensa_convers_f575d5_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['identificador_externo'], name='inbox_mensa_identif_e8a9c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='respostarapida',
            unique_together={('tenant', 'atalho')},
        ),
    ]
