# Generated by Django 5.2.4 on 2026-04-04 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_tagcrm_nome_alter_tagcrm_unique_together'),
        ('inbox', '0001_initial'),
        ('leads', '0001_initial'),
        ('sistema', '0001_initial'),
        ('suporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Transferência',
                'verbose_name_plural': 'Transferências',
                'db_table': 'inbox_historico_transferencia',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='HorarioAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Início')),
                ('hora_fim', models.TimeField(verbose_name='Hora Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Horário de Atendimento',
                'verbose_name_plural': 'Horários de Atendimento',
                'db_table': 'inbox_horario_atendimento',
                'ordering': ['dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='MembroEquipeInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('agente', 'Agente'), ('supervisor', 'Supervisor'), ('gerente', 'Gerente')], default='agente', max_length=20, verbose_name='Cargo')),
                ('adicionado_em', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
            ],
            options={
                'verbose_name': 'Membro de Equipe',
                'verbose_name_plural': 'Membros de Equipe',
                'db_table': 'inbox_membros_equipe',
            },
        ),
        migrations.CreateModel(
            name='PerfilAgenteInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Online'), ('ausente', 'Ausente'), ('offline', 'Offline')], default='offline', max_length=10, verbose_name='Status')),
                ('capacidade_maxima', models.PositiveIntegerField(default=10, help_text='Máximo de conversas abertas simultâneas', verbose_name='Capacidade Máxima')),
                ('ultimo_status_em', models.DateTimeField(auto_now=True, verbose_name='Último status em')),
            ],
            options={
                'verbose_name': 'Perfil de Agente',
                'verbose_name_plural': 'Perfis de Agente',
                'db_table': 'inbox_perfis_agente',
            },
        ),
        migrations.CreateModel(
            name='RegraRoteamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('canal', 'Por Canal'), ('etiqueta', 'Por Etiqueta'), ('horario', 'Por Horário')], max_length=15, verbose_name='Tipo')),
                ('horario_inicio', models.TimeField(blank=True, null=True, verbose_name='Horário início')),
                ('horario_fim', models.TimeField(blank=True, null=True, verbose_name='Horário fim')),
                ('dias_semana', models.CharField(blank=True, help_text='Separados por vírgula: 0=Seg, 1=Ter, ..., 6=Dom. Ex: 0,1,2,3,4', max_length=20, verbose_name='Dias da semana')),
                ('prioridade', models.PositiveIntegerField(default=0, verbose_name='Prioridade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Regra de Roteamento',
                'verbose_name_plural': 'Regras de Roteamento',
                'db_table': 'inbox_regras_roteamento',
                'ordering': ['-prioridade'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_fora_horario', models.TextField(blank=True, default='Nosso horário de atendimento é de segunda a sexta, das 8h às 18h. Responderemos assim que possível.', verbose_name='Mensagem fora do horário')),
                ('distribuicao_padrao', models.CharField(choices=[('round_robin', 'Round Robin'), ('menor_carga', 'Menor Carga'), ('manual', 'Manual')], default='round_robin', max_length=15, verbose_name='Distribuição padrão')),
                ('atribuir_ao_responder', models.BooleanField(default=True, help_text='Auto-atribuir agente quando responde conversa sem agente', verbose_name='Atribuir ao responder')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Configuração do Inbox',
                'verbose_name_plural': 'Configurações do Inbox',
                'db_table': 'inbox_configuracao',
            },
        ),
        migrations.CreateModel(
            name='EquipeInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('cor_hex', models.CharField(default='#667eea', max_length=7, verbose_name='Cor')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_inbox_lideradas', to=settings.AUTH_USER_MODEL, verbose_name='Líder')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
                'db_table': 'inbox_equipes',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='conversa',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas', to='inbox.equipeinbox', verbose_name='Equipe'),
        ),
        migrations.CreateModel(
            name='FilaInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('prioridade', models.PositiveIntegerField(default=0, help_text='Maior = processada primeiro', verbose_name='Prioridade')),
                ('modo_distribuicao', models.CharField(choices=[('round_robin', 'Round Robin'), ('menor_carga', 'Menor Carga'), ('manual', 'Manual')], default='round_robin', max_length=15, verbose_name='Modo de Distribuição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ultimo_agente_id', models.PositiveIntegerField(blank=True, help_text='Último agente atribuído (para round-robin)', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='inbox.equipeinbox', verbose_name='Equipe')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Fila',
                'verbose_name_plural': 'Filas',
                'db_table': 'inbox_filas',
                'ordering': ['-prioridade', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='conversa',
            name='fila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas', to='inbox.filainbox', verbose_name='Fila'),
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['equipe', 'status'], name='inbox_conve_equipe__758c23_idx'),
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['fila', 'status'], name='inbox_conve_fila_id_d8c48a_idx'),
        ),
        migrations.AddField(
            model_name='historicotransferencia',
            name='conversa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='inbox.conversa', verbose_name='Conversa'),
        ),
        migrations.AddField(
            model_name='historicotransferencia',
            name='de_agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='De agente'),
        ),
        migrations.AddField(
            model_name='historicotransferencia',
            name='de_equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inbox.equipeinbox', verbose_name='De equipe'),
        ),
        migrations.AddField(
            model_name='historicotransferencia',
            name='para_agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Para agente'),
        ),
        migrations.AddField(
            model_name='historicotransferencia',
            name='para_equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inbox.equipeinbox', verbose_name='Para equipe'),
        ),
        migrations.AddField(
            model_name='historicotransferencia',
            name='para_fila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inbox.filainbox', verbose_name='Para fila'),
        ),
        migrations.AddField(
            model_name='historicotransferencia',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='historicotransferencia',
            name='transferido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Transferido por'),
        ),
        migrations.AddField(
            model_name='horarioatendimento',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='membroequipeinbox',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='inbox.equipeinbox', verbose_name='Equipe'),
        ),
        migrations.AddField(
            model_name='membroequipeinbox',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='membroequipeinbox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_equipe_inbox', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='perfilagenteinbox',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='perfilagenteinbox',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_inbox', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='regraroteamento',
            name='canal',
            field=models.ForeignKey(blank=True, help_text='Quando tipo = Por Canal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inbox.canalinbox', verbose_name='Canal'),
        ),
        migrations.AddField(
            model_name='regraroteamento',
            name='etiqueta',
            field=models.ForeignKey(blank=True, help_text='Quando tipo = Por Etiqueta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inbox.etiquetaconversa', verbose_name='Etiqueta'),
        ),
        migrations.AddField(
            model_name='regraroteamento',
            name='fila',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='inbox.filainbox', verbose_name='Fila'),
        ),
        migrations.AddField(
            model_name='regraroteamento',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='equipeinbox',
            unique_together={('tenant', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='filainbox',
            unique_together={('tenant', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='horarioatendimento',
            unique_together={('tenant', 'dia_semana')},
        ),
        migrations.AlterUniqueTogether(
            name='membroequipeinbox',
            unique_together={('equipe', 'user')},
        ),
    ]
