# Generated by Django 5.2.4 on 2026-04-04 03:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_historicotransferencia_horarioatendimento_and_more'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('icone', models.CharField(blank=True, default='fa-circle-question', max_length=50, verbose_name='Ícone FontAwesome')),
                ('cor', models.CharField(default='#667eea', max_length=7, verbose_name='Cor')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Categoria FAQ',
                'verbose_name_plural': 'Categorias FAQ',
                'db_table': 'inbox_faq_categorias',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ArtigoFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('visualizacoes', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='inbox.categoriafaq', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Artigo FAQ',
                'verbose_name_plural': 'Artigos FAQ',
                'db_table': 'inbox_faq_artigos',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='WidgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_publico', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Token Público')),
                ('titulo', models.CharField(default='Como podemos ajudar?', max_length=200, verbose_name='Título')),
                ('mensagem_boas_vindas', models.CharField(default='Olá 👋', max_length=500, verbose_name='Mensagem de Boas Vindas')),
                ('cor_primaria', models.CharField(default='#3b82f6', max_length=7, verbose_name='Cor Primária')),
                ('cor_header', models.CharField(default='#1e3a5f', max_length=7, verbose_name='Cor do Header')),
                ('posicao', models.CharField(choices=[('bottom-right', 'Inferior Direito'), ('bottom-left', 'Inferior Esquerdo')], default='bottom-right', max_length=15, verbose_name='Posição')),
                ('mostrar_faq', models.BooleanField(default=True, verbose_name='Mostrar FAQ')),
                ('pedir_dados_antes', models.BooleanField(default=True, help_text='Solicitar nome/email antes de permitir chat', verbose_name='Pedir dados antes')),
                ('campos_obrigatorios', models.JSONField(blank=True, default=list, help_text='Lista de campos: nome, email, telefone', verbose_name='Campos Obrigatórios')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('dominios_permitidos', models.JSONField(blank=True, default=list, help_text='Lista de domínios. Vazio = todos permitidos.', verbose_name='Domínios Permitidos')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Configuração do Widget',
                'verbose_name_plural': 'Configurações do Widget',
                'db_table': 'inbox_widget_config',
            },
        ),
    ]
