# Generated by Django 5.2.4 on 2026-04-06 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_categoriafaq_artigofaq_widgetconfig'),
        ('integracoes', '0002_alter_integracaoapi_access_token_and_more'),
        ('sistema', '0004_funcionalidade_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='canalinbox',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='canalinbox',
            name='identificador_canal',
            field=models.CharField(blank=True, default='', help_text='Número de telefone, ID da instância, etc.', max_length=100, verbose_name='Identificador'),
        ),
        migrations.AddField(
            model_name='canalinbox',
            name='integracao',
            field=models.ForeignKey(blank=True, help_text='Integração de API vinculada a este canal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canais', to='integracoes.integracaoapi', verbose_name='Integração'),
        ),
        migrations.AddField(
            model_name='canalinbox',
            name='provedor',
            field=models.CharField(blank=True, default='', help_text='Slug do provider: uazapi, evolution, meta_cloud, twilio, webhook', max_length=30, verbose_name='Provedor'),
        ),
        migrations.AlterUniqueTogether(
            name='canalinbox',
            unique_together={('tenant', 'tipo', 'identificador_canal')},
        ),
    ]
