# Generated by Django 5.2.4 on 2026-04-08 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0006_alter_nodofluxoatendimento_tipo'),
        ('inbox', '0004_alter_canalinbox_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canalinbox',
            name='fluxo',
            field=models.ForeignKey(blank=True, help_text='Fluxo que será iniciado ao receber mensagem neste canal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canais_inbox', to='atendimento.fluxoatendimento', verbose_name='Fluxo de Atendimento'),
        ),
    ]
