# Generated by Django 5.2.4 on 2026-04-10 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0005_canalinbox_fluxo'),
        ('sistema', '0005_logsistema_acao_logsistema_categoria_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horarioatendimento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='conversa',
            name='modo_atendimento',
            field=models.CharField(choices=[('bot', 'Bot'), ('humano', 'Humano'), ('finalizado_bot', 'Finalizado pelo Bot')], default='humano', help_text='bot = fluxo ativo, humano = transferido para atendente, finalizado_bot = bot encerrou', max_length=20, verbose_name='Modo de Atendimento'),
        ),
        migrations.AddField(
            model_name='filainbox',
            name='mensagem_fora_horario',
            field=models.TextField(blank=True, default='', help_text='Mensagem enviada automaticamente quando fora do horário da fila', verbose_name='Mensagem fora do horário'),
        ),
        migrations.AddField(
            model_name='horarioatendimento',
            name='fila',
            field=models.ForeignKey(blank=True, help_text='Se vazio, aplica como horario global (fallback)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='inbox.filainbox', verbose_name='Fila'),
        ),
        migrations.AlterUniqueTogether(
            name='horarioatendimento',
            unique_together={('tenant', 'fila', 'dia_semana')},
        ),
    ]
