# Generated by Django 5.2.4 on 2026-04-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0006_alter_horarioatendimento_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversa',
            name='modo_atendimento',
            field=models.CharField(choices=[('bot', 'Bot'), ('humano', 'Humano'), ('finalizado_bot', 'Finalizado pelo Bot'), ('assistente', 'Assistente CRM')], default='humano', help_text='bot = fluxo ativo, humano = transferido para atendente, finalizado_bot = bot encerrou', max_length=20, verbose_name='Modo de Atendimento'),
        ),
    ]
