# Generated by Django 5.2.4 on 2026-05-05 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0007_alter_conversa_modo_atendimento'),
        ('sistema', '0010_tenant_modulo_workspace_tenant_plano_workspace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(blank=True, help_text='1 = péssimo, 5 = excelente. Null = ainda não respondeu.', null=True, verbose_name='Nota (1-5)')),
                ('comentario', models.TextField(blank=True, default='', verbose_name='Comentário')),
                ('sentimento', models.CharField(blank=True, choices=[('positivo', 'Positivo'), ('neutro', 'Neutro'), ('negativo', 'Negativo')], default='', help_text='Classificação automática do comentário aberto.', max_length=10, verbose_name='Sentimento (IA)')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Pergunta enviada em')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Cliente respondeu em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='inbox.conversa', verbose_name='Conversa')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Avaliação de Atendimento (CSAT)',
                'verbose_name_plural': 'Avaliações de Atendimento (CSAT)',
                'db_table': 'inbox_avaliacao_atendimento',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['nota'], name='inbox_avali_nota_016046_idx'), models.Index(fields=['sentimento'], name='inbox_avali_sentime_6bb656_idx'), models.Index(fields=['-criado_em'], name='inbox_avali_criado__264bc9_idx')],
            },
        ),
    ]
