# Generated by Django 5.2.4 on 2026-05-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0008_avaliacaoatendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='arquivo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL do Arquivo'),
        ),
    ]
