# Generated by Django 5.2.4 on 2026-05-22 19:28

import apps.inbox.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0009_alter_mensagem_arquivo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='arquivo',
            field=models.FileField(blank=True, help_text='Midia baixada do WhatsApp (servida via view auth-gated).', null=True, storage=apps.inbox.models.PrivateMidiaStorage(), upload_to='%Y/%m/', verbose_name='Arquivo de Mídia'),
        ),
    ]
