# Generated by Django 5.2.4 on 2026-05-29 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0010_mensagem_arquivo'),
        ('sistema', '0010_tenant_modulo_workspace_tenant_plano_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoinbox',
            name='encerramento_auto_ativo',
            field=models.BooleanField(default=False, help_text='Encerra conversas humanas (aberta/pendente) sem resposta há X horas', verbose_name='Encerrar atendimentos inativos automaticamente'),
        ),
        migrations.AddField(
            model_name='configuracaoinbox',
            name='encerramento_auto_aviso_ativo',
            field=models.BooleanField(default=True, verbose_name='Avisar o contato ao encerrar'),
        ),
        migrations.AddField(
            model_name='configuracaoinbox',
            name='encerramento_auto_aviso_texto',
            field=models.TextField(blank=True, default='Encerramos este atendimento por inatividade. Se precisar de algo, é só chamar que a gente continua.', verbose_name='Mensagem de encerramento automático'),
        ),
        migrations.AddField(
            model_name='configuracaoinbox',
            name='encerramento_auto_horas',
            field=models.PositiveIntegerField(default=48, verbose_name='Horas de inatividade para encerrar'),
        ),
        migrations.CreateModel(
            name='MotivoEncerramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('cor_hex', models.CharField(default='#667eea', max_length=7, verbose_name='Cor')),
                ('codigo', models.CharField(blank=True, default='', help_text='Identificador estável para motivos de sistema (vazio para os criados pelo tenant)', max_length=40, verbose_name='Código interno')),
                ('sistema', models.BooleanField(default=False, editable=False, help_text='Motivos de sistema não podem ser apagados pela UI', verbose_name='Motivo de sistema')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Motivo de encerramento',
                'verbose_name_plural': 'Motivos de encerramento',
                'db_table': 'inbox_motivos_encerramento',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('tenant', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='conversa',
            name='motivo_encerramento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas', to='inbox.motivoencerramento', verbose_name='Motivo de encerramento'),
        ),
    ]
