# Generated by Django 5.2.4 on 2026-05-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0012_seed_motivo_auto_inatividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='assumida',
            field=models.BooleanField(default=False, help_text='Agente abriu e aceitou atender explicitamente. Falso = só direcionada, histórico bloqueado.', verbose_name='Assumida'),
        ),
    ]
