# Generated by Django 5.2.4 on 2026-06-01 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_oportunidadevenda_motivo_perda_origem'),
        ('inbox', '0013_add_assumida_conversa'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoinbox',
            name='encerramento_auto_fecha_oportunidade',
            field=models.BooleanField(default=False, help_text='Quando ativo, ao encerrar conversa por inatividade move a oportunidade vinculada pro estágio escolhido (tipicamente Perdida).', verbose_name='Fechar oportunidade junto ao encerrar conversa automaticamente'),
        ),
        migrations.AddField(
            model_name='configuracaoinbox',
            name='encerramento_auto_motivo_perda_ref',
            field=models.ForeignKey(blank=True, help_text='Se o estágio destino for de perda (is_final_perdido), motivo a ser registrado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.motivoperda', verbose_name='Motivo de perda (se estágio destino for Perdida)'),
        ),
        migrations.AddField(
            model_name='configuracaoinbox',
            name='encerramento_auto_oportunidade_estagio',
            field=models.ForeignKey(blank=True, help_text='Pra onde mover a oportunidade vinculada quando a conversa for encerrada por inatividade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.pipelineestagio', verbose_name='Estágio destino da oportunidade'),
        ),
    ]
