# Generated by Django 5.2.4 on 2026-06-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0014_configuracaoinbox_encerramento_auto_fecha_oportunidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='data_assumida',
            field=models.DateTimeField(blank=True, help_text='Timestamp do momento em que o agente assumiu (clicou Assumir OU enviou primeira mensagem)', null=True, verbose_name='Assumida em'),
        ),
        migrations.AddField(
            model_name='conversa',
            name='realocacoes_count',
            field=models.PositiveIntegerField(default=0, help_text='Quantas vezes essa conversa foi realocada automaticamente por inatividade (v3)', verbose_name='Realocacoes automaticas'),
        ),
        migrations.AddField(
            model_name='filainbox',
            name='alerta_admin_inativo_ativo',
            field=models.BooleanField(default=False, help_text='Quando ativo, admin recebe notificacao se atendente assumiu e nao responde a ultima msg do contato em Y min.', verbose_name='Notificar admin quando atendente assumir e nao responder'),
        ),
        migrations.AddField(
            model_name='filainbox',
            name='max_realocacoes',
            field=models.PositiveIntegerField(default=2, help_text='Apos esse limite, conversa vai pra fila sem agente (status=pendente) ate alguem assumir manualmente.', verbose_name='Maximo de realocacoes por conversa'),
        ),
        migrations.AddField(
            model_name='filainbox',
            name='realocar_inativo_ativo',
            field=models.BooleanField(default=False, help_text='Quando ativo, conversa atribuida mas nao assumida em X min e reatribuida pra outro agente online.', verbose_name='Realocar quando atendente nao assume'),
        ),
        migrations.AddField(
            model_name='filainbox',
            name='tempo_max_sem_assumir_min',
            field=models.PositiveIntegerField(default=10, help_text="So aplica se 'Realocar quando atendente nao assume' estiver ativo.", verbose_name='Minutos sem assumir para realocar'),
        ),
        migrations.AddField(
            model_name='filainbox',
            name='tempo_max_sem_responder_min',
            field=models.PositiveIntegerField(default=30, help_text="So aplica se 'Notificar admin' estiver ativo.", verbose_name='Minutos sem responder para alertar admin'),
        ),
        migrations.AddField(
            model_name='historicotransferencia',
            name='tipo',
            field=models.CharField(choices=[('atribuicao_inicial', 'Atribuicao inicial'), ('transferir_manual', 'Transferencia manual'), ('realocar_inativo', 'Realocacao por inatividade'), ('alerta_admin', 'Alerta de inatividade'), ('liberar', 'Conversa liberada')], default='transferir_manual', help_text='Tipo do evento de atribuicao/transferencia', max_length=30, verbose_name='Tipo'),
        ),
    ]
