# Generated by Django 5.2.4 on 2026-06-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0015_conversa_data_assumida_conversa_realocacoes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilagenteinbox',
            name='ultimo_heartbeat',
            field=models.DateTimeField(blank=True, help_text='Timestamp do último ping do navegador do agente. Se ficar antigo (>5min), cron marca offline.', null=True, verbose_name='Último heartbeat'),
        ),
    ]
