# Generated by Django 5.2.4 on 2026-06-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0016_perfilagenteinbox_ultimo_heartbeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversa',
            name='contato_telefone',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Telefone'),
        ),
    ]
