# Generated by Django 5.2.4 on 2026-03-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarteirinhaMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='carteirinhas/fotos/')),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Carteirinha do Membro',
                'verbose_name_plural': 'Carteirinhas dos Membros',
                'db_table': 'carteirinha_carteirinhamembro',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='ModeloCarteirinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome interno do modelo (ex: Cartao Ouro)', max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('tipo_fundo', models.CharField(choices=[('cor', 'Cores / Gradiente'), ('imagem', 'Imagem de Fundo')], default='cor', max_length=10)),
                ('cor_fundo_primaria', models.CharField(default='#000b4a', help_text='Cor primaria do fundo (ou inicio do gradiente)', max_length=7)),
                ('cor_fundo_secundaria', models.CharField(default='#1a2d4a', help_text='Cor secundaria (fim do gradiente). Igual a primaria = cor solida', max_length=7)),
                ('imagem_fundo', models.ImageField(blank=True, help_text='Imagem de fundo (600x380px). Usado quando tipo_fundo = imagem', null=True, upload_to='carteirinhas/modelos/')),
                ('cor_texto', models.CharField(default='#ffffff', help_text='Cor do texto principal', max_length=7)),
                ('cor_texto_secundario', models.CharField(default='#94a3b8', help_text='Cor do texto secundario (labels)', max_length=7)),
                ('cor_destaque', models.CharField(default='#fbbf24', help_text='Cor de destaque (nivel, badges)', max_length=7)),
                ('logo', models.ImageField(blank=True, help_text='Logo exibido no cartao', null=True, upload_to='carteirinhas/logos/')),
                ('texto_marca', models.CharField(default='Clube Megalink', help_text='Texto da marca (usado se nao tiver logo)', max_length=100)),
                ('mostrar_nome', models.BooleanField(default=True)),
                ('mostrar_cpf', models.BooleanField(default=True)),
                ('mostrar_nivel', models.BooleanField(default=True)),
                ('mostrar_data_emissao', models.BooleanField(default=True)),
                ('mostrar_data_validade', models.BooleanField(default=False)),
                ('mostrar_qr_code', models.BooleanField(default=True, help_text='QR Code com link de validacao')),
                ('mostrar_foto', models.BooleanField(default=False, help_text='Exibir foto do membro')),
                ('mostrar_pontos', models.BooleanField(default=False)),
                ('mostrar_cidade', models.BooleanField(default=False)),
                ('texto_rodape', models.CharField(blank=True, default='um clube filiado', help_text='Texto pequeno no rodape', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modelo de Carteirinha',
                'verbose_name_plural': 'Modelos de Carteirinha',
                'db_table': 'carteirinha_modelocarteirinha',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegraAtribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nivel', 'Por Nível'), ('pontuacao_minima', 'Por Pontuação Mínima'), ('cidade', 'Por Cidade'), ('todos', 'Todos os Membros'), ('manual', 'Atribuição Manual')], max_length=20)),
                ('pontuacao_minima', models.IntegerField(default=0, help_text='Usado quando tipo = pontuacao_minima (XP minimo)')),
                ('cidade', models.CharField(blank=True, help_text='Usado quando tipo = cidade', max_length=100)),
                ('prioridade', models.IntegerField(default=0, help_text='Maior prioridade vence quando membro se encaixa em varias regras')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regra de Atribuição',
                'verbose_name_plural': 'Regras de Atribuição',
                'db_table': 'carteirinha_regraatribuicao',
                'ordering': ['-prioridade'],
            },
        ),
    ]
