# Generated by Django 5.2.4 on 2026-03-30 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carteirinha', '0001_initial'),
        ('clube', '0001_initial'),
        ('sistema', '0002_plano_featureplano_tenant_plano_comercial_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteirinhamembro',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteirinhas', to='clube.membroclube'),
        ),
        migrations.AddField(
            model_name='carteirinhamembro',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='modelocarteirinha',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='carteirinhamembro',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissoes', to='carteirinha.modelocarteirinha'),
        ),
        migrations.AddField(
            model_name='regraatribuicao',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='carteirinha.modelocarteirinha'),
        ),
        migrations.AddField(
            model_name='regraatribuicao',
            name='nivel',
            field=models.ForeignKey(blank=True, help_text='Usado quando tipo = nivel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clube.nivelclube'),
        ),
        migrations.AddField(
            model_name='regraatribuicao',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
    ]
