# Generated by Django 5.2.4 on 2026-06-19 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0003_alter_campanhatrafego_codigo_and_more'),
        ('leads', '0008_leadprospecto_atendido_em'),
        ('sistema', '0012_perfilusuario_login_matrix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome para identificar a LP no painel. Nao aparece pro publico.', max_length=200, verbose_name='Nome interno')),
                ('slug', models.SlugField(help_text='Parte final da URL publica: /p/<tenant>/<slug>/', max_length=80, verbose_name='Slug da URL')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicada', 'Publicada'), ('arquivada', 'Arquivada')], db_index=True, default='rascunho', max_length=20, verbose_name='Status')),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Largura max, cor de fundo, fonte. Aplicadas no <body> da LP.', verbose_name='Configuracoes globais')),
                ('blocos_json', models.JSONField(blank=True, default=list, help_text='Array ordenado: [{"tipo": "hero", "props": {...}}, ...]', verbose_name='Blocos da pagina')),
                ('html_compilado', models.TextField(blank=True, default='', help_text='HTML final pre-renderizado pra servir em prod sem hit no template.', verbose_name='HTML compilado (cache)')),
                ('seo_title', models.CharField(blank=True, default='', max_length=200, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, default='', max_length=300, verbose_name='SEO description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='landing_pages/og/', verbose_name='Imagem OpenGraph')),
                ('pixels', models.JSONField(blank=True, default=dict, help_text='{google_analytics: "G-XXX", meta_pixel: "...", tiktok_pixel: "..."}', verbose_name='Pixels (GA4, Meta, etc.)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('campanha_padrao', models.ForeignKey(blank=True, help_text='LP sem UTM atribui essa campanha aos leads.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_pages', to='campanhas.campanhatrafego', verbose_name='Campanha padrao')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_pages_criadas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Landing Page',
                'verbose_name_plural': 'Landing Pages',
                'db_table': 'marketing_landing_page',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='LandingSubmissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_form', models.JSONField(blank=True, default=dict, verbose_name='Dados do form (cru)')),
                ('utm_source', models.CharField(blank=True, default='', max_length=100)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=100)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=200)),
                ('utm_content', models.CharField(blank=True, default='', max_length=200)),
                ('utm_term', models.CharField(blank=True, default='', max_length=200)),
                ('ip_origem', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('referrer', models.TextField(blank=True, default='')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissoes', to='landing_pages.landingpage', verbose_name='Landing page')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_submissoes', to='leads.leadprospecto', verbose_name='Lead criado')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Submissao de Landing Page',
                'verbose_name_plural': 'Submissoes de Landing Page',
                'db_table': 'marketing_landing_submissao',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='landingpage',
            index=models.Index(fields=['tenant', 'status'], name='marketing_l_tenant__7d69dd_idx'),
        ),
        migrations.AddIndex(
            model_name='landingpage',
            index=models.Index(fields=['tenant', 'slug'], name='marketing_l_tenant__36a086_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='landingpage',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='landingsubmissao',
            index=models.Index(fields=['tenant', 'landing', 'enviado_em'], name='marketing_l_tenant__47d8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='landingsubmissao',
            index=models.Index(fields=['tenant', 'enviado_em'], name='marketing_l_tenant__bc7eb5_idx'),
        ),
    ]
