# Generated by Django 5.2.4 on 2026-06-19 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0001_initial'),
        ('sistema', '0012_perfilusuario_login_matrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: "Cadastro completo cliente fibra"', max_length=200, verbose_name='Nome interno')),
                ('descricao', models.CharField(blank=True, default='', max_length=300)),
                ('campos_json', models.JSONField(blank=True, default=list, help_text='Array ordenado: [{"tipo": "text", "name": "nome", "props": {...}}, ...]', verbose_name='Campos do formulario')),
                ('submit_label', models.CharField(default='Enviar', max_length=80, verbose_name='Texto do botao')),
                ('success_msg', models.TextField(blank=True, default='Recebemos seu cadastro! Em breve entraremos em contato.', verbose_name='Mensagem de sucesso')),
                ('success_redirect', models.URLField(blank=True, default='', verbose_name='URL de redirect pos-sucesso (opcional)')),
                ('criar_lead', models.BooleanField(default=True, verbose_name='Criar LeadProspecto no submit')),
                ('bloquear_fora_cobertura', models.BooleanField(default=False, help_text='So tem efeito se o form tem campo viabilidade.', verbose_name='Bloquear submit se viabilidade=fora_cobertura')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Formulario de Landing Page',
                'verbose_name_plural': 'Formularios de Landing Pages',
                'db_table': 'marketing_formulario_landing',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.AddField(
            model_name='landingsubmissao',
            name='formulario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissoes', to='landing_pages.formulariolanding'),
        ),
    ]
