# Generated by Django 5.2.4 on 2026-05-30 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descricao')),
                ('command', models.CharField(help_text='Nome do command sem args. Ex: encerrar_inativos', max_length=100, verbose_name='Management command')),
                ('args', models.CharField(blank=True, default='', help_text='Argumentos do command, separados por espaco. Ex: --tenant tr-carrion --horas 48', max_length=500, verbose_name='Args')),
                ('schedule', models.CharField(help_text='5 campos: minuto hora dia-do-mes mes dia-da-semana. Ex: */15 * * * *', max_length=80, verbose_name='Schedule (cron expression)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('timeout_segundos', models.PositiveIntegerField(default=600, help_text='Mata o processo se passar disso. Default 10min.', verbose_name='Timeout (s)')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Ultima execucao')),
                ('last_status', models.CharField(choices=[('nunca', 'Nunca executou'), ('running', 'Rodando'), ('success', 'Sucesso'), ('erro', 'Erro'), ('timeout', 'Timeout')], default='nunca', max_length=15, verbose_name='Ultimo status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cron Job',
                'verbose_name_plural': 'Cron Jobs',
                'db_table': 'cron_jobs',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ExecucaoCron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Inicio')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('duracao_segundos', models.FloatField(blank=True, null=True, verbose_name='Duracao (s)')),
                ('status', models.CharField(choices=[('running', 'Rodando'), ('success', 'Sucesso'), ('erro', 'Erro'), ('timeout', 'Timeout')], default='running', max_length=15)),
                ('return_code', models.IntegerField(blank=True, null=True, verbose_name='Return code')),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('disparado_por', models.CharField(default='dispatcher', help_text='"dispatcher" (automatico) ou "manual:<username>"', max_length=80, verbose_name='Disparado por')),
                ('cron_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='cron.cronjob', verbose_name='Cron Job')),
            ],
            options={
                'verbose_name': 'Execucao de Cron',
                'verbose_name_plural': 'Execucoes de Cron',
                'db_table': 'cron_execucoes',
                'ordering': ['-inicio'],
                'indexes': [models.Index(fields=['cron_job', '-inicio'], name='cron_execuc_cron_jo_b75556_idx'), models.Index(fields=['status'], name='cron_execuc_status_6d2b04_idx')],
            },
        ),
    ]
