# Generated by Django 5.2.4 on 2026-03-31 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('imagem', models.ImageField(upload_to='banners/')),
                ('link', models.URLField(blank=True, help_text='URL ao clicar no banner (opcional)')),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'roleta_bannerclube',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'db_table': 'roleta_cidade',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LandingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Clube Megalink', max_length=200)),
                ('subtitulo', models.CharField(default='Seu programa de fidelidade', max_length=300)),
                ('whatsapp_numero', models.CharField(blank=True, help_text='Numero com DDD (ex: 5586999999999)', max_length=20)),
                ('whatsapp_mensagem', models.CharField(default='Quero participar do Clube Megalink!', max_length=300)),
                ('texto_como_funciona', models.TextField(blank=True, help_text='Texto da secao Como Funciona (markdown)')),
                ('texto_rodape', models.CharField(blank=True, max_length=300)),
                ('cor_primaria', models.CharField(default='#000b4a', max_length=10)),
                ('cor_secundaria', models.CharField(default='#f59e0b', max_length=10)),
                ('logo', models.ImageField(blank=True, upload_to='landing/')),
                ('ativo', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Configuracao Landing Page',
                'verbose_name_plural': 'Configuracao Landing Page',
                'db_table': 'roleta_landingconfig',
            },
        ),
        migrations.CreateModel(
            name='MembroClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('saldo', models.IntegerField(default=0, help_text='Saldo acumulado de pontos (Giros)')),
                ('xp_total', models.IntegerField(default=0, help_text='Experiência acumulada (Define o Nível)')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('id_cliente_hubsoft', models.IntegerField(blank=True, db_index=True, null=True)),
                ('validado', models.BooleanField(db_index=True, default=False, help_text='Se o membro já validou o OTP')),
                ('codigo_indicacao', models.CharField(blank=True, help_text='Código único para link de indicação', max_length=10, null=True, unique=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Membro do Clube',
                'verbose_name_plural': 'Membros do Clube',
                'db_table': 'roleta_membroclube',
            },
        ),
        migrations.CreateModel(
            name='NivelClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Bronze, Prata, Ouro', max_length=50)),
                ('xp_necessario', models.IntegerField(default=0, help_text='XP mínimo para alcançar este nível')),
                ('ordem', models.IntegerField(default=1, help_text='Ordem de exibição (1 é o mais baixo)')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Nível do Clube',
                'verbose_name_plural': 'Níveis do Clube',
                'db_table': 'roleta_nivelclube',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteRoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('premio', models.CharField(max_length=255)),
                ('canal_origem', models.CharField(default='Online', max_length=100)),
                ('perfil_cliente', models.CharField(default='nao', max_length=10)),
                ('id_cliente_hubsoft', models.IntegerField(blank=True, null=True)),
                ('saldo', models.IntegerField(default=0, help_text='Saldo de pontos do membro')),
                ('status', models.CharField(choices=[('reservado', 'Reservado'), ('ganhou', 'Ganhou'), ('inviavel_tec', 'Inviável Tecnicamente'), ('inviavel_cani', 'Inviável Cani')], db_index=True, default='reservado', max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giros', to='clube.membroclube')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Participante da Roleta',
                'verbose_name_plural': 'Participantes da Roleta',
                'db_table': 'roleta_participanteroleta',
            },
        ),
        migrations.CreateModel(
            name='PremioRoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField(default=0)),
                ('posicoes', models.CharField(default='1', help_text='Posições na roleta (ex: 4,7)', max_length=50)),
                ('probabilidade', models.IntegerField(default=1, help_text='Peso da probabilidade (ex: 1 para raro, 10 para comum)')),
                ('mensagem_vitoria', models.TextField(blank=True, default='Você ganhou um prêmio!', help_text='Mensagem que aparecerá no alerta ao ganhar este prêmio.')),
                ('cidades_permitidas', models.ManyToManyField(blank=True, help_text='Selecione as cidades permitidas. Se deixar vazio, o prêmio valerá para QUALQUER cidade.', related_name='premios', to='clube.cidade')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Prêmio da Roleta',
                'verbose_name_plural': 'Prêmios da Roleta',
                'db_table': 'roleta_premioroleta',
            },
        ),
        migrations.CreateModel(
            name='RegraPontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatilho', models.CharField(help_text='Identificador único (ex: cadastro, indicacao)', max_length=50, unique=True)),
                ('nome_exibicao', models.CharField(help_text='Ex: Bônus de Boas Vindas', max_length=100)),
                ('pontos_saldo', models.IntegerField(default=0, help_text='Quantos Giros/Saldo a pessoa ganha')),
                ('pontos_xp', models.IntegerField(default=0, help_text='Quanto XP a pessoa ganha')),
                ('limite_por_membro', models.IntegerField(default=1, help_text='Quantas vezes um mesmo membro pode ganhar? (0 para iimitado)')),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('visivel_na_roleta', models.BooleanField(default=True, help_text='Se marcado, esta missão aparecerá na lista da roleta para o usuário.')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Regra de Pontuação',
                'verbose_name_plural': 'Regras de Pontuação',
                'db_table': 'roleta_regrapontuacao',
            },
        ),
        migrations.CreateModel(
            name='ExtratoPontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_saldo_ganhos', models.IntegerField(default=0)),
                ('pontos_xp_ganhos', models.IntegerField(default=0)),
                ('descricao_extra', models.CharField(blank=True, help_text='Ex: Indicou CPF 123456789', max_length=255, null=True)),
                ('data_recebimento', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extratos', to='clube.membroclube')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clube.regrapontuacao')),
            ],
            options={
                'verbose_name': 'Extrato de Pontuação',
                'verbose_name_plural': 'Extratos de Pontuação',
                'db_table': 'roleta_extratopontuacao',
            },
        ),
        migrations.CreateModel(
            name='RoletaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_giro', models.IntegerField(default=10, help_text='Pontos necessários para girar a roleta')),
                ('xp_por_giro', models.IntegerField(default=5, help_text='Quantidade de XP ganha a cada giro da roleta')),
                ('nome_clube', models.CharField(default='Clube MegaLink', max_length=100)),
                ('limite_giros_por_membro', models.IntegerField(default=0, help_text='Número máximo de giros permitidos por pessoa. Use 0 para sem limite.')),
                ('periodo_limite', models.CharField(choices=[('total', 'Total (para sempre)'), ('diario', 'Diário (por dia corrido)'), ('semanal', 'Semanal (últimos 7 dias)'), ('mensal', 'Mensal (mês atual)')], default='total', help_text='Janela de tempo usada para contar os giros de cada membro.', max_length=10)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Configuração da Roleta',
                'verbose_name_plural': 'Configurações da Roleta',
                'db_table': 'roleta_roletaconfig',
            },
        ),
        migrations.CreateModel(
            name='RouletteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('frame', 'Frame da Roleta'), ('background', 'Fundo da Página'), ('logo', 'Logo Central'), ('pointer', 'Ponteiro/Seta')], default='frame', max_length=20)),
                ('ordem', models.IntegerField(default=0, help_text='0-12 para frames')),
                ('imagem', models.ImageField(upload_to='roleta/assets/')),
                ('ativo', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Asset da Roleta',
                'verbose_name_plural': 'Assets da Roleta',
                'db_table': 'roleta_rouletteasset',
                'ordering': ['tipo', 'ordem'],
            },
        ),
    ]
