# Generated by Django 5.2.4 on 2026-04-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0001_initial'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regrapontuacao',
            name='gatilho',
            field=models.CharField(help_text='Identificador único (ex: cadastro, indicacao)', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='regrapontuacao',
            unique_together={('tenant', 'gatilho')},
        ),
    ]
