# Generated by Django 5.2.4 on 2026-04-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0002_alter_regrapontuacao_gatilho_and_more'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='membroclube',
            name='codigo_indicacao',
            field=models.CharField(blank=True, help_text='Código único para link de indicação', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='membroclube',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterUniqueTogether(
            name='cidade',
            unique_together={('tenant', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='membroclube',
            unique_together={('tenant', 'cpf')},
        ),
    ]
