"""
Django settings for gerenciador_vendas project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env (.env.production when DJANGO_ENV=production) from dashboard_comercial/
try:
    from dotenv import load_dotenv
    _env_name = os.environ.get('DJANGO_ENV', 'development')
    _env_file = BASE_DIR.parent / ('.env.production' if _env_name == 'production' else '.env')
    load_dotenv(_env_file, override=False)
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-a2by4jf(!)4jho+09#cjnv8v#w)ozj$r(l6gsslmt%v$7_oh&0')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'robovendas.megalinkpiaui.com.br,187.62.153.53,localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vendas_web',
    'integracoes',
    'crm',
    'ia_validador',
    'posvenda_hubsoft',
]

# ── Automação HubSoft (pós-venda) ───────────────────────────────────────────
# Guard de segurança: enquanto True, TODA execução roda em dry-run (webdriver para
# antes do SALVAR; API monta payload sem POST final), exceto CPFs na allowlist.
# O HubSoft é PRODUÇÃO real — manter True até liberação caso a caso.
HUBSOFT_DRY_RUN_FORCADO = os.environ.get('HUBSOFT_DRY_RUN_FORCADO', 'true').lower() == 'true'
HUBSOFT_CPFS_TESTE = [
    c for c in os.environ.get('HUBSOFT_CPFS_TESTE', '').split(',') if c.strip()
]
# Estratégia por processo: primário + fallback.
# novo_servico: API interna validada (dry-run ~13s vs 104s webdriver) → primário.
HUBSOFT_AUTOMACAO = {
    'novo_servico': {'estrategia': 'api_interna', 'fallback': 'webdriver'},
    'upgrade':      {'estrategia': 'api_interna', 'fallback': 'webdriver'},
    'conversao':    {'estrategia': 'api_interna', 'fallback': None},
}
# Vendedor atrelado às vendas/conversões do robô v2 (separa do gestao_leads_bot,
# que converte os do 1618). Nossos prospectos nascem com este vendedor e o worker
# de conversão (hubsoft_poll_conversao) só converte os prospectos deste vendedor.
HUBSOFT_VENDEDOR_CONVERSAO = int(os.environ.get('HUBSOFT_VENDEDOR_CONVERSAO', '1613'))

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'gerenciador_vendas.portal_sso.PortalSSOMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'vendas_web.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Configurações de Segurança
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# Content Security Policy - Permitir Chart.js
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = (
    "'self'",
    "'unsafe-inline'",
    "'unsafe-eval'",
    "https://cdnjs.cloudflare.com",
    "https://code.jquery.com",
    "https://cdn.jsdelivr.net",  # Para Chart.js
)
CSP_STYLE_SRC = (
    "'self'",
    "'unsafe-inline'",
    "https://cdnjs.cloudflare.com",
)
CSP_IMG_SRC = (
    "'self'",
    "data:",
    "https:",
)
CSP_FONT_SRC = (
    "'self'",
    "https://cdnjs.cloudflare.com",
)

ROOT_URLCONF = 'gerenciador_vendas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'vendas_web.context_processors.empresa_context',
                'vendas_web.rbac.permissoes_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'gerenciador_vendas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# DB_ENGINE=sqlite (.env local, fora do git) aponta para uma cópia sqlite de
# robovendas_v2 para dev sem acesso à VPS. Produção não seta essa var, então
# continua em postgresql.
if os.environ.get('DB_ENGINE', '').lower() == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.environ.get('SQLITE_PATH', BASE_DIR / 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'robovendas'),
            'USER': os.environ.get('DB_USER', 'admin'),
            'PASSWORD': os.environ.get('DB_PASSWORD', '***REMOVIDO***'),
            'HOST': os.environ.get('DB_HOST', '187.62.153.52'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'OPTIONS': {
                'options': '-c timezone=America/Sao_Paulo',
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

# Configurações de fuso horário para garantir horário de Brasília
USE_L10N = True

# Força o uso do fuso horário local em todas as operações
os.environ['TZ'] = 'America/Sao_Paulo'

# Configurações adicionais para fuso horário
from django.utils import timezone
timezone.activate('America/Sao_Paulo')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard1/'
LOGOUT_REDIRECT_URL = '/'

# Disable APPEND_SLASH for API endpoints to avoid POST redirect issues
APPEND_SLASH = False

# ============================================================================
# CONFIGURAÇÕES DO SISTEMA DE NOTIFICAÇÕES
# ============================================================================

# N8N Integration
N8N_WEBHOOK_URL = os.environ.get('N8N_WEBHOOK_URL', 'https://n8n.aurora.consulteplus.com/webhook/notifications')
N8N_API_KEY = os.environ.get('N8N_API_KEY', '')

# Notification Settings
NOTIFICATION_MAX_RETRIES = 3
NOTIFICATION_RETRY_DELAYS = [2, 4, 8]  # minutos (exponential backoff)
NOTIFICATION_BATCH_SIZE = 100
NOTIFICATION_CLEANUP_DAYS = 30  # Limpar notificações antigas

# Site URL para links em notificações
SITE_URL = os.environ.get('SITE_URL', 'https://robovendas.megalinkpiaui.com.br')

# Email Templates
EMAIL_TEMPLATES = {
    'lead_novo': {
        'subject': 'Novo Lead Recebido - {{ lead.nome }}',
        'template': 'emails/lead_novo.html'
    },
    'venda_aprovada': {
        'subject': 'Venda Aprovada - {{ venda.valor }}',
        'template': 'emails/venda_aprovada.html'
    },
    'sistema_erro': {
        'subject': 'Erro no Sistema - {{ erro.tipo }}',
        'template': 'emails/sistema_erro.html'
    }
}

# FastAPI IA Validação (validação de imagem no /cadastro web)
# v2 roda na 8091; a v1/produção usava 8090.
IA_VALIDACAO_URL = os.environ.get('IA_VALIDACAO_URL', 'http://127.0.0.1:8091')

# Portal Megalink SSO (TecHub)
# PORTAL_URL = chamada server-to-server (interno, nao passa por Cloudflare)
# PORTAL_URL_PUBLICA = link para o browser (HTTPS publico)
PORTAL_URL = os.environ.get('PORTAL_URL', 'http://127.0.0.1:8100')
PORTAL_URL_PUBLICA = os.environ.get('PORTAL_URL_PUBLICA', 'https://techub.megalinkpiaui.com.br')
PORTAL_SECRET_KEY = os.environ.get('PORTAL_SECRET_KEY', '')

# Clube de Benefícios — webhook conversão de indicação
# Gunicorn 8101 escuta na raiz; FORCE_SCRIPT_NAME=/clube só afeta URLs geradas (browser/nginx).
CLUBE_WEBHOOK_URL = os.environ.get(
    'CLUBE_WEBHOOK_URL',
    'http://127.0.0.1:8101/roleta/api/indicacoes/conversao/',
).rstrip('/') + '/'
CLUBE_WEBHOOK_SECRET = (
    os.environ.get('CLUBE_WEBHOOK_SECRET', '').strip()
    or os.environ.get('COMERCIAL_WEBHOOK_SECRET', '').strip()
)

# Wifeed (portal WiFi) — poller que puxa cadastros e cria leads no pipeline Wifeed.
# Credenciais geradas no painel Wifeed ("Darlan API"). NÃO commitar valores reais —
# defina via variáveis de ambiente (systemd Environment / .env).
WIFEED_ENABLED = os.environ.get('WIFEED_ENABLED', 'false').lower() == 'true'
WIFEED_BASE_URL = os.environ.get('WIFEED_BASE_URL', 'https://api.wifeed.com.br').rstrip('/')
WIFEED_CLIENT_ID = os.environ.get('WIFEED_CLIENT_ID', '').strip()
WIFEED_CLIENT_SECRET = os.environ.get('WIFEED_CLIENT_SECRET', '').strip()
# IDs de local (loja/ponto WiFi) que viram lead. Vazio = todos os locais da conta.
WIFEED_LOCAIS = [
    int(x) for x in os.environ.get('WIFEED_LOCAIS', '').replace(';', ',').split(',')
    if x.strip().isdigit()
]
