# Generated by Django 5.2.4 on 2026-03-31 13:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaTrafego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome descritivo da campanha', max_length=200, verbose_name='Nome da Campanha')),
                ('codigo', models.CharField(help_text='Código identificador único (ex: BF2024, CUPOM50)', max_length=50, unique=True, verbose_name='Código Único')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da campanha', verbose_name='Descrição')),
                ('palavra_chave', models.CharField(help_text='Palavra ou termo que identifica esta campanha', max_length=200, verbose_name='Palavra-chave')),
                ('tipo_match', models.CharField(choices=[('exato', 'Match Exato'), ('parcial', 'Match Parcial'), ('regex', 'Expressão Regular')], default='parcial', help_text='Como a palavra-chave será detectada na mensagem', max_length=20, verbose_name='Tipo de Detecção')),
                ('case_sensitive', models.BooleanField(default=False, help_text='Diferenciar maiúsculas de minúsculas', verbose_name='Case Sensitive')),
                ('plataforma', models.CharField(choices=[('google_ads', 'Google Ads'), ('facebook_ads', 'Facebook Ads'), ('instagram_ads', 'Instagram Ads'), ('tiktok_ads', 'TikTok Ads'), ('linkedin_ads', 'LinkedIn Ads'), ('email', 'Email Marketing'), ('sms', 'SMS Marketing'), ('whatsapp', 'WhatsApp Business'), ('outro', 'Outro')], help_text='Plataforma de origem do tráfego', max_length=50, verbose_name='Plataforma')),
                ('tipo_trafego', models.CharField(blank=True, choices=[('pago', 'Tráfego Pago'), ('organico', 'Tráfego Orgânico'), ('hibrido', 'Híbrido')], max_length=50, verbose_name='Tipo de Tráfego')),
                ('prioridade', models.IntegerField(default=5, help_text='Prioridade para desempate (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Prioridade')),
                ('ativa', models.BooleanField(default=True, help_text='Se a campanha está ativa para detecção', verbose_name='Ativa')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('url_destino', models.URLField(blank=True, help_text='URL da landing page ou destino da campanha', max_length=500, verbose_name='URL de Destino')),
                ('orcamento', models.DecimalField(blank=True, decimal_places=2, help_text='Orçamento total da campanha em R$', max_digits=12, null=True, verbose_name='Orçamento')),
                ('meta_leads', models.IntegerField(blank=True, help_text='Quantidade de leads esperada', null=True, verbose_name='Meta de Leads')),
                ('contador_deteccoes', models.IntegerField(default=0, help_text='Contador automático de detecções', verbose_name='Total de Detecções')),
                ('ultima_deteccao', models.DateTimeField(blank=True, null=True, verbose_name='Última Detecção')),
                ('cor_identificacao', models.CharField(default='#667eea', help_text='Cor hexadecimal para identificação visual', max_length=7, verbose_name='Cor de Identificação')),
                ('ordem_exibicao', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Campanha de Tráfego',
                'verbose_name_plural': '📢 Campanhas de Tráfego',
                'db_table': 'campanha_trafego',
                'ordering': ['-ativa', 'ordem_exibicao', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='DeteccaoCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('mensagem_original', models.TextField(verbose_name='Mensagem Original')),
                ('mensagem_normalizada', models.TextField(blank=True, help_text='Versão normalizada para processamento', verbose_name='Mensagem Normalizada')),
                ('tamanho_mensagem', models.IntegerField(blank=True, null=True, verbose_name='Tamanho da Mensagem')),
                ('trecho_detectado', models.CharField(blank=True, help_text='Parte da mensagem que deu match', max_length=500, verbose_name='Trecho Detectado')),
                ('posicao_inicio', models.IntegerField(blank=True, null=True, verbose_name='Posição Inicial')),
                ('posicao_fim', models.IntegerField(blank=True, null=True, verbose_name='Posição Final')),
                ('metodo_deteccao', models.CharField(blank=True, choices=[('exato', 'Match Exato'), ('parcial', 'Match Parcial'), ('regex', 'Expressão Regular')], max_length=20, verbose_name='Método de Detecção')),
                ('score_confianca', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de confiança (0-100%)', max_digits=5, verbose_name='Score de Confiança')),
                ('eh_primeira_mensagem', models.BooleanField(default=False, help_text='Se é a primeira mensagem do cliente', verbose_name='É Primeira Mensagem')),
                ('origem', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('chat', 'Chat Web'), ('telefone', 'Telefone')], default='whatsapp', max_length=20, verbose_name='Origem')),
                ('timestamp_mensagem', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp da Mensagem')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dados adicionais em formato JSON', verbose_name='Metadata')),
                ('aceita', models.BooleanField(default=True, help_text='Se a detecção foi validada como correta', verbose_name='Detecção Aceita')),
                ('motivo_rejeicao', models.TextField(blank=True, verbose_name='Motivo da Rejeição')),
                ('data_rejeicao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Rejeição')),
                ('processado_n8n', models.BooleanField(default=False, verbose_name='Processado pelo N8N')),
                ('data_processamento_n8n', models.DateTimeField(blank=True, null=True, verbose_name='Data de Processamento N8N')),
                ('resposta_n8n', models.JSONField(blank=True, default=dict, verbose_name='Resposta do N8N')),
                ('converteu_venda', models.BooleanField(default=False, verbose_name='Converteu em Venda')),
                ('data_conversao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conversão')),
                ('valor_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor da Venda')),
                ('detectado_em', models.DateTimeField(auto_now_add=True, verbose_name='Detectado em')),
                ('campanha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deteccoes', to='campanhas.campanhatrafego', verbose_name='Campanha')),
            ],
            options={
                'verbose_name': 'Detecção de Campanha',
                'verbose_name_plural': '📊 Detecções de Campanhas',
                'db_table': 'deteccao_campanha',
                'ordering': ['-detectado_em'],
            },
        ),
    ]
