# Generated by Django 5.2.4 on 2026-03-31 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0001_initial'),
        ('leads', '0001_initial'),
        ('sistema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deteccaocampanha',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deteccoes_campanha', to='leads.leadprospecto', verbose_name='Lead'),
        ),
        migrations.AddField(
            model_name='deteccaocampanha',
            name='rejeitada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deteccoes_rejeitadas', to=settings.AUTH_USER_MODEL, verbose_name='Rejeitada por'),
        ),
        migrations.AddField(
            model_name='deteccaocampanha',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddIndex(
            model_name='campanhatrafego',
            index=models.Index(fields=['codigo'], name='campanha_tr_codigo_62c99b_idx'),
        ),
        migrations.AddIndex(
            model_name='campanhatrafego',
            index=models.Index(fields=['ativa'], name='campanha_tr_ativa_158d75_idx'),
        ),
        migrations.AddIndex(
            model_name='campanhatrafego',
            index=models.Index(fields=['palavra_chave'], name='campanha_tr_palavra_832227_idx'),
        ),
        migrations.AddIndex(
            model_name='campanhatrafego',
            index=models.Index(fields=['plataforma'], name='campanha_tr_platafo_2ac82a_idx'),
        ),
        migrations.AddIndex(
            model_name='deteccaocampanha',
            index=models.Index(fields=['telefone'], name='deteccao_ca_telefon_409219_idx'),
        ),
        migrations.AddIndex(
            model_name='deteccaocampanha',
            index=models.Index(fields=['lead'], name='deteccao_ca_lead_id_2b5b54_idx'),
        ),
        migrations.AddIndex(
            model_name='deteccaocampanha',
            index=models.Index(fields=['campanha'], name='deteccao_ca_campanh_9ef1cf_idx'),
        ),
        migrations.AddIndex(
            model_name='deteccaocampanha',
            index=models.Index(fields=['-detectado_em'], name='deteccao_ca_detecta_11808e_idx'),
        ),
        migrations.AddIndex(
            model_name='deteccaocampanha',
            index=models.Index(fields=['aceita'], name='deteccao_ca_aceita_a6714e_idx'),
        ),
        migrations.AddIndex(
            model_name='deteccaocampanha',
            index=models.Index(fields=['converteu_venda'], name='deteccao_ca_convert_bf3ebc_idx'),
        ),
    ]
