# Generated by Django 5.2.4 on 2026-04-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0002_initial'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanhatrafego',
            name='codigo',
            field=models.CharField(help_text='Código identificador único (ex: BF2024, CUPOM50)', max_length=50, verbose_name='Código Único'),
        ),
        migrations.AlterUniqueTogether(
            name='campanhatrafego',
            unique_together={('tenant', 'codigo')},
        ),
    ]
