# Generated by Django 5.2.4 on 2026-06-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0003_alter_campanhatrafego_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanhatrafego',
            name='meio',
            field=models.CharField(blank=True, choices=[('ads', 'Tráfego Pago (ads)'), ('social', 'Social Orgânico'), ('search', 'Busca'), ('referral', 'Indicação'), ('email', 'Email'), ('direct', 'Direto')], db_index=True, help_text='Categoria de trafego (ads pago / social organico / busca / indicacao / email / direto)', max_length=20, null=True, verbose_name='Meio (UTM medium)'),
        ),
    ]
