# Generated by Django 5.2.4 on 2026-03-30 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clube', '0001_initial'),
        ('sistema', '0002_plano_featureplano_tenant_plano_comercial_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaParceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icone', models.CharField(default='fas fa-tag', help_text='Classe FontAwesome', max_length=50)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Categoria de Parceiro',
                'verbose_name_plural': 'Categorias de Parceiros',
                'db_table': 'parceiros_categoriaparceiro',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='parceiros/logos/')),
                ('descricao', models.TextField(blank=True)),
                ('contato_nome', models.CharField(blank=True, max_length=255)),
                ('contato_telefone', models.CharField(blank=True, max_length=20)),
                ('contato_email', models.EmailField(blank=True, max_length=254)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parceiros', to='parceiros.categoriaparceiro')),
                ('cidades', models.ManyToManyField(blank=True, related_name='parceiros', to='clube.cidade')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('usuario', models.OneToOneField(blank=True, help_text='Usuário Django vinculado para acesso ao painel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parceiro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
                'db_table': 'parceiros_parceiro',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CupomDesconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: 20% off no Restaurante X', max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cupons/')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo_desconto', models.CharField(choices=[('percentual', 'Percentual (%)'), ('fixo', 'Valor Fixo (R$)')], max_length=15)),
                ('valor_desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modalidade', models.CharField(choices=[('gratuito', 'Gratuito'), ('pontos', 'Custo em Pontos'), ('nivel', 'Bônus de Nível')], default='gratuito', max_length=15)),
                ('custo_pontos', models.IntegerField(default=0, help_text='Usado quando modalidade = Pontos')),
                ('quantidade_total', models.IntegerField(default=0, help_text='0 = ilimitado')),
                ('quantidade_resgatada', models.IntegerField(default=0)),
                ('limite_por_membro', models.IntegerField(default=1)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(db_index=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('status_aprovacao', models.CharField(choices=[('aprovado', 'Aprovado'), ('pendente', 'Aguardando Aprovação'), ('rejeitado', 'Rejeitado')], db_index=True, default='aprovado', help_text='Cupons solicitados por parceiros ficam pendentes até aprovação', max_length=15)),
                ('motivo_rejeicao', models.TextField(blank=True, help_text='Motivo da rejeição (preenchido pelo admin)')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cidades_permitidas', models.ManyToManyField(blank=True, related_name='cupons', to='clube.cidade')),
                ('nivel_minimo', models.ForeignKey(blank=True, help_text='Usado quando modalidade = Nível', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clube.nivelclube')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupons', to='parceiros.parceiro')),
            ],
            options={
                'verbose_name': 'Cupom de Desconto',
                'verbose_name_plural': 'Cupons de Desconto',
                'db_table': 'parceiros_cupomdesconto',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='ResgateCupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(max_length=20, unique=True)),
                ('pontos_gastos', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('resgatado', 'Resgatado'), ('utilizado', 'Utilizado'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], db_index=True, default='resgatado', max_length=20)),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, help_text='Valor total da compra no estabelecimento', max_digits=10, null=True)),
                ('data_resgate', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data_utilizacao', models.DateTimeField(blank=True, null=True)),
                ('cupom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resgates', to='parceiros.cupomdesconto')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resgates_cupom', to='clube.membroclube')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Resgate de Cupom',
                'verbose_name_plural': 'Resgates de Cupom',
                'db_table': 'parceiros_resgatecupom',
                'ordering': ['-data_resgate'],
            },
        ),
    ]
