# Generated by Django 5.2.4 on 2026-04-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0001_initial'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaparceiro',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='cupomdesconto',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resgatecupom',
            name='codigo_unico',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='categoriaparceiro',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='cupomdesconto',
            unique_together={('tenant', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='resgatecupom',
            unique_together={('tenant', 'codigo_unico')},
        ),
    ]
