# Generated by Django 5.2.4 on 2026-03-31 13:51

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('webhook', 'Webhook')], max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('configuracao', models.JSONField(default=dict, help_text='Configurações específicas do canal', verbose_name='Configuração')),
                ('icone', models.CharField(default='fas fa-envelope', help_text='Classe do ícone FontAwesome', max_length=50, verbose_name='Ícone')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Canal de Notificação',
                'verbose_name_plural': '📱 02. Canais de Notificação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('lead_novo', 'Novo Lead'), ('lead_convertido', 'Lead Convertido'), ('venda_aprovada', 'Venda Aprovada'), ('venda_rejeitada', 'Venda Rejeitada'), ('prospecto_aguardando', 'Prospecto Aguardando Validação')], max_length=50, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('template_padrao', models.TextField(help_text='Template padrão da mensagem', verbose_name='Template Padrão')),
                ('prioridade_padrao', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridade Padrão')),
                ('whatsapp_config', models.JSONField(blank=True, default=dict, help_text='Configurações específicas para o canal WhatsApp', verbose_name='Configuração WhatsApp')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Tipo de Notificação',
                'verbose_name_plural': '📢 01. Tipos de Notificação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TemplateNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Template')),
                ('assunto', models.CharField(help_text='Assunto para email', max_length=200, verbose_name='Assunto')),
                ('corpo_html', models.TextField(help_text='Template HTML', verbose_name='Corpo HTML')),
                ('corpo_texto', models.TextField(help_text='Template texto simples', verbose_name='Corpo Texto')),
                ('variaveis', models.JSONField(default=list, help_text='Lista de variáveis disponíveis', verbose_name='Variáveis')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacoes.canalnotificacao')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('tipo_notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacoes.tiponotificacao')),
            ],
            options={
                'verbose_name': 'Template de Notificação',
                'verbose_name_plural': '📝 05. Templates de Notificação',
                'ordering': ['tipo_notificacao__nome', 'canal__nome'],
                'unique_together': {('tipo_notificacao', 'canal')},
            },
        ),
        migrations.CreateModel(
            name='PreferenciaNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('horario_inicio', models.TimeField(default=datetime.time(8, 0), help_text='Horário início para receber notificações', verbose_name='Horário Início')),
                ('horario_fim', models.TimeField(default=datetime.time(18, 0), help_text='Horário fim para receber notificações', verbose_name='Horário Fim')),
                ('dias_semana', models.JSONField(default=list, help_text='Dias da semana [0=segunda, 6=domingo]', verbose_name='Dias da Semana')),
                ('canal_preferido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacoes.canalnotificacao')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacao', to=settings.AUTH_USER_MODEL)),
                ('tipo_notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacoes.tiponotificacao')),
            ],
            options={
                'verbose_name': 'Preferência de Notificação',
                'verbose_name_plural': '⚙️ 03. Preferências de Notificação',
                'ordering': ['usuario__username', 'tipo_notificacao__nome'],
                'unique_together': {('usuario', 'tipo_notificacao', 'canal_preferido')},
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('destinatario_telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('dados_contexto', models.JSONField(default=dict, help_text='Dados para personalização', verbose_name='Dados de Contexto')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviando', 'Enviando'), ('enviada', 'Enviada'), ('falhou', 'Falhou'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('max_tentativas', models.PositiveIntegerField(default=3)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_agendamento', models.DateTimeField(blank=True, help_text='Para envio agendado', null=True)),
                ('n8n_webhook_id', models.CharField(blank=True, max_length=100, null=True)),
                ('n8n_execution_id', models.CharField(blank=True, max_length=100, null=True)),
                ('n8n_response', models.JSONField(blank=True, null=True)),
                ('erro_detalhes', models.TextField(blank=True, null=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacoes.canalnotificacao')),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacoes.tiponotificacao')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': '📨 04. Notificações',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['status'], name='notificacoe_status_3cf862_idx'), models.Index(fields=['data_criacao'], name='notificacoe_data_cr_1961f5_idx'), models.Index(fields=['tipo'], name='notificacoe_tipo_id_1dc7b9_idx'), models.Index(fields=['canal'], name='notificacoe_canal_i_20f27e_idx')],
            },
        ),
    ]
