# Generated by Django 5.2.4 on 2026-04-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canalnotificacao',
            name='codigo',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('webhook', 'Webhook')], max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tiponotificacao',
            name='codigo',
            field=models.CharField(choices=[('lead_novo', 'Novo Lead'), ('lead_convertido', 'Lead Convertido'), ('venda_aprovada', 'Venda Aprovada'), ('venda_rejeitada', 'Venda Rejeitada'), ('prospecto_aguardando', 'Prospecto Aguardando Validação')], max_length=50, verbose_name='Código'),
        ),
        migrations.AlterUniqueTogether(
            name='canalnotificacao',
            unique_together={('tenant', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='tiponotificacao',
            unique_together={('tenant', 'codigo')},
        ),
    ]
