# Generated by Django 5.2.4 on 2026-04-11 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_alter_canalnotificacao_codigo_and_more'),
        ('sistema', '0007_codigorecuperacaosenha_configuracaorecuperacaosenha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='n8n_execution_id',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='n8n_response',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='n8n_webhook_id',
        ),
        migrations.AddField(
            model_name='notificacao',
            name='data_lida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='lida',
            field=models.BooleanField(default=False, verbose_name='Lida'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='resposta_externa',
            field=models.JSONField(blank=True, help_text='Resposta da integração (N8N, webhook, etc.)', null=True, verbose_name='Resposta Externa'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='url_acao',
            field=models.CharField(blank=True, default='', help_text='Link ao clicar na notificação (ex: /comercial/leads/123/)', max_length=500, verbose_name='URL de Ação'),
        ),
        migrations.AddField(
            model_name='tiponotificacao',
            name='icone',
            field=models.CharField(default='fas fa-bell', help_text='Classe FontAwesome (ex: fas fa-bell)', max_length=50, verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='canalnotificacao',
            name='codigo',
            field=models.CharField(choices=[('sistema', 'Sistema (in-app)'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('webhook', 'Webhook')], max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tiponotificacao',
            name='codigo',
            field=models.CharField(choices=[('lead_novo', 'Novo Lead'), ('lead_convertido', 'Lead Convertido'), ('venda_aprovada', 'Venda Aprovada'), ('venda_rejeitada', 'Venda Rejeitada'), ('prospecto_aguardando', 'Prospecto Aguardando Validação'), ('conversa_recebida', 'Nova Conversa Recebida'), ('conversa_transferida', 'Conversa Transferida'), ('mensagem_recebida', 'Nova Mensagem'), ('tarefa_vencendo', 'Tarefa Próxima do Vencimento'), ('tarefa_atribuida', 'Tarefa Atribuída'), ('oportunidade_movida', 'Oportunidade Mudou de Estágio'), ('ticket_criado', 'Novo Ticket'), ('ticket_respondido', 'Ticket Respondido'), ('sla_estourando', 'SLA Próximo do Limite'), ('mencao_nota', 'Menção em Nota'), ('sistema_geral', 'Notificação do Sistema')], max_length=50, verbose_name='Código'),
        ),
        migrations.AlterUniqueTogether(
            name='preferencianotificacao',
            unique_together={('tenant', 'usuario', 'tipo_notificacao', 'canal_preferido')},
        ),
        migrations.AlterUniqueTogether(
            name='templatenotificacao',
            unique_together={('tenant', 'tipo_notificacao', 'canal')},
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['destinatario', 'lida'], name='notificacoe_destina_87c32f_idx'),
        ),
    ]
