# Generated by Django 5.2.4 on 2026-04-26 17:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0003_remove_notificacao_n8n_execution_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoLeituraBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_leitura', models.DateTimeField(default=django.utils.timezone.now)),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_broadcast', to='notificacoes.notificacao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_notif_broadcast', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leitura de notificacao broadcast',
                'verbose_name_plural': 'Leituras de notificacao broadcast',
                'indexes': [models.Index(fields=['user', 'notificacao'], name='notificacoe_user_id_4bbbdd_idx')],
                'constraints': [models.UniqueConstraint(fields=('notificacao', 'user'), name='unique_leitura_broadcast_por_user')],
            },
        ),
    ]
