# Generated by Django 5.2.4 on 2026-07-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0005_seed_inatividade_atendente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiponotificacao',
            name='codigo',
            field=models.CharField(choices=[('lead_novo', 'Novo Lead'), ('lead_convertido', 'Lead Convertido'), ('venda_aprovada', 'Venda Aprovada'), ('venda_rejeitada', 'Venda Rejeitada'), ('prospecto_aguardando', 'Prospecto Aguardando Validação'), ('conversa_recebida', 'Nova Conversa Recebida'), ('conversa_transferida', 'Conversa Transferida'), ('mensagem_recebida', 'Nova Mensagem'), ('inatividade_atendente', 'Atendente Sem Resposta'), ('tarefa_vencendo', 'Tarefa Próxima do Vencimento'), ('tarefa_atribuida', 'Tarefa Atribuída'), ('oportunidade_movida', 'Oportunidade Mudou de Estágio'), ('resumo_diario_comercial', 'Resumo Diário Comercial'), ('ticket_criado', 'Novo Ticket'), ('ticket_respondido', 'Ticket Respondido'), ('sla_estourando', 'SLA Próximo do Limite'), ('mencao_nota', 'Menção em Nota'), ('sistema_geral', 'Notificação do Sistema')], max_length=50, verbose_name='Código'),
        ),
    ]
