# Generated by Django 5.2.4 on 2026-03-31 13:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0001_initial'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadProspecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razaosocial', models.CharField(help_text='Nome completo ou razão social do cliente', max_length=255, verbose_name='Nome/Razão Social')),
                ('email', models.EmailField(blank=True, help_text='Email válido do cliente', max_length=255, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('telefone', models.CharField(help_text='Telefone de contato', max_length=17, validators=[django.core.validators.RegexValidator(message="Telefone deve estar no formato: '+999999999'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Valor em reais associado ao lead', max_digits=12, null=True, verbose_name='Valor')),
                ('empresa', models.CharField(blank=True, help_text='Nome da empresa do cliente', max_length=255, null=True, verbose_name='Empresa')),
                ('origem', models.CharField(choices=[('site', 'Site'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google Ads'), ('whatsapp', 'WhatsApp'), ('indicacao', 'Indicação'), ('telefone', 'Telefone'), ('email', 'Email'), ('outros', 'Outros')], default='site', help_text='Canal de origem do lead', max_length=50, verbose_name='Origem')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora do cadastro', verbose_name='Data de Cadastro')),
                ('status_api', models.CharField(default='pendente', help_text='Status do processamento na API', max_length=20, verbose_name='Status API')),
                ('id_hubsoft', models.CharField(blank=True, db_index=True, help_text='Identificador do lead no Hubsoft para relacionar automaticamente com prospectos', max_length=100, null=True, verbose_name='ID Hubsoft')),
                ('id_origem', models.CharField(blank=True, db_index=True, help_text='Identificador único do lead no sistema de origem (Facebook Ads, Google Ads, etc)', max_length=100, null=True, verbose_name='ID Origem')),
                ('id_origem_servico', models.CharField(blank=True, db_index=True, help_text='Identificador do serviço específico de origem do lead', max_length=100, null=True, verbose_name='ID Origem Serviço')),
                ('cpf_cnpj', models.CharField(blank=True, help_text='CPF ou CNPJ do cliente', max_length=18, null=True, verbose_name='CPF/CNPJ')),
                ('rg', models.CharField(blank=True, help_text='Número do RG do cliente', max_length=30, null=True, verbose_name='RG')),
                ('endereco', models.TextField(blank=True, help_text='Endereço completo do cliente', null=True, verbose_name='Endereço')),
                ('rua', models.CharField(blank=True, help_text='Logradouro do endereço', max_length=255, null=True, verbose_name='Rua')),
                ('numero_residencia', models.CharField(blank=True, help_text='Número do endereço', max_length=20, null=True, verbose_name='Número da Residência')),
                ('bairro', models.CharField(blank=True, help_text='Bairro do endereço', max_length=120, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, help_text='UF do estado', max_length=2, null=True, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('ponto_referencia', models.CharField(blank=True, help_text='Ponto de referência para facilitar a localização', max_length=255, null=True, verbose_name='Ponto de Referência')),
                ('id_plano_rp', models.IntegerField(blank=True, help_text='Identificador do plano no sistema RP', null=True, verbose_name='ID Plano (RP)')),
                ('id_dia_vencimento', models.IntegerField(blank=True, help_text='Identificador do dia de vencimento no RP', null=True, verbose_name='ID Dia de Vencimento')),
                ('id_vendedor_rp', models.IntegerField(blank=True, help_text='Identificador do vendedor no sistema RP', null=True, verbose_name='ID Vendedor (RP)')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre o lead', null=True, verbose_name='Observações')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('canal_entrada', models.CharField(blank=True, choices=[('site', 'Site'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google Ads'), ('whatsapp', 'WhatsApp'), ('indicacao', 'Indicação'), ('telefone', 'Telefone'), ('email', 'Email'), ('outros', 'Outros')], help_text='Canal por onde o lead entrou no sistema', max_length=50, null=True, verbose_name='Canal de Entrada')),
                ('tipo_entrada', models.CharField(blank=True, choices=[('contato_whatsapp', 'Contato WhatsApp'), ('cadastro_site', 'Cadastro Site'), ('telefone', 'Telefone'), ('formulario', 'Formulário'), ('importacao', 'Importação'), ('api_externa', 'API Externa')], help_text='Tipo específico de entrada no sistema', max_length=50, null=True, verbose_name='Tipo de Entrada')),
                ('total_campanhas_detectadas', models.IntegerField(default=0, help_text='Contador de quantas campanhas foram detectadas para este lead', verbose_name='Total de Campanhas Detectadas')),
                ('metadata_campanhas', models.JSONField(blank=True, default=dict, help_text='Dados adicionais sobre campanhas detectadas', verbose_name='Metadata de Campanhas')),
                ('score_qualificacao', models.IntegerField(blank=True, help_text='Score de 1 a 10 baseado na qualificação do lead', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Score de Qualificação')),
                ('tentativas_contato', models.PositiveIntegerField(default=0, help_text='Número de tentativas de contato realizadas', verbose_name='Tentativas de Contato')),
                ('data_ultimo_contato', models.DateTimeField(blank=True, null=True, verbose_name='Data do Último Contato')),
                ('motivo_rejeicao', models.TextField(blank=True, help_text='Motivo detalhado caso tenha sido rejeitado', null=True, verbose_name='Motivo da Rejeição')),
                ('custo_aquisicao', models.DecimalField(blank=True, decimal_places=2, help_text='Custo investido para adquirir este lead', max_digits=10, null=True, verbose_name='Custo de Aquisição')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o lead está ativo', verbose_name='Ativo')),
                ('documentacao_completa', models.BooleanField(default=False, help_text='Indica se toda documentação foi enviada', verbose_name='Documentação Completa')),
                ('documentacao_validada', models.BooleanField(default=False, help_text='Indica se a documentação foi validada', verbose_name='Documentação Validada')),
                ('data_documentacao_completa', models.DateTimeField(blank=True, null=True, verbose_name='Data Documentação Completa')),
                ('data_documentacao_validada', models.DateTimeField(blank=True, null=True, verbose_name='Data Documentação Validada')),
                ('contrato_aceito', models.BooleanField(default=False, help_text='Indica se o contrato foi aceito', verbose_name='Contrato Aceito')),
                ('data_aceite_contrato', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aceite do Contrato')),
                ('ip_aceite_contrato', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Aceite do Contrato')),
                ('url_pdf_conversa', models.URLField(blank=True, help_text='Link do PDF da conversa gerado após validação dos documentos', max_length=1024, null=True, verbose_name='URL PDF da Conversa')),
                ('data_geracao_pdf', models.DateTimeField(blank=True, null=True, verbose_name='Data de Geração do PDF')),
                ('html_conversa_path', models.CharField(blank=True, help_text='Caminho relativo do arquivo HTML gerado do atendimento', max_length=500, null=True, verbose_name='Caminho HTML da Conversa')),
                ('data_geracao_html', models.DateTimeField(blank=True, null=True, verbose_name='Data de Geração do HTML')),
                ('anexos_contrato_enviados', models.BooleanField(default=False, help_text='Indica se os documentos e o HTML do atendimento foram anexados ao contrato no HubSoft', verbose_name='Anexos do Contrato Enviados')),
                ('campanha_conversao', models.ForeignKey(blank=True, help_text='Campanha ativa quando o lead converteu em cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_convertidos', to='campanhas.campanhatrafego', verbose_name='Campanha de Conversão')),
                ('campanha_origem', models.ForeignKey(blank=True, help_text='Campanha pela qual o lead entrou pela primeira vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_origem', to='campanhas.campanhatrafego', verbose_name='Campanha de Origem')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Lead/Prospecto',
                'verbose_name_plural': '📊 01. Leads/Prospectos',
                'db_table': 'leads_prospectos',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='ImagemLeadProspecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.URLField(max_length=1024, verbose_name='URL da Imagem')),
                ('descricao', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição')),
                ('status_validacao', models.CharField(choices=[('pendente', 'Pendente'), ('documentos_validos', 'Documentos Válidos'), ('documentos_rejeitados', 'Documentos Rejeitados')], db_index=True, default='pendente', max_length=30, verbose_name='Status de Validação')),
                ('observacao_validacao', models.TextField(blank=True, default='', verbose_name='Observação da Validação')),
                ('data_validacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Validação')),
                ('validado_por', models.CharField(blank=True, default='', max_length=150, verbose_name='Validado por')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='leads.leadprospecto', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Imagem do Lead',
                'verbose_name_plural': 'Imagens do Lead',
                'db_table': 'imagens_lead_prospecto',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(help_text='Número de telefone do contato', max_length=17, verbose_name='Telefone')),
                ('data_hora_contato', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora do Contato')),
                ('status', models.CharField(max_length=30, verbose_name='Status do Contato')),
                ('nome_contato', models.CharField(blank=True, help_text='Nome identificado durante o contato', max_length=255, null=True, verbose_name='Nome do Contato')),
                ('duracao_segundos', models.PositiveIntegerField(blank=True, help_text='Duração da chamada em segundos', null=True, verbose_name='Duração (segundos)')),
                ('transcricao', models.TextField(blank=True, help_text='Transcrição da conversa', null=True, verbose_name='Transcrição')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o contato', null=True, verbose_name='Observações')),
                ('ip_origem', models.GenericIPAddressField(blank=True, help_text='IP de onde partiu a chamada', null=True, verbose_name='IP de Origem')),
                ('user_agent', models.TextField(blank=True, help_text='User agent do sistema que fez a chamada', null=True, verbose_name='User Agent')),
                ('dados_extras', models.JSONField(blank=True, help_text='Dados JSON com informações extras do contato', null=True, verbose_name='Dados Extras')),
                ('sucesso', models.BooleanField(default=False, help_text='Indica se o contato foi bem-sucedido', verbose_name='Sucesso')),
                ('converteu_lead', models.BooleanField(default=False, help_text='Indica se este contato gerou um lead/prospecto', verbose_name='Converteu em Lead')),
                ('data_conversao_lead', models.DateTimeField(blank=True, help_text='Data quando foi convertido em lead/prospecto', null=True, verbose_name='Data de Conversão em Lead')),
                ('converteu_venda', models.BooleanField(default=False, help_text='Indica se este lead se tornou uma venda confirmada', verbose_name='Converteu em Venda')),
                ('data_conversao_venda', models.DateTimeField(blank=True, help_text='Data quando foi confirmada a venda', null=True, verbose_name='Data de Conversão em Venda')),
                ('valor_venda', models.DecimalField(blank=True, decimal_places=2, help_text='Valor em reais da venda confirmada', max_digits=12, null=True, verbose_name='Valor da Venda')),
                ('origem_contato', models.CharField(blank=True, choices=[('site', 'Site'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google Ads'), ('whatsapp', 'WhatsApp'), ('indicacao', 'Indicação'), ('telefone', 'Telefone'), ('email', 'Email'), ('outros', 'Outros')], help_text='Canal de origem do contato', max_length=50, null=True, verbose_name='Origem do Contato')),
                ('identificador_cliente', models.CharField(blank=True, help_text='Hash ou ID único para agrupar contatos do mesmo cliente', max_length=255, null=True, verbose_name='Identificador do Cliente')),
                ('id_conta', models.CharField(blank=True, db_index=True, help_text='Identificador da conta do cliente no sistema', max_length=100, null=True, verbose_name='ID da Conta')),
                ('numero_conta', models.CharField(blank=True, db_index=True, help_text='Número da conta do cliente', max_length=100, null=True, verbose_name='Número da Conta')),
                ('ultima_mensagem', models.TextField(blank=True, help_text='Última mensagem enviada ou recebida no contato', null=True, verbose_name='Última Mensagem')),
                ('protocolo_atendimento', models.CharField(blank=True, db_index=True, help_text='Número de protocolo do atendimento', max_length=100, null=True, verbose_name='Protocolo de Atendimento')),
                ('codigo_atendimento', models.CharField(blank=True, db_index=True, help_text='Código único do atendimento', max_length=100, null=True, verbose_name='Código de Atendimento')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_contatos', to='leads.leadprospecto', verbose_name='Lead Relacionado')),
            ],
            options={
                'verbose_name': 'Histórico de Contato',
                'verbose_name_plural': '📊 03. Histórico de Contatos',
                'db_table': 'historico_contato',
                'ordering': ['-data_hora_contato'],
            },
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prospecto', models.CharField(max_length=255, verbose_name='Nome do Prospecto')),
                ('id_prospecto_hubsoft', models.CharField(blank=True, help_text='ID único no sistema Hubsoft', max_length=100, null=True, unique=True, verbose_name='ID Prospecto Hubsoft')),
                ('status', models.CharField(default='pendente', help_text='Status atual do processamento', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_processamento', models.DateTimeField(blank=True, help_text='Data e hora do último processamento', null=True, verbose_name='Data de Processamento')),
                ('tentativas_processamento', models.PositiveIntegerField(default=0, help_text='Número de tentativas de processamento', verbose_name='Tentativas de Processamento')),
                ('tempo_processamento', models.DecimalField(blank=True, decimal_places=3, help_text='Tempo de processamento em segundos', max_digits=10, null=True, verbose_name='Tempo de Processamento')),
                ('erro_processamento', models.TextField(blank=True, help_text='Detalhes do erro durante o processamento', null=True, verbose_name='Erro de Processamento')),
                ('data_inicio_processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data Início Processamento')),
                ('data_fim_processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data Fim Processamento')),
                ('usuario_processamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuário que Processou')),
                ('score_conversao', models.DecimalField(blank=True, decimal_places=2, help_text='Probabilidade de conversão calculada (0-100%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score de Conversão')),
                ('prioridade', models.PositiveIntegerField(default=1, help_text='Prioridade do processamento (1=baixa, 5=alta)', verbose_name='Prioridade')),
                ('dados_processamento', models.JSONField(blank=True, help_text='Dados JSON com informações do processamento', null=True, verbose_name='Dados de Processamento')),
                ('resultado_processamento', models.JSONField(blank=True, help_text='Resultado JSON do processamento', null=True, verbose_name='Resultado do Processamento')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospectos', to='leads.leadprospecto', verbose_name='Lead Relacionado')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Prospecto',
                'verbose_name_plural': '📊 02. Prospectos',
                'db_table': 'prospectos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['email'], name='leads_prosp_email_414191_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['telefone'], name='leads_prosp_telefon_d5e731_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['data_cadastro'], name='leads_prosp_data_ca_fb3e15_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['status_api'], name='leads_prosp_status__5a52c2_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['origem'], name='leads_prosp_origem_85b6d6_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['id_hubsoft'], name='leads_prosp_id_hubs_32a959_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['id_origem'], name='leads_prosp_id_orig_e65820_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['id_origem_servico'], name='leads_prosp_id_orig_f2e894_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['canal_entrada'], name='leads_prosp_canal_e_bf753f_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['tipo_entrada'], name='leads_prosp_tipo_en_fdceb2_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['score_qualificacao'], name='leads_prosp_score_q_c74bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['data_ultimo_contato'], name='leads_prosp_data_ul_3fc6e1_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['tentativas_contato'], name='leads_prosp_tentati_f48189_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['canal_entrada', 'data_cadastro'], name='leads_prosp_canal_e_c84337_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['score_qualificacao', 'status_api'], name='leads_prosp_score_q_60b836_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['tipo_entrada', 'ativo'], name='leads_prosp_tipo_en_3d0197_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['data_ultimo_contato', 'tentativas_contato'], name='leads_prosp_data_ul_6e46eb_idx'),
        ),
        migrations.AddIndex(
            model_name='imagemleadprospecto',
            index=models.Index(fields=['lead'], name='imagens_lea_lead_id_c4fae0_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['telefone'], name='historico_c_telefon_e30cae_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['data_hora_contato'], name='historico_c_data_ho_ed88a8_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['status'], name='historico_c_status_3dd74d_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['sucesso'], name='historico_c_sucesso_5720b3_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['converteu_lead'], name='historico_c_convert_70ea4e_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['converteu_venda'], name='historico_c_convert_600b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['data_conversao_lead'], name='historico_c_data_co_d999e6_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['data_conversao_venda'], name='historico_c_data_co_eee962_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['origem_contato'], name='historico_c_origem__8a44c7_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['identificador_cliente'], name='historico_c_identif_f20d30_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['id_conta'], name='historico_c_id_cont_b9e662_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['numero_conta'], name='historico_c_numero__50613e_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['protocolo_atendimento'], name='historico_c_protoco_cfa95e_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['codigo_atendimento'], name='historico_c_codigo__fe1f23_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['data_hora_contato', 'status'], name='historico_c_data_ho_ba55c3_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['converteu_lead', 'data_conversao_lead'], name='historico_c_convert_c52a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['converteu_venda', 'data_conversao_venda'], name='historico_c_convert_7c1356_idx'),
        ),
        migrations.AddIndex(
            model_name='prospecto',
            index=models.Index(fields=['status'], name='prospectos_status_79c72a_idx'),
        ),
        migrations.AddIndex(
            model_name='prospecto',
            index=models.Index(fields=['data_criacao'], name='prospectos_data_cr_978d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='prospecto',
            index=models.Index(fields=['id_prospecto_hubsoft'], name='prospectos_id_pros_a37429_idx'),
        ),
        migrations.AddIndex(
            model_name='prospecto',
            index=models.Index(fields=['tentativas_processamento'], name='prospectos_tentati_6d61d7_idx'),
        ),
        migrations.AddIndex(
            model_name='prospecto',
            index=models.Index(fields=['data_inicio_processamento'], name='prospectos_data_in_768e09_idx'),
        ),
        migrations.AddIndex(
            model_name='prospecto',
            index=models.Index(fields=['data_fim_processamento'], name='prospectos_data_fi_298986_idx'),
        ),
        migrations.AddIndex(
            model_name='prospecto',
            index=models.Index(fields=['usuario_processamento'], name='prospectos_usuario_ffb44b_idx'),
        ),
        migrations.AddIndex(
            model_name='prospecto',
            index=models.Index(fields=['score_conversao'], name='prospectos_score_c_57dabd_idx'),
        ),
        migrations.AddIndex(
            model_name='prospecto',
            index=models.Index(fields=['status', 'data_inicio_processamento'], name='prospectos_status_dd0be9_idx'),
        ),
        migrations.AddIndex(
            model_name='prospecto',
            index=models.Index(fields=['prioridade', 'data_criacao'], name='prospectos_priorid_1e3057_idx'),
        ),
        migrations.AddIndex(
            model_name='prospecto',
            index=models.Index(fields=['score_conversao', 'status'], name='prospectos_score_c_bfee71_idx'),
        ),
    ]
