# Generated by Django 5.2.4 on 2026-04-06 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('sistema', '0004_funcionalidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadprospecto',
            name='dados_custom',
            field=models.JSONField(blank=True, default=dict, help_text='Campos personalizados definidos pelo tenant', verbose_name='Dados Customizados'),
        ),
        migrations.CreateModel(
            name='CampoCustomizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome exibido no formulario', max_length=100, verbose_name='Nome do Campo')),
                ('slug', models.SlugField(help_text='Chave unica usada no JSON (gerado automaticamente)', max_length=100, verbose_name='Identificador')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Numero'), ('decimal', 'Decimal'), ('data', 'Data'), ('booleano', 'Sim/Nao'), ('select', 'Lista de opcoes'), ('textarea', 'Texto longo')], default='texto', max_length=20, verbose_name='Tipo do Campo')),
                ('opcoes', models.JSONField(blank=True, default=list, help_text='Lista de opcoes para campos do tipo \'select\'. Ex: ["Opcao 1", "Opcao 2"]', verbose_name='Opcoes')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='Obrigatorio')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibicao')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Campo Customizado',
                'verbose_name_plural': 'Campos Customizados',
                'db_table': 'campos_customizados_lead',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
    ]
