# Generated by Django 5.2.4 on 2026-04-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_leadprospecto_dados_custom_campocustomizado'),
        ('sistema', '0005_logsistema_acao_logsistema_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campocustomizado',
            options={'ordering': ['entidade', 'ordem', 'nome'], 'verbose_name': 'Campo Customizado', 'verbose_name_plural': 'Campos Customizados'},
        ),
        migrations.AlterUniqueTogether(
            name='campocustomizado',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='campocustomizado',
            name='entidade',
            field=models.CharField(choices=[('lead', 'Lead'), ('oportunidade', 'Oportunidade')], db_index=True, default='lead', help_text='A qual entidade este campo pertence', max_length=20, verbose_name='Entidade'),
        ),
        migrations.AlterUniqueTogether(
            name='campocustomizado',
            unique_together={('tenant', 'slug', 'entidade')},
        ),
        migrations.AlterModelTable(
            name='campocustomizado',
            table='campos_customizados',
        ),
    ]
