# Generated by Django 5.2.4 on 2026-05-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_campocustomizado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadprospecto',
            name='status_api',
            field=models.CharField(default='pendente', help_text='Status do processamento na API (ex: pendente, processamento_manual, aguardando_assinatura, cliente)', max_length=50, verbose_name='Status API'),
        ),
    ]
