# Generated by Django 5.2.4 on 2026-06-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_leadprospecto_status_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadprospecto',
            name='numero_residencia',
            field=models.CharField(blank=True, help_text="Número do endereço (pode conter texto livre, ex: 'Quadra 15 casa 3')", max_length=100, null=True, verbose_name='Número da Residência'),
        ),
    ]
