# Generated by Django 5.2.4 on 2026-06-01 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_leadprospecto_numero_residencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadprospecto',
            name='cep',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='leadprospecto',
            name='estado',
            field=models.CharField(blank=True, help_text='UF do estado (sigla 2 letras ou nome curto)', max_length=20, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='leadprospecto',
            name='telefone',
            field=models.CharField(help_text='Telefone de contato', max_length=20, validators=[django.core.validators.RegexValidator(message="Telefone deve estar no formato: '+999999999'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone'),
        ),
    ]
