# Generated by Django 5.2.4 on 2026-06-16 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_leadprospecto_cep_alter_leadprospecto_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leadprospecto',
            name='score_atualizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Score atualizado em'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='score_atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Score atualizado por'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='score_status',
            field=models.CharField(choices=[('nao_consultado', 'Nao consultado'), ('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], db_index=True, default='nao_consultado', help_text='Resultado da analise de score externa (binario). Usado como gate para abrir OS e assinar contrato no HubSoft.', max_length=20, verbose_name='Score externo'),
        ),
    ]
