# Generated by Django 5.2.4 on 2026-06-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_leadprospecto_score_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadprospecto',
            name='atendido_em',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp da primeira interacao humana com o lead. Usado no relatorio de performance/TMA das consultoras.', null=True, verbose_name='Atendido em (primeira interacao humana)'),
        ),
    ]
