# Generated by Django 5.2.4 on 2026-06-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_leadprospecto_atendido_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicocontato',
            name='telefone',
            field=models.CharField(help_text='Número de telefone do contato', max_length=32, verbose_name='Telefone'),
        ),
    ]
