# Generated by Django 5.2.4 on 2026-06-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_historicocontato_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadprospecto',
            name='complemento',
            field=models.CharField(blank=True, help_text='Apto, casa, bloco, sala — coletado pelo flow Matrix e usado no HubSoft.', max_length=120, null=True, verbose_name='Complemento'),
        ),
    ]
