# Generated by Django 5.2.4 on 2026-06-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_leadprospecto_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadprospecto',
            name='cep',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP'),
        ),
    ]
