# Generated by Django 5.2.4 on 2026-06-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_leadprospecto_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadprospecto',
            name='canal',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('telefone', 'Telefone'), ('email', 'Email'), ('site', 'Site'), ('sms', 'SMS'), ('loja_fisica', 'Loja Física'), ('manual', 'Manual / Operador')], db_index=True, help_text='Meio fisico de chegada (WhatsApp, Telefone, Site, etc)', max_length=20, null=True, verbose_name='Canal'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='fonte',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('indicacao', 'Indicação'), ('parceiro', 'Parceiro'), ('organico', 'Orgânico'), ('email_mkt', 'Email Marketing'), ('direto', 'Direto'), ('outros', 'Outros')], db_index=True, help_text='Plataforma que trouxe o trafego (Facebook, Google, Indicacao, etc)', max_length=30, null=True, verbose_name='Fonte'),
        ),
    ]
