# Generated by Django 5.2.4 on 2026-07-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_migrar_origem_canal_fonte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicocontato',
            name='status',
            field=models.CharField(choices=[('fluxo_inicializado', 'Fluxo Inicializado'), ('fluxo_finalizado', 'Fluxo Finalizado'), ('transferido_humano', 'Transferido para Humano'), ('chamada_perdida', 'Chamada Perdida'), ('ligacao_atendida', 'Ligação Atendida'), ('ocupado', 'Ocupado'), ('desligou', 'Desligou'), ('nao_atendeu', 'Não Atendeu'), ('abandonou_fluxo', 'Abandonou o Fluxo'), ('numero_invalido', 'Número Inválido'), ('erro_sistema', 'Erro do Sistema'), ('convertido_lead', 'Convertido em Lead'), ('venda_confirmada', 'Venda Confirmada'), ('venda_rejeitada', 'Venda Rejeitada'), ('venda_sem_viabilidade', 'Venda Sem Viabilidade'), ('cliente_desistiu', 'Cliente Desistiu'), ('aguardando_validacao', 'Aguardando Validação'), ('followup_agendado', 'Follow-up Agendado'), ('nao_qualificado', 'Não Qualificado')], max_length=30, verbose_name='Status do Contato'),
        ),
    ]
