# Generated by Django 5.2.4 on 2025-08-04 12:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(help_text='Chave única da configuração', max_length=100, unique=True, verbose_name='Chave')),
                ('valor', models.TextField(help_text='Valor da configuração', verbose_name='Valor')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da configuração', null=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON'), ('decimal', 'Decimal')], default='string', help_text='Tipo do valor da configuração', max_length=20, verbose_name='Tipo')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
                'db_table': 'configuracao_sistema',
                'ordering': ['chave'],
            },
        ),
        migrations.CreateModel(
            name='LeadProspecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razaosocial', models.CharField(help_text='Nome completo ou razão social do cliente', max_length=255, verbose_name='Nome/Razão Social')),
                ('email', models.EmailField(help_text='Email válido do cliente', max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('telefone', models.CharField(help_text='Telefone de contato', max_length=17, validators=[django.core.validators.RegexValidator(message="Telefone deve estar no formato: '+999999999'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Valor em reais associado ao lead', max_digits=12, null=True, verbose_name='Valor')),
                ('empresa', models.CharField(blank=True, help_text='Nome da empresa do cliente', max_length=255, null=True, verbose_name='Empresa')),
                ('origem', models.CharField(choices=[('site', 'Site'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google Ads'), ('whatsapp', 'WhatsApp'), ('indicacao', 'Indicação'), ('telefone', 'Telefone'), ('email', 'Email'), ('outros', 'Outros')], default='site', help_text='Canal de origem do lead', max_length=50, verbose_name='Origem')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora do cadastro', verbose_name='Data de Cadastro')),
                ('status_api', models.CharField(choices=[('pendente', 'Pendente'), ('processado', 'Processado'), ('erro', 'Erro'), ('sucesso', 'Sucesso'), ('rejeitado', 'Rejeitado')], default='pendente', help_text='Status do processamento na API', max_length=20, verbose_name='Status API')),
                ('cpf_cnpj', models.CharField(blank=True, help_text='CPF ou CNPJ do cliente', max_length=18, null=True, verbose_name='CPF/CNPJ')),
                ('endereco', models.TextField(blank=True, help_text='Endereço completo do cliente', null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, help_text='UF do estado', max_length=2, null=True, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre o lead', null=True, verbose_name='Observações')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o lead está ativo', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Lead/Prospecto',
                'verbose_name_plural': 'Leads/Prospectos',
                'db_table': 'leads_prospectos',
                'ordering': ['-data_cadastro'],
                'indexes': [models.Index(fields=['email'], name='leads_prosp_email_414191_idx'), models.Index(fields=['telefone'], name='leads_prosp_telefon_d5e731_idx'), models.Index(fields=['data_cadastro'], name='leads_prosp_data_ca_fb3e15_idx'), models.Index(fields=['status_api'], name='leads_prosp_status__5a52c2_idx'), models.Index(fields=['origem'], name='leads_prosp_origem_85b6d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10, verbose_name='Nível')),
                ('modulo', models.CharField(help_text='Módulo/função que gerou o log', max_length=100, verbose_name='Módulo')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('dados_extras', models.JSONField(blank=True, help_text='Dados JSON com informações extras', null=True, verbose_name='Dados Extras')),
                ('usuario', models.CharField(blank=True, help_text='Usuário relacionado ao log', max_length=100, null=True, verbose_name='Usuário')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Log do Sistema',
                'verbose_name_plural': 'Logs do Sistema',
                'db_table': 'log_sistema',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['nivel'], name='log_sistema_nivel_570003_idx'), models.Index(fields=['data_criacao'], name='log_sistema_data_cr_aae550_idx'), models.Index(fields=['modulo'], name='log_sistema_modulo_a0fbdb_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(help_text='Número de telefone do contato', max_length=17, verbose_name='Telefone')),
                ('data_hora_contato', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora do Contato')),
                ('status', models.CharField(choices=[('fluxo_inicializado', 'Fluxo Inicializado'), ('fluxo_finalizado', 'Fluxo Finalizado'), ('transferido_humano', 'Transferido para Humano'), ('chamada_perdida', 'Chamada Perdida'), ('ocupado', 'Ocupado'), ('desligou', 'Desligou'), ('nao_atendeu', 'Não Atendeu'), ('erro_sistema', 'Erro do Sistema')], max_length=30, verbose_name='Status do Contato')),
                ('nome_contato', models.CharField(blank=True, help_text='Nome identificado durante o contato', max_length=255, null=True, verbose_name='Nome do Contato')),
                ('duracao_segundos', models.PositiveIntegerField(blank=True, help_text='Duração da chamada em segundos', null=True, verbose_name='Duração (segundos)')),
                ('transcricao', models.TextField(blank=True, help_text='Transcrição da conversa', null=True, verbose_name='Transcrição')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o contato', null=True, verbose_name='Observações')),
                ('ip_origem', models.GenericIPAddressField(blank=True, help_text='IP de onde partiu a chamada', null=True, verbose_name='IP de Origem')),
                ('user_agent', models.TextField(blank=True, help_text='User agent do sistema que fez a chamada', null=True, verbose_name='User Agent')),
                ('dados_extras', models.JSONField(blank=True, help_text='Dados JSON com informações extras do contato', null=True, verbose_name='Dados Extras')),
                ('sucesso', models.BooleanField(default=False, help_text='Indica se o contato foi bem-sucedido', verbose_name='Sucesso')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_contatos', to='vendas_web.leadprospecto', verbose_name='Lead Relacionado')),
            ],
            options={
                'verbose_name': 'Histórico de Contato',
                'verbose_name_plural': 'Histórico de Contatos',
                'db_table': 'historico_contato',
                'ordering': ['-data_hora_contato'],
                'indexes': [models.Index(fields=['telefone'], name='historico_c_telefon_e30cae_idx'), models.Index(fields=['data_hora_contato'], name='historico_c_data_ho_ed88a8_idx'), models.Index(fields=['status'], name='historico_c_status_3dd74d_idx'), models.Index(fields=['sucesso'], name='historico_c_sucesso_5720b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prospecto', models.CharField(max_length=255, verbose_name='Nome do Prospecto')),
                ('id_prospecto_hubsoft', models.CharField(blank=True, help_text='ID único no sistema Hubsoft', max_length=100, null=True, unique=True, verbose_name='ID Prospecto Hubsoft')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('processado', 'Processado'), ('erro', 'Erro'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendente', help_text='Status atual do processamento', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_processamento', models.DateTimeField(blank=True, help_text='Data e hora do último processamento', null=True, verbose_name='Data de Processamento')),
                ('tentativas_processamento', models.PositiveIntegerField(default=0, help_text='Número de tentativas de processamento', verbose_name='Tentativas de Processamento')),
                ('tempo_processamento', models.DecimalField(blank=True, decimal_places=3, help_text='Tempo de processamento em segundos', max_digits=10, null=True, verbose_name='Tempo de Processamento')),
                ('erro_processamento', models.TextField(blank=True, help_text='Detalhes do erro durante o processamento', null=True, verbose_name='Erro de Processamento')),
                ('prioridade', models.PositiveIntegerField(default=1, help_text='Prioridade do processamento (1=baixa, 5=alta)', verbose_name='Prioridade')),
                ('dados_processamento', models.JSONField(blank=True, help_text='Dados JSON com informações do processamento', null=True, verbose_name='Dados de Processamento')),
                ('resultado_processamento', models.JSONField(blank=True, help_text='Resultado JSON do processamento', null=True, verbose_name='Resultado do Processamento')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospectos', to='vendas_web.leadprospecto', verbose_name='Lead Relacionado')),
            ],
            options={
                'verbose_name': 'Prospecto',
                'verbose_name_plural': 'Prospectos',
                'db_table': 'prospectos',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['status'], name='prospectos_status_79c72a_idx'), models.Index(fields=['data_criacao'], name='prospectos_data_cr_978d2e_idx'), models.Index(fields=['id_prospecto_hubsoft'], name='prospectos_id_pros_a37429_idx'), models.Index(fields=['tentativas_processamento'], name='prospectos_tentati_6d61d7_idx')],
            },
        ),
    ]
