# Generated by Django 5.2.4 on 2025-08-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocontato',
            name='converteu_lead',
            field=models.BooleanField(default=False, help_text='Indica se este contato gerou um lead/prospecto', verbose_name='Converteu em Lead'),
        ),
        migrations.AddField(
            model_name='historicocontato',
            name='converteu_venda',
            field=models.BooleanField(default=False, help_text='Indica se este lead se tornou uma venda confirmada', verbose_name='Converteu em Venda'),
        ),
        migrations.AddField(
            model_name='historicocontato',
            name='data_conversao_lead',
            field=models.DateTimeField(blank=True, help_text='Data quando foi convertido em lead/prospecto', null=True, verbose_name='Data de Conversão em Lead'),
        ),
        migrations.AddField(
            model_name='historicocontato',
            name='data_conversao_venda',
            field=models.DateTimeField(blank=True, help_text='Data quando foi confirmada a venda', null=True, verbose_name='Data de Conversão em Venda'),
        ),
        migrations.AddField(
            model_name='historicocontato',
            name='identificador_cliente',
            field=models.CharField(blank=True, help_text='Hash ou ID único para agrupar contatos do mesmo cliente', max_length=255, null=True, verbose_name='Identificador do Cliente'),
        ),
        migrations.AddField(
            model_name='historicocontato',
            name='origem_contato',
            field=models.CharField(blank=True, choices=[('site', 'Site'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google Ads'), ('whatsapp', 'WhatsApp'), ('indicacao', 'Indicação'), ('telefone', 'Telefone'), ('email', 'Email'), ('outros', 'Outros')], help_text='Canal de origem do contato', max_length=50, null=True, verbose_name='Origem do Contato'),
        ),
        migrations.AddField(
            model_name='historicocontato',
            name='valor_venda',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor em reais da venda confirmada', max_digits=12, null=True, verbose_name='Valor da Venda'),
        ),
        migrations.AlterField(
            model_name='historicocontato',
            name='status',
            field=models.CharField(choices=[('fluxo_inicializado', 'Fluxo Inicializado'), ('fluxo_finalizado', 'Fluxo Finalizado'), ('transferido_humano', 'Transferido para Humano'), ('chamada_perdida', 'Chamada Perdida'), ('ocupado', 'Ocupado'), ('desligou', 'Desligou'), ('nao_atendeu', 'Não Atendeu'), ('abandonou_fluxo', 'Abandonou o Fluxo'), ('numero_invalido', 'Número Inválido'), ('erro_sistema', 'Erro do Sistema'), ('convertido_lead', 'Convertido em Lead'), ('venda_confirmada', 'Venda Confirmada'), ('venda_rejeitada', 'Venda Rejeitada')], max_length=30, verbose_name='Status do Contato'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['converteu_lead'], name='historico_c_convert_70ea4e_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['converteu_venda'], name='historico_c_convert_600b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['data_conversao_lead'], name='historico_c_data_co_d999e6_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['data_conversao_venda'], name='historico_c_data_co_eee962_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['origem_contato'], name='historico_c_origem__8a44c7_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['identificador_cliente'], name='historico_c_identif_f20d30_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['data_hora_contato', 'status'], name='historico_c_data_ho_ba55c3_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['converteu_lead', 'data_conversao_lead'], name='historico_c_convert_c52a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['converteu_venda', 'data_conversao_venda'], name='historico_c_convert_7c1356_idx'),
        ),
    ]
