# Generated by Django 5.2.4 on 2025-08-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0006_leadprospecto_bairro_leadprospecto_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicocontato',
            name='status',
            field=models.CharField(max_length=30, verbose_name='Status do Contato'),
        ),
        migrations.AlterField(
            model_name='leadprospecto',
            name='status_api',
            field=models.CharField(default='pendente', help_text='Status do processamento na API', max_length=20, verbose_name='Status API'),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='status',
            field=models.CharField(default='pendente', help_text='Status atual do processamento', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='StatusConfiguravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('lead_status_api', 'Lead: Status API'), ('prospecto_status', 'Prospecto: Status'), ('historico_status', 'Histórico: Status')], db_index=True, max_length=50)),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('rotulo', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'status_configuravel',
                'ordering': ['grupo', 'ordem', 'codigo'],
                'unique_together': {('grupo', 'codigo')},
            },
        ),
    ]
