# Generated by Django 5.2.4 on 2025-08-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0008_alter_statusconfiguravel_grupo_fluxoatendimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentofluxo',
            name='dados_respostas',
            field=models.JSONField(blank=True, default=dict, help_text='JSON com todas as respostas do usuário', null=True, verbose_name='Dados das Respostas'),
        ),
    ]
