# Generated by Django 5.2.4 on 2025-09-25 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0012_questaofluxo_criterios_ia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='Sua Empresa', help_text='Nome da empresa que aparecerá no sistema', max_length=100, verbose_name='Nome da Empresa')),
                ('logo_empresa', models.ImageField(blank=True, help_text='Logo da empresa (recomendado: 200x200px)', null=True, upload_to='logos/', verbose_name='Logo da Empresa')),
                ('cor_primaria', models.CharField(default='#1F3D59', help_text='Cor primária da empresa (formato HEX, ex: #1F3D59)', max_length=7, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor Primária')),
                ('cor_secundaria', models.CharField(default='#2c5aa0', help_text='Cor secundária da empresa (formato HEX, ex: #2c5aa0)', max_length=7, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor Secundária')),
                ('ativo', models.BooleanField(default=True, help_text='Se esta configuração está ativa', verbose_name='Configuração Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da Empresa',
                'verbose_name_plural': 'Configurações da Empresa',
                'ordering': ['-ativo', '-data_criacao'],
            },
        ),
    ]
