# Generated by Django 5.2.4 on 2025-10-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0014_alter_atendimentofluxo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRecontato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem de Recontato')),
                ('tempo_recontato', models.PositiveIntegerField(verbose_name='Tempo para Recontato')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Configuração de Recontato',
                'verbose_name_plural': '⚙️ 03. Configurações de Recontato',
                'db_table': 'configuracoes_recontato',
                'ordering': ['-ativo'],
            },
        ),
    ]
