# Generated by Django 5.2.4 on 2025-10-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0016_canalnotificacao_tiponotificacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canalnotificacao',
            name='codigo',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('webhook', 'Webhook')], max_length=20, unique=True, verbose_name='Código'),
        ),
    ]
