# Generated by Django 5.2.4 on 2025-10-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0017_update_canal_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiponotificacao',
            name='whatsapp_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configurações específicas para o canal WhatsApp', verbose_name='Configuração WhatsApp'),
        ),
    ]
