# Generated by Django 5.2.4 on 2025-10-20 23:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0020_remove_unnecessary_notification_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, help_text='Número de telefone para contato e notificações', max_length=20, null=True, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, help_text='Número do WhatsApp (pode ser diferente do telefone)', max_length=20, null=True, verbose_name='WhatsApp')),
                ('cargo', models.CharField(blank=True, help_text='Cargo ou função do usuário', max_length=100, null=True, verbose_name='Cargo')),
                ('departamento', models.CharField(blank=True, help_text='Departamento ou setor', max_length=100, null=True, verbose_name='Departamento')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': '👤 05. Perfis de Usuário',
                'ordering': ['user__username'],
            },
        ),
    ]
