# Generated by Django 5.2.4 on 2025-10-20 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0021_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
