# Generated by Django 5.2.4 on 2025-10-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0024_leadprospecto_metadata_campanhas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocontato',
            name='id_conta',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador da conta do cliente no sistema', max_length=100, null=True, verbose_name='ID da Conta'),
        ),
        migrations.AddField(
            model_name='historicocontato',
            name='numero_conta',
            field=models.CharField(blank=True, db_index=True, help_text='Número da conta do cliente', max_length=100, null=True, verbose_name='Número da Conta'),
        ),
        migrations.AddField(
            model_name='historicocontato',
            name='protocolo_atendimento',
            field=models.CharField(blank=True, db_index=True, help_text='Número de protocolo do atendimento', max_length=100, null=True, verbose_name='Protocolo de Atendimento'),
        ),
        migrations.AddField(
            model_name='historicocontato',
            name='ultima_mensagem',
            field=models.TextField(blank=True, help_text='Última mensagem enviada ou recebida no contato', null=True, verbose_name='Última Mensagem'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='id_origem',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador único do lead no sistema de origem (Facebook Ads, Google Ads, etc)', max_length=100, null=True, verbose_name='ID Origem'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='ponto_referencia',
            field=models.CharField(blank=True, help_text='Ponto de referência para facilitar a localização', max_length=255, null=True, verbose_name='Ponto de Referência'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['id_conta'], name='historico_c_id_cont_b9e662_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['numero_conta'], name='historico_c_numero__50613e_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['protocolo_atendimento'], name='historico_c_protoco_cfa95e_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['id_origem'], name='leads_prosp_id_orig_e65820_idx'),
        ),
    ]
