# Generated by Django 5.2.4 on 2026-03-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0028_configuracaocadastro_id_origem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoempresa',
            name='nome_empresa',
            field=models.CharField(default='Megalink', help_text='Nome da empresa que aparecerá no sistema', max_length=100, verbose_name='Nome da Empresa'),
        ),
    ]
