# Generated by Django 5.2.4 on 2026-03-12 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0029_alter_configuracaoempresa_nome_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemLeadProspecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.URLField(max_length=1024, verbose_name='URL da Imagem')),
                ('descricao', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='vendas_web.leadprospecto', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Imagem do Lead',
                'verbose_name_plural': 'Imagens do Lead',
                'db_table': 'imagens_lead_prospecto',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['lead'], name='imagens_lea_lead_id_c4fae0_idx')],
            },
        ),
    ]
