# Generated by Django 5.2.4 on 2026-03-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0030_add_imagem_lead_prospecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemleadprospecto',
            name='data_validacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Validação'),
        ),
        migrations.AddField(
            model_name='imagemleadprospecto',
            name='observacao_validacao',
            field=models.TextField(blank=True, default='', verbose_name='Observação da Validação'),
        ),
        migrations.AddField(
            model_name='imagemleadprospecto',
            name='status_validacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('documentos_validos', 'Documentos Válidos'), ('documentos_rejeitados', 'Documentos Rejeitados')], db_index=True, default='pendente', max_length=30, verbose_name='Status de Validação'),
        ),
        migrations.AddField(
            model_name='imagemleadprospecto',
            name='validado_por',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Validado por'),
        ),
    ]
