# Generated by Django 5.2.4 on 2026-03-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0031_add_validacao_imagem_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadprospecto',
            name='codigo_atendimento_pdf',
            field=models.CharField(blank=True, db_index=True, help_text='Código do atendimento usado para gerar o PDF da conversa', max_length=100, null=True, verbose_name='Código Atendimento (PDF)'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='data_geracao_pdf',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Geração do PDF'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='protocolo_atendimento_pdf',
            field=models.CharField(blank=True, help_text='Protocolo do atendimento usado para gerar o PDF da conversa', max_length=100, null=True, verbose_name='Protocolo Atendimento (PDF)'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='url_pdf_conversa',
            field=models.URLField(blank=True, help_text='Link do PDF da conversa gerado após validação dos documentos', max_length=1024, null=True, verbose_name='URL PDF da Conversa'),
        ),
    ]
