# Generated by Django 5.2.4 on 2026-03-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0032_add_pdf_conversa_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadprospecto',
            name='codigo_atendimento_pdf',
        ),
        migrations.RemoveField(
            model_name='leadprospecto',
            name='protocolo_atendimento_pdf',
        ),
    ]
