# Generated by Django 5.2.4 on 2026-03-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0033_remove_campos_pdf_duplicados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadprospecto',
            name='url_pdf_conversa',
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='arquivo_pdf_conversa',
            field=models.FileField(blank=True, help_text='Arquivo PDF da conversa baixado após validação dos documentos', null=True, upload_to='pdfs_conversa/', verbose_name='PDF da Conversa'),
        ),
        migrations.AlterField(
            model_name='leadprospecto',
            name='data_geracao_pdf',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Download do PDF'),
        ),
    ]
