# Generated by Django 5.2.4 on 2026-03-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0035_remove_leadprospecto_arquivo_pdf_conversa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadprospecto',
            name='data_geracao_html',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Geração do HTML'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='html_conversa_path',
            field=models.CharField(blank=True, help_text='Caminho relativo do arquivo HTML gerado do atendimento', max_length=500, null=True, verbose_name='Caminho HTML da Conversa'),
        ),
    ]
