# Generated by Django 5.2.4 on 2026-03-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0036_html_conversa_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadprospecto',
            name='anexos_contrato_enviados',
            field=models.BooleanField(default=False, help_text='Indica se os documentos e o HTML do atendimento foram anexados ao contrato no HubSoft', verbose_name='Anexos do Contrato Enviados'),
        ),
    ]
