# Generated by Django 5.2.4 on 2026-03-16 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0037_anexos_contrato_enviados'),
    ]

    operations = [
        migrations.CreateModel(
            name='CidadeViabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(db_index=True, help_text='Nome da cidade com viabilidade técnica', max_length=120, verbose_name='Cidade')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], db_index=True, max_length=2, verbose_name='Estado (UF)')),
                ('cep', models.CharField(blank=True, db_index=True, help_text='CEP exato com viabilidade (opcional, formato: 00000-000). Se não informado, toda a cidade é considerada viável.', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato 00000-000 ou 00000000', regex='^\\d{5}-?\\d{3}$')], verbose_name='CEP Específico')),
                ('bairro', models.CharField(blank=True, help_text='Bairro específico (opcional)', max_length=120, null=True, verbose_name='Bairro')),
                ('observacao', models.TextField(blank=True, help_text='Informações adicionais sobre esta região (tecnologia disponível, restrições, etc.)', null=True, verbose_name='Observação')),
                ('ativo', models.BooleanField(db_index=True, default=True, help_text='Desative para suspender temporariamente sem excluir o registro', verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cidade com Viabilidade',
                'verbose_name_plural': '📡 Viabilidade Técnica — Cidades',
                'ordering': ['estado', 'cidade', 'cep'],
                'indexes': [models.Index(fields=['cidade', 'estado'], name='vendas_web__cidade_08f1d7_idx')],
            },
        ),
    ]
