# Generated by Django 5.2.4 on 2026-03-29 18:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
        ('vendas_web', '0038_cidade_viabilidade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CidadeViabilidade',
        ),
        migrations.AlterModelOptions(
            name='configuracaoempresa',
            options={'ordering': ['-ativo', '-data_criacao'], 'verbose_name': 'Configuração da Empresa', 'verbose_name_plural': 'Configurações da Empresa'},
        ),
        migrations.AlterModelOptions(
            name='configuracaorecontato',
            options={'ordering': ['-ativo'], 'verbose_name': 'Configuração de Recontato', 'verbose_name_plural': 'Configurações de Recontato'},
        ),
        migrations.AlterModelOptions(
            name='configuracaosistema',
            options={'ordering': ['chave'], 'verbose_name': 'Configuração do Sistema', 'verbose_name_plural': 'Configurações do Sistema'},
        ),
        migrations.AlterModelOptions(
            name='logsistema',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Log do Sistema', 'verbose_name_plural': 'Logs do Sistema'},
        ),
        migrations.AlterModelOptions(
            name='statusconfiguravel',
            options={'ordering': ['grupo', 'ordem', 'codigo'], 'verbose_name': 'Status Configurável', 'verbose_name_plural': 'Status Configuráveis'},
        ),
        migrations.AlterUniqueTogether(
            name='statusconfiguravel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='atendimentofluxo',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='cadastrocliente',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='campanhatrafego',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='canalnotificacao',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_empresa', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='configuracaorecontato',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_recontato', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_sistema', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='deteccaocampanha',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='documentolead',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='fluxoatendimento',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='historicocontato',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='imagemleadprospecto',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='logsistema',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='opcaovencimento',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='planointernet',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='preferencianotificacao',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='questaofluxo',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='respostaquestao',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='statusconfiguravel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_configuraveis', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='templatenotificacao',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='tentativaresposta',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='tiponotificacao',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='configuracaoempresa',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Configuração Ativa'),
        ),
        migrations.AlterField(
            model_name='configuracaoempresa',
            name='cor_primaria',
            field=models.CharField(default='#1F3D59', max_length=7, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor Primária'),
        ),
        migrations.AlterField(
            model_name='configuracaoempresa',
            name='cor_secundaria',
            field=models.CharField(default='#2c5aa0', max_length=7, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor Secundária'),
        ),
        migrations.AlterField(
            model_name='configuracaoempresa',
            name='logo_empresa',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo da Empresa'),
        ),
        migrations.AlterField(
            model_name='configuracaoempresa',
            name='nome_empresa',
            field=models.CharField(default='Provedor', max_length=100, verbose_name='Nome da Empresa'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='chave',
            field=models.CharField(max_length=100, verbose_name='Chave'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='tipo',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON'), ('decimal', 'Decimal')], default='string', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='valor',
            field=models.TextField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='logsistema',
            name='dados_extras',
            field=models.JSONField(blank=True, null=True, verbose_name='Dados Extras'),
        ),
        migrations.AlterField(
            model_name='logsistema',
            name='modulo',
            field=models.CharField(max_length=100, verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='logsistema',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuário'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracaosistema',
            unique_together={('tenant', 'chave')},
        ),
        migrations.AlterUniqueTogether(
            name='statusconfiguravel',
            unique_together={('tenant', 'grupo', 'codigo')},
        ),
        migrations.AlterModelTable(
            name='configuracaoempresa',
            table='vendas_web_configuracaoempresa',
        ),
    ]
