# Generated by Django 5.2.4 on 2026-04-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0002_clientehubsoft_servicoclientehubsoft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracaoapi',
            name='tipo',
            field=models.CharField(choices=[('hubsoft', 'Hubsoft'), ('matrix', 'Matrix'), ('outro', 'Outro')], db_index=True, default='hubsoft', max_length=50, verbose_name='Tipo'),
        ),
    ]
