# Generated by Django 5.2.4 on 2026-04-20 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0003_alter_integracaoapi_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoHubsoft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_atendimento', models.BigIntegerField(unique=True, verbose_name='ID Atendimento')),
                ('protocolo', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('tipo_atendimento', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('status_fechamento', models.CharField(blank=True, default='', max_length=60)),
                ('motivo_fechamento', models.CharField(blank=True, default='', max_length=255)),
                ('setor_responsavel', models.CharField(blank=True, default='', max_length=120)),
                ('usuario_abertura', models.CharField(blank=True, default='', max_length=120)),
                ('usuario_responsavel', models.CharField(blank=True, default='', max_length=120)),
                ('usuario_fechamento', models.CharField(blank=True, default='', max_length=120)),
                ('descricao_abertura', models.TextField(blank=True, default='')),
                ('descricao_fechamento', models.TextField(blank=True, default='')),
                ('data_cadastro', models.CharField(blank=True, default='', max_length=30)),
                ('data_fechamento', models.CharField(blank=True, default='', max_length=30)),
                ('rascunho', models.BooleanField(default=False)),
                ('qtd_ordens_servico', models.PositiveIntegerField(default=0)),
                ('dados_completos', models.JSONField(blank=True, default=dict)),
                ('data_sync', models.DateTimeField(auto_now=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='integracoes.clientehubsoft', verbose_name='Cliente Hubsoft')),
            ],
            options={
                'verbose_name': 'Atendimento Hubsoft',
                'verbose_name_plural': 'Atendimentos Hubsoft',
                'db_table': 'atendimentos_hubsoft',
                'ordering': ['-data_cadastro', '-id_atendimento'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoHubsoft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ordem_servico', models.BigIntegerField(unique=True, verbose_name='ID OS')),
                ('numero_ordem_servico', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('tipo', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('status_fechamento', models.CharField(blank=True, default='', max_length=60)),
                ('usuario_abertura', models.CharField(blank=True, default='', max_length=120)),
                ('usuario_fechamento', models.CharField(blank=True, default='', max_length=120)),
                ('descricao_abertura', models.TextField(blank=True, default='')),
                ('descricao_servico', models.TextField(blank=True, default='')),
                ('descricao_fechamento', models.TextField(blank=True, default='')),
                ('data_cadastro', models.CharField(blank=True, default='', max_length=30)),
                ('data_inicio_programado', models.CharField(blank=True, default='', max_length=30)),
                ('data_termino_programado', models.CharField(blank=True, default='', max_length=30)),
                ('data_inicio_executado', models.CharField(blank=True, default='', max_length=30)),
                ('data_termino_executado', models.CharField(blank=True, default='', max_length=30)),
                ('tecnicos', models.JSONField(blank=True, default=list)),
                ('qtd_anexos', models.PositiveIntegerField(default=0)),
                ('dados_completos', models.JSONField(blank=True, default=dict)),
                ('data_sync', models.DateTimeField(auto_now=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_rel', to='integracoes.atendimentohubsoft')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='integracoes.clientehubsoft', verbose_name='Cliente Hubsoft')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço Hubsoft',
                'verbose_name_plural': 'Ordens de Serviço Hubsoft',
                'db_table': 'ordens_servico_hubsoft',
                'ordering': ['-data_cadastro', '-id_ordem_servico'],
            },
        ),
        migrations.AddIndex(
            model_name='atendimentohubsoft',
            index=models.Index(fields=['cliente', '-id_atendimento'], name='atendimento_cliente_30fa52_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimentohubsoft',
            index=models.Index(fields=['protocolo'], name='atendimento_protoco_386f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservicohubsoft',
            index=models.Index(fields=['cliente', '-id_ordem_servico'], name='ordens_serv_cliente_c26f28_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservicohubsoft',
            index=models.Index(fields=['numero_ordem_servico'], name='ordens_serv_numero__80428d_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservicohubsoft',
            index=models.Index(fields=['status'], name='ordens_serv_status_868f01_idx'),
        ),
    ]
