# Generated by Django 5.2.4 on 2026-05-26 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0004_atendimentohubsoft_ordemservicohubsoft_and_more'),
        ('vendas_web', '0048_leadprospecto_primeira_tentativa_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoInstalacaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], max_length=10)),
                ('data_instalacao', models.DateField()),
                ('status', models.CharField(choices=[('aguardando_sync', 'Aguardando sync Hubsoft'), ('processando', 'Processando'), ('agendado', 'Agendado'), ('erro', 'Erro')], db_index=True, default='aguardando_sync', max_length=20)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('id_tecnico', models.IntegerField(blank=True, null=True)),
                ('nome_tecnico', models.CharField(blank=True, default='', max_length=255)),
                ('id_agenda_os', models.IntegerField(blank=True, null=True)),
                ('id_cliente_servico', models.IntegerField(blank=True, null=True)),
                ('id_atendimento_matrix', models.IntegerField(blank=True, null=True)),
                ('id_os_matrix', models.IntegerField(blank=True, null=True)),
                ('dados_resposta_atendimento', models.JSONField(blank=True, default=dict)),
                ('dados_resposta_os', models.JSONField(blank=True, default=dict)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('ultimo_erro', models.TextField(blank=True, default='')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_processado', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_ia', to='vendas_web.leadprospecto')),
            ],
            options={
                'verbose_name': 'Agendamento Instalação (IA)',
                'verbose_name_plural': '📅 Agendamentos Instalação IA',
                'db_table': 'agendamentos_instalacao_ia',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['status', '-data_criacao'], name='agendamento_status_b7999a_idx'), models.Index(fields=['lead'], name='agendamento_lead_id_1be8d2_idx')],
            },
        ),
    ]
