# Generated by Django 5.2.4 on 2026-03-31 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        ('leads', '0001_initial'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrocliente',
            name='lead_gerado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.leadprospecto', verbose_name='Lead Gerado'),
        ),
        migrations.AddField(
            model_name='cadastrocliente',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='documentolead',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='leads.leadprospecto', verbose_name='Lead/Prospecto'),
        ),
        migrations.AddField(
            model_name='documentolead',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='opcaovencimento',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='cadastrocliente',
            name='vencimento_selecionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.opcaovencimento', verbose_name='Vencimento Selecionado'),
        ),
        migrations.AddField(
            model_name='planointernet',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='plano_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.planointernet', verbose_name='Plano Padrão'),
        ),
        migrations.AddField(
            model_name='cadastrocliente',
            name='plano_selecionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.planointernet', verbose_name='Plano Selecionado'),
        ),
        migrations.AddIndex(
            model_name='documentolead',
            index=models.Index(fields=['lead', 'tipo_documento'], name='documentos__lead_id_aef551_idx'),
        ),
        migrations.AddIndex(
            model_name='documentolead',
            index=models.Index(fields=['status'], name='documentos__status_a9c4b4_idx'),
        ),
        migrations.AddIndex(
            model_name='documentolead',
            index=models.Index(fields=['data_upload'], name='documentos__data_up_f54585_idx'),
        ),
        migrations.AddIndex(
            model_name='cadastrocliente',
            index=models.Index(fields=['cpf'], name='cadastros_c_cpf_badf25_idx'),
        ),
        migrations.AddIndex(
            model_name='cadastrocliente',
            index=models.Index(fields=['email'], name='cadastros_c_email_a4a4c4_idx'),
        ),
        migrations.AddIndex(
            model_name='cadastrocliente',
            index=models.Index(fields=['telefone'], name='cadastros_c_telefon_1c0911_idx'),
        ),
        migrations.AddIndex(
            model_name='cadastrocliente',
            index=models.Index(fields=['status'], name='cadastros_c_status_b04ca4_idx'),
        ),
        migrations.AddIndex(
            model_name='cadastrocliente',
            index=models.Index(fields=['data_inicio'], name='cadastros_c_data_in_d37939_idx'),
        ),
    ]
