# Generated by Django 5.2.4 on 2026-04-13 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_initial'),
        ('crm', '0005_produtoservico_itemoportunidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrocliente',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadastros', to='crm.produtoservico', verbose_name='Produto Selecionado'),
        ),
        migrations.AlterField(
            model_name='cadastrocliente',
            name='plano_selecionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.planointernet', verbose_name='Plano Selecionado (legado)'),
        ),
        migrations.AlterField(
            model_name='cadastrocliente',
            name='vencimento_selecionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.opcaovencimento', verbose_name='Vencimento Selecionado (legado)'),
        ),
    ]
