"""
Django settings for gerenciador_vendas project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Sem fallback. Em produção, falha se não definida.
# settings_local.py sobrescreve para desenvolvimento.
SECRET_KEY = os.environ.get('SECRET_KEY', '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # === DRF ===
    'rest_framework',
    'drf_spectacular',

    # === App legado (views, urls e admin ainda aqui) ===
    'vendas_web',

    # === Base ===
    'apps.sistema',
    'apps.notificacoes',
    'apps.dashboard',

    # === Módulo Comercial ===
    'apps.comercial.leads',
    'apps.comercial.atendimento',
    'apps.comercial.cadastro',
    'apps.comercial.viabilidade',
    'apps.comercial.crm',

    # === Módulo Marketing ===
    'apps.marketing.campanhas',

    # === API ===
    'apps.api',

    # === Integrações ===
    'apps.integracoes',

    # === Admin Aurora ===
    'apps.admin_aurora',

    # === Módulo CS ===
    'apps.cs.clube',
    'apps.cs.parceiros',
    'apps.cs.indicacoes',
    'apps.cs.carteirinha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.sistema.middleware.LoginRequiredMiddleware',
    'apps.sistema.middleware.TenantMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Configurações de Segurança
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False').lower() == 'true'
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False').lower() == 'true'

# Content Security Policy - Permitir Chart.js
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = (
    "'self'",
    "'unsafe-inline'",
    "'unsafe-eval'",
    "https://cdnjs.cloudflare.com",
    "https://code.jquery.com",
    "https://cdn.jsdelivr.net",  # Para Chart.js
)
CSP_STYLE_SRC = (
    "'self'",
    "'unsafe-inline'",
    "https://cdnjs.cloudflare.com",
)
CSP_IMG_SRC = (
    "'self'",
    "data:",
    "https:",
)
CSP_FONT_SRC = (
    "'self'",
    "https://cdnjs.cloudflare.com",
)

ROOT_URLCONF = 'gerenciador_vendas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.sistema.context_processors.empresa_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'gerenciador_vendas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'OPTIONS': {
            'options': '-c timezone=America/Sao_Paulo',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

# Configurações de fuso horário para garantir horário de Brasília
USE_L10N = True

# Força o uso do fuso horário local em todas as operações
os.environ['TZ'] = 'America/Sao_Paulo'

# Configurações adicionais para fuso horário
from django.utils import timezone
timezone.activate('America/Sao_Paulo')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard1/'
LOGOUT_REDIRECT_URL = '/'

# Disable APPEND_SLASH for API endpoints to avoid POST redirect issues
APPEND_SLASH = False

# ============================================================================
# DJANGO REST FRAMEWORK
# ============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'apps.sistema.authentication.APITokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',
        'user': '120/minute',
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS': ['v1'],
    'DATETIME_FORMAT': '%d/%m/%Y %H:%M:%S',
    'DATE_FORMAT': '%d/%m/%Y',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'AuroraISP API',
    'DESCRIPTION': 'API do hub de tecnologia para provedores de internet',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# ============================================================================
# CONFIGURAÇÕES DO SISTEMA DE NOTIFICAÇÕES
# ============================================================================

# N8N Integration
N8N_WEBHOOK_URL = os.environ.get('N8N_WEBHOOK_URL', 'https://n8n.aurora.consulteplus.com/webhook/notifications')
N8N_API_KEY = os.environ.get('N8N_API_KEY', '')

# Notification Settings
NOTIFICATION_MAX_RETRIES = 3
NOTIFICATION_RETRY_DELAYS = [2, 4, 8]  # minutos (exponential backoff)
NOTIFICATION_BATCH_SIZE = 100
NOTIFICATION_CLEANUP_DAYS = 30  # Limpar notificações antigas

# Site URL para links em notificações
SITE_URL = os.environ.get('SITE_URL', 'https://robovendas.megalinkpiaui.com.br')

# Email Templates
EMAIL_TEMPLATES = {
    'lead_novo': {
        'subject': 'Novo Lead Recebido - {{ lead.nome }}',
        'template': 'emails/lead_novo.html'
    },
    'venda_aprovada': {
        'subject': 'Venda Aprovada - {{ venda.valor }}',
        'template': 'emails/venda_aprovada.html'
    },
    'sistema_erro': {
        'subject': 'Erro no Sistema - {{ erro.tipo }}',
        'template': 'emails/sistema_erro.html'
    }
}
