# Generated by Django 5.2.4 on 2026-03-31 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clube', '0001_initial'),
        ('integracoes', '0002_alter_integracaoapi_access_token_and_more'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoNPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicidade_dias', models.IntegerField(default=90, verbose_name='Periodicidade (dias)')),
                ('canal_envio', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('ambos', 'Ambos')], default='whatsapp', max_length=20)),
                ('mensagem_template', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Configuração NPS',
                'verbose_name_plural': 'Configurações NPS',
            },
        ),
        migrations.CreateModel(
            name='PesquisaNPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(verbose_name='Nota (0-10)')),
                ('comentario', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('promotor', 'Promotor 9-10'), ('neutro', 'Neutro 7-8'), ('detrator', 'Detrator 0-6')], max_length=20)),
                ('canal_resposta', models.CharField(default='whatsapp', max_length=20)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('respondida', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integracoes.clientehubsoft')),
                ('membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clube.membroclube')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Pesquisa NPS',
                'verbose_name_plural': 'Pesquisas NPS',
                'ordering': ['-data_envio'],
            },
        ),
    ]
