# Generated by Django 5.2.4 on 2026-07-18 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automacao', '0013_checklist_itemchecklist_respostachecklist'),
        ('leads', '0014_alter_historicocontato_status'),
        ('sistema', '0015_alter_alertasistema_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoAtendimentoBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellphone', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('aguardando_resposta', 'Aguardando resposta do cliente'), ('aguardando_recontato', 'Aguardando recontato (timeout do cliente)'), ('transbordado', 'Transbordado para atendimento humano'), ('finalizado', 'Checklist completo')], default='em_andamento', max_length=20)),
                ('motivo_transbordo', models.CharField(blank=True, default='', max_length=60)),
                ('tentativas_item', models.PositiveSmallIntegerField(default=0)),
                ('tentativas_recontato', models.PositiveSmallIntegerField(default=0)),
                ('is_cliente_ativo', models.BooleanField(default=False)),
                ('ultima_interacao_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='automacao.checklist')),
                ('item_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='automacao.itemchecklist')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_bot', to='leads.leadprospecto')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Sessao do bot conversacional',
                'verbose_name_plural': 'Sessoes do bot conversacional',
                'db_table': 'atendimento_ia_sessao',
                'ordering': ['-ultima_interacao_em'],
            },
        ),
        migrations.CreateModel(
            name='TentativaResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(default=1)),
                ('resposta', models.TextField(blank=True, default='')),
                ('valida', models.BooleanField(null=True)),
                ('fonte_validacao', models.CharField(blank=True, default='', max_length=20)),
                ('motivo_erro', models.CharField(blank=True, default='', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='automacao.itemchecklist')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='atendimento_ia.sessaoatendimentobot')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Tentativa de resposta do bot',
                'verbose_name_plural': 'Tentativas de resposta do bot',
                'db_table': 'atendimento_ia_tentativa',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='sessaoatendimentobot',
            index=models.Index(fields=['tenant', 'lead'], name='atendimento_tenant__416451_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaoatendimentobot',
            index=models.Index(fields=['tenant', 'cellphone', 'status'], name='atendimento_tenant__f9f2d1_idx'),
        ),
    ]
