# Generated by Django 5.2.4 on 2026-03-31 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_seed_tags_qualificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraPipelineEstagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Descrição curta (ex: 'Serviço habilitado + doc validada')", max_length=150, verbose_name='Nome da Regra')),
                ('condicoes', models.JSONField(default=list, help_text='Lista de condições AND: [{tipo, campo, operador, valor}, ...]', verbose_name='Condições')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('prioridade', models.PositiveIntegerField(default=0, help_text='Menor valor = avaliada primeiro dentro do estágio', verbose_name='Prioridade')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('estagio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='crm.pipelineestagio', verbose_name='Estágio')),
            ],
            options={
                'verbose_name': 'Regra de Pipeline',
                'verbose_name_plural': 'Regras de Pipeline',
                'db_table': 'crm_regras_pipeline_estagio',
                'ordering': ['estagio__ordem', 'prioridade'],
            },
        ),
    ]
