# Generated by Django 5.2.4 on 2026-06-10 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_regrapipelineestagio'),
        ('vendas_web', '0058_alter_newservice_matrix_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidadevenda',
            name='new_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_crm', to='vendas_web.newservice', verbose_name='Novo Serviço (origem)'),
        ),
        migrations.AddField(
            model_name='oportunidadevenda',
            name='tipo',
            field=models.CharField(choices=[('aquisicao', 'Aquisição'), ('novo_servico', 'Novo Serviço'), ('upgrade', 'Upgrade de Plano'), ('atendimento', 'Atendimento')], db_index=True, default='aquisicao', max_length=20, verbose_name='Tipo / Pipeline'),
        ),
        migrations.AddField(
            model_name='oportunidadevenda',
            name='upgrade_plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_crm', to='vendas_web.upgradeplano', verbose_name='Upgrade (origem)'),
        ),
        migrations.AddField(
            model_name='pipelineestagio',
            name='pipeline_tipo',
            field=models.CharField(choices=[('aquisicao', 'Aquisição (lead novo → cliente)'), ('novo_servico', 'Novo Serviço (cliente existente)'), ('upgrade', 'Upgrade de Plano'), ('atendimento', 'Atendimento / Suporte')], db_index=True, default='aquisicao', max_length=20, verbose_name='Pipeline'),
        ),
        migrations.AlterField(
            model_name='oportunidadevenda',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades_crm', to='vendas_web.leadprospecto', verbose_name='Lead'),
        ),
    ]
