# Generated by Django 5.2.14 on 2026-07-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_seed_estagios_posvenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidadevenda',
            name='tipo',
            field=models.CharField(choices=[('aquisicao', 'Aquisição'), ('novo_servico', 'Novo Serviço'), ('upgrade', 'Upgrade de Plano'), ('atendimento', 'Atendimento'), ('indicacao', 'Indicação')], db_index=True, default='aquisicao', max_length=20, verbose_name='Tipo / Pipeline'),
        ),
        migrations.AlterField(
            model_name='pipelineestagio',
            name='pipeline_tipo',
            field=models.CharField(choices=[('aquisicao', 'Aquisição (lead novo → cliente)'), ('novo_servico', 'Novo Serviço (cliente existente)'), ('upgrade', 'Upgrade de Plano'), ('atendimento', 'Atendimento / Suporte'), ('indicacao', 'Indicação (operado por pessoas)')], db_index=True, default='aquisicao', max_length=20, verbose_name='Pipeline'),
        ),
    ]
