# Generated by Django 5.2.14 on 2026-07-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_seed_estagios_indicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_tipo', models.CharField(choices=[('aquisicao', 'Aquisição (lead novo → cliente)'), ('novo_servico', 'Novo Serviço (cliente existente)'), ('upgrade', 'Upgrade de Plano'), ('atendimento', 'Atendimento / Suporte'), ('indicacao', 'Indicação (operado por pessoas)')], max_length=20, unique=True, verbose_name='Pipeline')),
                ('mensagem', models.TextField(blank=True, default='', verbose_name='Mensagem inicial')),
                ('ativo', models.BooleanField(default=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mensagem de WhatsApp do Pipeline',
                'verbose_name_plural': 'Mensagens de WhatsApp dos Pipelines',
                'db_table': 'mensagem_pipeline',
            },
        ),
    ]
