# Generated by Django 5.2.14 on 2026-07-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_seed_mensagem_wifeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagempipeline',
            name='pipeline_tipo',
            field=models.CharField(choices=[('aquisicao', 'Aquisição (lead novo → cliente)'), ('novo_servico', 'Novo Serviço (cliente existente)'), ('upgrade', 'Upgrade de Plano'), ('atendimento', 'Atendimento / Suporte'), ('indicacao', 'Indicação (operado por pessoas)'), ('wifeed', 'Wifeed (portal WiFi)')], max_length=20, unique=True, verbose_name='Pipeline'),
        ),
    ]
