# Generated by Django 5.2.14 on 2026-07-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_mensagempipeline_pipeline_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WifeedFonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('local', 'Local (ponto WiFi)'), ('campanha', 'Campanha')], db_index=True, max_length=10, verbose_name='Tipo')),
                ('externo_id', models.BigIntegerField(verbose_name='ID no Wifeed')),
                ('nome', models.CharField(blank=True, default='', max_length=200, verbose_name='Nome')),
                ('ativo', models.BooleanField(db_index=True, default=False, help_text='Se marcado, o poller cria leads desta fonte.', verbose_name='Traz leads?')),
                ('ativo_wifeed', models.BooleanField(default=True, help_text='Espelho do isActive da API (informativo).', verbose_name='Ativa no Wifeed')),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização do catálogo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fonte Wifeed',
                'verbose_name_plural': '📶 Fontes Wifeed (locais/campanhas)',
                'db_table': 'crm_wifeed_fontes',
                'ordering': ['tipo', 'nome'],
                'unique_together': {('tipo', 'externo_id')},
            },
        ),
    ]
