# Generated by Django 5.2.14 on 2026-07-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_wifeedfonte'),
    ]

    operations = [
        migrations.CreateModel(
            name='WifeedConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo_minutos', models.PositiveIntegerField(default=15, help_text='De quantos em quantos minutos o poller busca leads novos.', verbose_name='Intervalo de sincronização (min)')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Wifeed',
                'verbose_name_plural': '📶 Configuração Wifeed',
                'db_table': 'crm_wifeed_config',
            },
        ),
    ]
