# Generated by Django 5.2.4 on 2026-03-29 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Provedor')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('modulo_comercial', models.BooleanField(default=True, verbose_name='Comercial ativo')),
                ('modulo_marketing', models.BooleanField(default=False, verbose_name='Marketing ativo')),
                ('modulo_cs', models.BooleanField(default=False, verbose_name='CS ativo')),
                ('plano_comercial', models.CharField(choices=[('starter', 'Starter'), ('start', 'Start'), ('pro', 'Pro')], default='starter', max_length=10, verbose_name='Plano Comercial')),
                ('plano_marketing', models.CharField(choices=[('starter', 'Starter'), ('start', 'Start'), ('pro', 'Pro')], default='starter', max_length=10, verbose_name='Plano Marketing')),
                ('plano_cs', models.CharField(choices=[('starter', 'Starter'), ('start', 'Start'), ('pro', 'Pro')], default='starter', max_length=10, verbose_name='Plano CS')),
                ('hubsoft_url', models.URLField(blank=True, null=True, verbose_name='URL HubSoft')),
                ('hubsoft_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token HubSoft')),
                ('em_trial', models.BooleanField(default=False, verbose_name='Em trial')),
                ('trial_inicio', models.DateField(blank=True, null=True, verbose_name='Início do trial')),
                ('trial_fim', models.DateField(blank=True, null=True, verbose_name='Fim do trial')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant (Provedor)',
                'verbose_name_plural': 'Tenants (Provedores)',
                'db_table': 'sistema_tenant',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuário',
                'db_table': 'sistema_perfil_usuario',
            },
        ),
    ]
