# Generated by Django 5.2.4 on 2026-03-31 13:51

import apps.sistema.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('modulo', models.CharField(choices=[('comercial', 'Comercial'), ('marketing', 'Marketing'), ('cs', 'CS')], max_length=20, verbose_name='Módulo')),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('start', 'Start'), ('pro', 'Pro')], max_length=10, verbose_name='Tier')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('preco_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mensalidade (R$)')),
                ('preco_transacional', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Transacional (R$)')),
                ('unidade_transacional', models.CharField(blank=True, default='', help_text='Ex: por venda, por contato/mês, por cliente ativo', max_length=100, verbose_name='Unidade Transacional')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('destaque', models.BooleanField(default=False, help_text='Destaca na página de preços', verbose_name='Plano destaque')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'db_table': 'sistema_plano',
                'ordering': ['modulo', 'ordem'],
                'unique_together': {('modulo', 'tier')},
            },
        ),
        migrations.CreateModel(
            name='FeaturePlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Feature')),
                ('slug', models.SlugField(help_text='Identificador usado no código para verificar acesso', verbose_name='Slug')),
                ('categoria', models.CharField(choices=[('core', 'Core'), ('crm', 'CRM'), ('automacao', 'Automação'), ('relatorios', 'Relatórios'), ('integracao', 'Integração'), ('suporte', 'Suporte')], default='core', max_length=20, verbose_name='Categoria')),
                ('descricao', models.CharField(blank=True, max_length=500, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='sistema.plano', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Feature do Plano',
                'verbose_name_plural': 'Features dos Planos',
                'db_table': 'sistema_feature_plano',
                'ordering': ['plano', 'categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Provedor')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('modulo_comercial', models.BooleanField(default=True, verbose_name='Comercial ativo')),
                ('modulo_marketing', models.BooleanField(default=False, verbose_name='Marketing ativo')),
                ('modulo_cs', models.BooleanField(default=False, verbose_name='CS ativo')),
                ('plano_comercial', models.CharField(choices=[('starter', 'Starter'), ('start', 'Start'), ('pro', 'Pro')], default='starter', max_length=10, verbose_name='Plano Comercial')),
                ('plano_marketing', models.CharField(choices=[('starter', 'Starter'), ('start', 'Start'), ('pro', 'Pro')], default='starter', max_length=10, verbose_name='Plano Marketing')),
                ('plano_cs', models.CharField(choices=[('starter', 'Starter'), ('start', 'Start'), ('pro', 'Pro')], default='starter', max_length=10, verbose_name='Plano CS')),
                ('hubsoft_url', models.URLField(blank=True, null=True, verbose_name='URL HubSoft')),
                ('hubsoft_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token HubSoft')),
                ('em_trial', models.BooleanField(default=False, verbose_name='Em trial')),
                ('trial_inicio', models.DateField(blank=True, null=True, verbose_name='Início do trial')),
                ('trial_fim', models.DateField(blank=True, null=True, verbose_name='Fim do trial')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('plano_comercial_ref', models.ForeignKey(blank=True, limit_choices_to={'ativo': True, 'modulo': 'comercial'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_comercial', to='sistema.plano', verbose_name='Plano Comercial (ref)')),
                ('plano_cs_ref', models.ForeignKey(blank=True, limit_choices_to={'ativo': True, 'modulo': 'cs'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_cs', to='sistema.plano', verbose_name='Plano CS (ref)')),
                ('plano_marketing_ref', models.ForeignKey(blank=True, limit_choices_to={'ativo': True, 'modulo': 'marketing'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_marketing', to='sistema.plano', verbose_name='Plano Marketing (ref)')),
            ],
            options={
                'verbose_name': 'Tenant (Provedor)',
                'verbose_name_plural': 'Tenants (Provedores)',
                'db_table': 'sistema_tenant',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuário',
                'db_table': 'sistema_perfil_usuario',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoRecontato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem de Recontato')),
                ('tempo_recontato', models.PositiveIntegerField(verbose_name='Tempo para Recontato')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_recontato', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Configuração de Recontato',
                'verbose_name_plural': 'Configurações de Recontato',
                'db_table': 'configuracoes_recontato',
                'ordering': ['-ativo'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='Provedor', max_length=100, verbose_name='Nome da Empresa')),
                ('logo_empresa', models.ImageField(blank=True, null=True, upload_to=apps.sistema.validators.tenant_upload_path, verbose_name='Logo da Empresa')),
                ('cor_primaria', models.CharField(default='#1F3D59', max_length=7, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor Primária')),
                ('cor_secundaria', models.CharField(default='#2c5aa0', max_length=7, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor Secundária')),
                ('ativo', models.BooleanField(default=True, verbose_name='Configuração Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_empresa', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Configuração da Empresa',
                'verbose_name_plural': 'Configurações da Empresa',
                'db_table': 'vendas_web_configuracaoempresa',
                'ordering': ['-ativo', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='StatusConfiguravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('lead_status_api', 'Lead: Status API'), ('prospecto_status', 'Prospecto: Status'), ('historico_status', 'Histórico: Status'), ('atendimento_status', 'Atendimento: Status'), ('fluxo_status', 'Fluxo: Status')], db_index=True, max_length=50)),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('rotulo', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_configuraveis', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Status Configurável',
                'verbose_name_plural': 'Status Configuráveis',
                'db_table': 'status_configuravel',
                'ordering': ['grupo', 'ordem', 'codigo'],
                'unique_together': {('tenant', 'grupo', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10, verbose_name='Nível')),
                ('modulo', models.CharField(max_length=100, verbose_name='Módulo')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('dados_extras', models.JSONField(blank=True, null=True, verbose_name='Dados Extras')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuário')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Log do Sistema',
                'verbose_name_plural': 'Logs do Sistema',
                'db_table': 'log_sistema',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['nivel'], name='log_sistema_nivel_570003_idx'), models.Index(fields=['data_criacao'], name='log_sistema_data_cr_aae550_idx'), models.Index(fields=['modulo'], name='log_sistema_modulo_a0fbdb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, verbose_name='Chave')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON'), ('decimal', 'Decimal')], default='string', max_length=20, verbose_name='Tipo')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_sistema', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
                'db_table': 'configuracao_sistema',
                'ordering': ['chave'],
                'unique_together': {('tenant', 'chave')},
            },
        ),
    ]
