# Generated by Django 5.2.4 on 2026-03-29 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('modulo', models.CharField(choices=[('comercial', 'Comercial'), ('marketing', 'Marketing'), ('cs', 'CS')], max_length=20, verbose_name='Módulo')),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('start', 'Start'), ('pro', 'Pro')], max_length=10, verbose_name='Tier')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('preco_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mensalidade (R$)')),
                ('preco_transacional', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Transacional (R$)')),
                ('unidade_transacional', models.CharField(blank=True, default='', help_text='Ex: por venda, por contato/mês, por cliente ativo', max_length=100, verbose_name='Unidade Transacional')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('destaque', models.BooleanField(default=False, help_text='Destaca na página de preços', verbose_name='Plano destaque')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'db_table': 'sistema_plano',
                'ordering': ['modulo', 'ordem'],
                'unique_together': {('modulo', 'tier')},
            },
        ),
        migrations.CreateModel(
            name='FeaturePlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Feature')),
                ('slug', models.SlugField(help_text='Identificador usado no código para verificar acesso', verbose_name='Slug')),
                ('categoria', models.CharField(choices=[('core', 'Core'), ('crm', 'CRM'), ('automacao', 'Automação'), ('relatorios', 'Relatórios'), ('integracao', 'Integração'), ('suporte', 'Suporte')], default='core', max_length=20, verbose_name='Categoria')),
                ('descricao', models.CharField(blank=True, max_length=500, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='sistema.plano', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Feature do Plano',
                'verbose_name_plural': 'Features dos Planos',
                'db_table': 'sistema_feature_plano',
                'ordering': ['plano', 'categoria', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='plano_comercial_ref',
            field=models.ForeignKey(blank=True, limit_choices_to={'ativo': True, 'modulo': 'comercial'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_comercial', to='sistema.plano', verbose_name='Plano Comercial (ref)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plano_cs_ref',
            field=models.ForeignKey(blank=True, limit_choices_to={'ativo': True, 'modulo': 'cs'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_cs', to='sistema.plano', verbose_name='Plano CS (ref)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plano_marketing_ref',
            field=models.ForeignKey(blank=True, limit_choices_to={'ativo': True, 'modulo': 'marketing'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_marketing', to='sistema.plano', verbose_name='Plano Marketing (ref)'),
        ),
    ]
