# Generated by Django 5.2.4 on 2026-04-05 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acesso_comercial', models.BooleanField(default=False, verbose_name='Acesso Comercial')),
                ('acesso_marketing', models.BooleanField(default=False, verbose_name='Acesso Marketing')),
                ('acesso_cs', models.BooleanField(default=False, verbose_name='Acesso CS')),
                ('acesso_inbox', models.BooleanField(default=False, verbose_name='Acesso Inbox')),
                ('acesso_configuracoes', models.BooleanField(default=False, verbose_name='Acesso Configurações')),
                ('papel_comercial', models.CharField(blank=True, choices=[('vendedor', 'Vendedor'), ('supervisor', 'Supervisor'), ('gerente', 'Gerente')], default='vendedor', max_length=20, verbose_name='Papel Comercial')),
                ('papel_marketing', models.CharField(blank=True, choices=[('analista', 'Analista'), ('gerente', 'Gerente')], default='analista', max_length=20, verbose_name='Papel Marketing')),
                ('papel_cs', models.CharField(blank=True, choices=[('operador', 'Operador'), ('gerente', 'Gerente')], default='operador', max_length=20, verbose_name='Papel CS')),
                ('papel_inbox', models.CharField(blank=True, choices=[('agente', 'Agente'), ('supervisor', 'Supervisor'), ('gerente', 'Gerente')], default='agente', max_length=20, verbose_name='Papel Inbox')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_usuarios', to='sistema.tenant', verbose_name='Tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Permissão de Usuário',
                'verbose_name_plural': 'Permissões de Usuários',
                'db_table': 'sistema_permissao_usuario',
            },
        ),
    ]
