# Generated by Django 5.2.4 on 2026-04-05 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_permissaousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissaousuario',
            name='acesso_comercial',
        ),
        migrations.RemoveField(
            model_name='permissaousuario',
            name='acesso_configuracoes',
        ),
        migrations.RemoveField(
            model_name='permissaousuario',
            name='acesso_cs',
        ),
        migrations.RemoveField(
            model_name='permissaousuario',
            name='acesso_inbox',
        ),
        migrations.RemoveField(
            model_name='permissaousuario',
            name='acesso_marketing',
        ),
        migrations.RemoveField(
            model_name='permissaousuario',
            name='papel_comercial',
        ),
        migrations.RemoveField(
            model_name='permissaousuario',
            name='papel_cs',
        ),
        migrations.RemoveField(
            model_name='permissaousuario',
            name='papel_inbox',
        ),
        migrations.RemoveField(
            model_name='permissaousuario',
            name='papel_marketing',
        ),
        migrations.CreateModel(
            name='PerfilPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Vendedor, Supervisor Comercial, Agente Suporte', max_length=100, verbose_name='Nome do Perfil')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('acesso_comercial', models.BooleanField(default=False, verbose_name='Acesso Comercial')),
                ('acesso_marketing', models.BooleanField(default=False, verbose_name='Acesso Marketing')),
                ('acesso_cs', models.BooleanField(default=False, verbose_name='Acesso CS')),
                ('acesso_inbox', models.BooleanField(default=False, verbose_name='Acesso Inbox')),
                ('acesso_configuracoes', models.BooleanField(default=False, verbose_name='Acesso Configurações')),
                ('papel_comercial', models.CharField(blank=True, choices=[('vendedor', 'Vendedor'), ('supervisor', 'Supervisor'), ('gerente', 'Gerente')], default='vendedor', max_length=20, verbose_name='Papel Comercial')),
                ('papel_marketing', models.CharField(blank=True, choices=[('analista', 'Analista'), ('gerente', 'Gerente')], default='analista', max_length=20, verbose_name='Papel Marketing')),
                ('papel_cs', models.CharField(blank=True, choices=[('operador', 'Operador'), ('gerente', 'Gerente')], default='operador', max_length=20, verbose_name='Papel CS')),
                ('papel_inbox', models.CharField(blank=True, choices=[('agente', 'Agente'), ('supervisor', 'Supervisor'), ('gerente', 'Gerente')], default='agente', max_length=20, verbose_name='Papel Inbox')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis_permissao', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Perfil de Permissão',
                'verbose_name_plural': 'Perfis de Permissão',
                'db_table': 'sistema_perfil_permissao',
                'ordering': ['nome'],
                'unique_together': {('tenant', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='permissaousuario',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='sistema.perfilpermissao', verbose_name='Perfil de Permissão'),
        ),
    ]
