# Generated by Django 5.2.4 on 2026-04-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_remove_permissaousuario_acesso_comercial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('comercial', 'Comercial'), ('marketing', 'Marketing'), ('cs', 'Customer Success'), ('inbox', 'Inbox / Suporte'), ('configuracoes', 'Configurações')], max_length=20, verbose_name='Módulo')),
                ('codigo', models.CharField(help_text='Identificador único (ex: comercial.ver_pipeline)', max_length=50, unique=True, verbose_name='Código')),
                ('nome', models.CharField(help_text='Nome amigável (ex: Ver Pipeline)', max_length=100, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Funcionalidade',
                'verbose_name_plural': 'Funcionalidades',
                'db_table': 'sistema_funcionalidade',
                'ordering': ['modulo', 'ordem'],
            },
        ),
        migrations.RemoveField(
            model_name='perfilpermissao',
            name='acesso_comercial',
        ),
        migrations.RemoveField(
            model_name='perfilpermissao',
            name='acesso_configuracoes',
        ),
        migrations.RemoveField(
            model_name='perfilpermissao',
            name='acesso_cs',
        ),
        migrations.RemoveField(
            model_name='perfilpermissao',
            name='acesso_inbox',
        ),
        migrations.RemoveField(
            model_name='perfilpermissao',
            name='acesso_marketing',
        ),
        migrations.RemoveField(
            model_name='perfilpermissao',
            name='papel_comercial',
        ),
        migrations.RemoveField(
            model_name='perfilpermissao',
            name='papel_cs',
        ),
        migrations.RemoveField(
            model_name='perfilpermissao',
            name='papel_inbox',
        ),
        migrations.RemoveField(
            model_name='perfilpermissao',
            name='papel_marketing',
        ),
        migrations.AddField(
            model_name='perfilpermissao',
            name='funcionalidades',
            field=models.ManyToManyField(blank=True, related_name='perfis', to='sistema.funcionalidade', verbose_name='Funcionalidades'),
        ),
    ]
