# Generated by Django 5.2.4 on 2026-04-07 02:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_funcionalidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsistema',
            name='acao',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Acao'),
        ),
        migrations.AddField(
            model_name='logsistema',
            name='categoria',
            field=models.CharField(blank=True, choices=[('auth', 'Autenticacao'), ('leads', 'Leads'), ('crm', 'CRM'), ('inbox', 'Inbox'), ('suporte', 'Suporte'), ('cs', 'Customer Success'), ('marketing', 'Marketing'), ('config', 'Configuracoes'), ('admin', 'Admin Aurora'), ('integracao', 'Integracoes'), ('sistema', 'Sistema')], db_index=True, default='', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='logsistema',
            name='entidade',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Entidade'),
        ),
        migrations.AddField(
            model_name='logsistema',
            name='entidade_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID da Entidade'),
        ),
        migrations.AlterField(
            model_name='logsistema',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criacao'),
        ),
        migrations.AlterField(
            model_name='logsistema',
            name='modulo',
            field=models.CharField(max_length=100, verbose_name='Modulo'),
        ),
        migrations.AlterField(
            model_name='logsistema',
            name='nivel',
            field=models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='logsistema',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='logsistema',
            index=models.Index(fields=['categoria'], name='log_sistema_categor_f59555_idx'),
        ),
        migrations.AddIndex(
            model_name='logsistema',
            index=models.Index(fields=['categoria', 'acao'], name='log_sistema_categor_26d003_idx'),
        ),
        migrations.AddIndex(
            model_name='logsistema',
            index=models.Index(fields=['entidade', 'entidade_id'], name='log_sistema_entidad_4b8a61_idx'),
        ),
    ]
