# Generated by Django 5.2.4 on 2026-04-10 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0005_integracaoapi_api_token'),
        ('sistema', '0005_logsistema_acao_logsistema_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoempresa',
            name='enviar_leads_integracao',
            field=models.BooleanField(default=False, help_text='Envia leads automaticamente para a integração selecionada ao cadastrar', verbose_name='Enviar leads para integração'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='integracao_leads',
            field=models.ForeignKey(blank=True, help_text='Integração que recebe os leads (ex: HubSoft)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_empresa_leads', to='integracoes.integracaoapi', verbose_name='Integração para leads'),
        ),
    ]
