# Generated by Django 5.2.4 on 2026-04-11 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0005_integracaoapi_api_token'),
        ('sistema', '0006_configuracaoempresa_enviar_leads_integracao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoRecuperacaoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, verbose_name='Codigo')),
                ('token', models.CharField(blank=True, default='', max_length=64, verbose_name='Token (para email)')),
                ('metodo', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10, verbose_name='Metodo')),
                ('tentativas', models.PositiveIntegerField(default=0, verbose_name='Tentativas')),
                ('usado', models.BooleanField(default=False, verbose_name='Usado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField(verbose_name='Expira em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_recuperacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Codigo de Recuperacao',
                'verbose_name_plural': 'Codigos de Recuperacao',
                'db_table': 'sistema_codigo_recuperacao_senha',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoRecuperacaoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_ativo', models.BooleanField(default=False, verbose_name='Recuperacao por Email')),
                ('smtp_host', models.CharField(blank=True, default='', max_length=200, verbose_name='SMTP Host')),
                ('smtp_porta', models.PositiveIntegerField(default=587, verbose_name='SMTP Porta')),
                ('smtp_usuario', models.CharField(blank=True, default='', max_length=200, verbose_name='SMTP Usuario')),
                ('smtp_senha', models.CharField(blank=True, default='', max_length=200, verbose_name='SMTP Senha')),
                ('smtp_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('email_remetente', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email Remetente')),
                ('whatsapp_ativo', models.BooleanField(default=False, verbose_name='Recuperacao por WhatsApp')),
                ('codigo_expiracao_minutos', models.PositiveIntegerField(default=5, verbose_name='Expiracao do codigo (min)')),
                ('max_tentativas', models.PositiveIntegerField(default=3, verbose_name='Max tentativas por codigo')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('whatsapp_integracao', models.ForeignKey(blank=True, help_text='Integracao usada para enviar codigo via WhatsApp', null=True, on_delete=django.db.models.deletion.SET_NULL, to='integracoes.integracaoapi', verbose_name='Integracao WhatsApp (Uazapi)')),
            ],
            options={
                'verbose_name': 'Config Recuperacao de Senha',
                'verbose_name_plural': 'Config Recuperacao de Senha',
                'db_table': 'sistema_config_recuperacao_senha',
            },
        ),
    ]
