# Generated by Django 5.2.4 on 2026-04-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_codigorecuperacaosenha_configuracaorecuperacaosenha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsistema',
            name='categoria',
            field=models.CharField(blank=True, choices=[('auth', 'Autenticacao'), ('leads', 'Leads'), ('crm', 'CRM'), ('inbox', 'Inbox'), ('suporte', 'Suporte'), ('cs', 'Customer Success'), ('marketing', 'Marketing'), ('config', 'Configuracoes'), ('admin', 'Admin Hubtrix'), ('integracao', 'Integracoes'), ('sistema', 'Sistema')], db_index=True, default='', max_length=20, verbose_name='Categoria'),
        ),
    ]
