# Generated by Django 5.2.4 on 2026-04-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_alter_logsistema_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='senha_temporaria',
            field=models.BooleanField(default=False, help_text='Se True, o usuário será forçado a trocar a senha no próximo login', verbose_name='Senha temporária'),
        ),
    ]
