# Generated by Django 5.2.4 on 2026-04-29 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_perfilusuario_senha_temporaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='modulo_workspace',
            field=models.BooleanField(default=False, verbose_name='Workspace ativo'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plano_workspace',
            field=models.CharField(choices=[('starter', 'Starter'), ('start', 'Start'), ('pro', 'Pro')], default='starter', max_length=10, verbose_name='Plano Workspace'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plano_workspace_ref',
            field=models.ForeignKey(blank=True, limit_choices_to={'ativo': True, 'modulo': 'workspace'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_workspace', to='sistema.plano', verbose_name='Plano Workspace (ref)'),
        ),
        migrations.AlterField(
            model_name='funcionalidade',
            name='modulo',
            field=models.CharField(choices=[('comercial', 'Comercial'), ('marketing', 'Marketing'), ('cs', 'Customer Success'), ('inbox', 'Inbox / Suporte'), ('configuracoes', 'Configurações'), ('workspace', 'Workspace')], max_length=20, verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='logsistema',
            name='categoria',
            field=models.CharField(blank=True, choices=[('auth', 'Autenticacao'), ('leads', 'Leads'), ('crm', 'CRM'), ('inbox', 'Inbox'), ('suporte', 'Suporte'), ('cs', 'Customer Success'), ('marketing', 'Marketing'), ('config', 'Configuracoes'), ('admin', 'Admin Hubtrix'), ('integracao', 'Integracoes'), ('sistema', 'Sistema'), ('workspace', 'Workspace')], db_index=True, default='', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='modulo',
            field=models.CharField(choices=[('comercial', 'Comercial'), ('marketing', 'Marketing'), ('cs', 'CS'), ('workspace', 'Workspace')], max_length=20, verbose_name='Módulo'),
        ),
    ]
