# Generated by Django 5.2.4 on 2026-06-03 06:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_tenant_modulo_workspace_tenant_plano_workspace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_destino', models.CharField(default='53981521653', help_text='Numero do operador que recebe alertas (formato 55XX...)', max_length=20, verbose_name='Telefone WhatsApp destino')),
                ('janela_dedup_minutos', models.PositiveIntegerField(default=5, help_text='Mesma chave nao reenvia WhatsApp dentro desta janela', verbose_name='Janela dedup (minutos)')),
                ('enviar_whatsapp', models.BooleanField(default=True, help_text='Se desligado, alertas sao apenas logados no admin', verbose_name='Enviar via WhatsApp')),
                ('tipos_ativos', models.JSONField(blank=True, default=list, help_text='Lista de tipos que disparam WhatsApp. Vazio = todos.', verbose_name='Tipos de alerta ativos')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracao de alertas',
                'verbose_name_plural': 'Configuracao de alertas',
                'db_table': 'sistema_alerta_config',
            },
        ),
        migrations.CreateModel(
            name='AlertaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cron_falhou', 'CronJob falhou'), ('cron_lag', 'CronJob nao rodou no schedule'), ('webhook_5xx', 'Webhook N8N retornou 5xx'), ('hubsoft_erro', 'HubSoft API com erros consecutivos'), ('catalogo_mudou', 'Catalogo HubSoft mudou (vendedor/origem sumiu)'), ('lead_travado', 'Lead em status erro ha > 1h'), ('uazapi_caiu', 'uazapi sem token / instancia caiu'), ('bot_falhou', 'Bot Selenium falhou'), ('erro_python', 'Erro Python critico'), ('outro', 'Outro')], db_index=True, max_length=30)),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo (vai no WhatsApp)')),
                ('mensagem', models.TextField(verbose_name='Mensagem detalhada')),
                ('dados_extras', models.JSONField(blank=True, default=dict, verbose_name='Dados estruturados (entidade_id, etc)')),
                ('dedup_key', models.CharField(db_index=True, help_text='Mesma chave dentro da janela nao reenvia WhatsApp', max_length=200, verbose_name='Chave de deduplicacao (5min)')),
                ('criado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='Quando saiu por WhatsApp')),
                ('suprimido', models.BooleanField(default=False, help_text='Marcado True quando uma chave dedup repete dentro da janela', verbose_name='Suprimido por dedup')),
                ('erro_envio', models.TextField(blank=True, default='', verbose_name='Erro ao enviar (se falhou)')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_disparados', to='sistema.tenant', verbose_name='Tenant que disparou (contexto)')),
            ],
            options={
                'verbose_name': 'Alerta do sistema',
                'verbose_name_plural': 'Alertas do sistema',
                'db_table': 'sistema_alerta',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['dedup_key', 'criado_em'], name='sistema_ale_dedup_k_9663df_idx'), models.Index(fields=['tipo', 'criado_em'], name='sistema_ale_tipo_3aea94_idx')],
            },
        ),
    ]
