# Generated by Django 5.2.4 on 2026-06-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_alertaconfig_alertasistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='login_matrix',
            field=models.CharField(blank=True, db_index=True, help_text='Login do agente no Matrix Brasil (ex: "joyce", "AnaP"). Usado pelo cron de sync pra atribuir oportunidade ao mesmo vendedor que pegou o atendimento la.', max_length=80, null=True, verbose_name='Login Matrix Brasil'),
        ),
    ]
