# Generated by Django 5.2.4 on 2026-06-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_perfilusuario_login_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='id_vendedor_hubsoft',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID do vendedor correspondente no HubSoft. Usado pelo mapper de prospecto pra atribuir vendas a vendedora correta no ERP. Achado via cache.vendedores da IntegracaoAPI HubSoft.', null=True, verbose_name='ID Vendedor HubSoft'),
        ),
    ]
