# Generated by Django 5.2.4 on 2026-07-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0013_perfilusuario_id_vendedor_hubsoft'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='cod_talk',
            field=models.IntegerField(blank=True, db_index=True, help_text='Codigo (cod_agente) do vendedor na plataforma Talk (matrixdobrasil.ai). Usado pelo cron de sync pra atribuir oportunidade Talk ao agente que atendeu a chamada. Descobrir via GET /ws/rest/restGerenciaAgente.php?modulo=listaagentes.', null=True, verbose_name='Codigo Agente Talk'),
        ),
    ]
