# Generated by Django 5.2.4 on 2026-07-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0014_perfilusuario_cod_talk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertasistema',
            name='tipo',
            field=models.CharField(choices=[('cron_falhou', 'CronJob falhou'), ('cron_lag', 'CronJob nao rodou no schedule'), ('webhook_5xx', 'Webhook N8N retornou 5xx'), ('hubsoft_erro', 'HubSoft API com erros consecutivos'), ('catalogo_mudou', 'Catalogo HubSoft mudou (vendedor/origem sumiu)'), ('lead_travado', 'Lead em status erro ha > 1h'), ('uazapi_caiu', 'uazapi sem token / instancia caiu'), ('bot_falhou', 'Bot Selenium falhou'), ('erro_python', 'Erro Python critico'), ('agente_sem_match', 'Ligacao atendida mas sem vendedora atribuida'), ('outro', 'Outro')], db_index=True, max_length=30),
        ),
    ]
