# Generated by Django 5.2.4 on 2026-07-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0015_alter_alertasistema_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsistema',
            name='categoria',
            field=models.CharField(blank=True, choices=[('auth', 'Autenticacao'), ('leads', 'Leads'), ('crm', 'CRM'), ('inbox', 'Inbox'), ('suporte', 'Suporte'), ('cs', 'Customer Success'), ('marketing', 'Marketing'), ('config', 'Configuracoes'), ('admin', 'Admin Hubtrix'), ('integracao', 'Integracoes'), ('sistema', 'Sistema'), ('workspace', 'Workspace'), ('people', 'People (RH)')], db_index=True, default='', max_length=20, verbose_name='Categoria'),
        ),
    ]
