# Generated by Django 5.2.4 on 2026-07-20 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0016_alter_logsistema_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='modulo_people',
            field=models.BooleanField(default=False, verbose_name='People ativo'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plano_people',
            field=models.CharField(choices=[('starter', 'Starter'), ('start', 'Start'), ('pro', 'Pro')], default='starter', max_length=10, verbose_name='Plano People'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plano_people_ref',
            field=models.ForeignKey(blank=True, limit_choices_to={'ativo': True, 'modulo': 'people'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_people', to='sistema.plano', verbose_name='Plano People (ref)'),
        ),
        migrations.AlterField(
            model_name='funcionalidade',
            name='modulo',
            field=models.CharField(choices=[('comercial', 'Comercial'), ('marketing', 'Marketing'), ('cs', 'Customer Success'), ('inbox', 'Inbox / Suporte'), ('configuracoes', 'Configurações'), ('workspace', 'Workspace'), ('people', 'People (RH)')], max_length=20, verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='modulo',
            field=models.CharField(choices=[('comercial', 'Comercial'), ('marketing', 'Marketing'), ('cs', 'CS'), ('workspace', 'Workspace'), ('people', 'People')], max_length=20, verbose_name='Módulo'),
        ),
    ]
