# Generated by Django 5.2.4 on 2026-04-07 02:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automacoes', '0004_alter_regraautomacao_evento'),
        ('leads', '0002_leadprospecto_dados_custom_campocustomizado'),
        ('sistema', '0005_logsistema_acao_logsistema_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(default='fas fa-folder', help_text='Classe FontAwesome (ex: fas fa-envelope)', max_length=50)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Categoria de Template',
                'verbose_name_plural': 'Categorias de Templates',
                'db_table': 'marketing_categoria_template',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TemplateEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome interno do template', max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional')),
                ('assunto', models.CharField(blank=True, help_text='Assunto do email. Suporta variáveis: {{lead.nome}}', max_length=300)),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Configurações globais do email (largura, cores, fonte)')),
                ('blocos_json', models.JSONField(blank=True, default=list, help_text='Lista de blocos do editor visual')),
                ('html_compilado', models.TextField(blank=True, help_text='HTML renderizado a partir dos blocos (gerado automaticamente)')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativo', 'Ativo'), ('arquivado', 'Arquivado')], db_index=True, default='rascunho', max_length=20)),
                ('eh_modelo_base', models.BooleanField(default=False, help_text='Templates base do sistema (disponíveis para todos os tenants)')),
                ('thumbnail', models.ImageField(blank=True, help_text='Preview em miniatura do template', null=True, upload_to='emails/thumbnails/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='emails.categoriatemplate')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_email_criados', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Template de Email',
                'verbose_name_plural': 'Templates de Email',
                'db_table': 'marketing_template_email',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='EnvioEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destino', models.EmailField(max_length=254)),
                ('assunto_renderizado', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('aberto', 'Aberto'), ('clicado', 'Clicado'), ('erro', 'Erro'), ('bounce', 'Bounce')], db_index=True, default='enviado', max_length=20)),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('aberto_em', models.DateTimeField(blank=True, null=True)),
                ('clicado_em', models.DateTimeField(blank=True, null=True)),
                ('erro_detalhe', models.TextField(blank=True)),
                ('automacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_enviados', to='automacoes.regraautomacao')),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_recebidos', to='leads.leadprospecto')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='emails.templateemail')),
            ],
            options={
                'verbose_name': 'Envio de Email',
                'verbose_name_plural': 'Envios de Email',
                'db_table': 'marketing_envio_email',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='templateemail',
            index=models.Index(fields=['status'], name='marketing_t_status_51962b_idx'),
        ),
        migrations.AddIndex(
            model_name='templateemail',
            index=models.Index(fields=['eh_modelo_base'], name='marketing_t_eh_mode_030c69_idx'),
        ),
        migrations.AddIndex(
            model_name='envioemail',
            index=models.Index(fields=['tracking_id'], name='marketing_e_trackin_0411a2_idx'),
        ),
        migrations.AddIndex(
            model_name='envioemail',
            index=models.Index(fields=['status'], name='marketing_e_status_7c3989_idx'),
        ),
    ]
