# Generated by Django 5.2.4 on 2026-04-29 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
        ('sistema', '0010_tenant_modulo_workspace_tenant_plano_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envioemail',
            name='bounce_type',
            field=models.CharField(blank=True, help_text='hard / soft / undetermined (do provedor)', max_length=50),
        ),
        migrations.AddField(
            model_name='envioemail',
            name='complaint_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='envioemail',
            name='entregue_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envioemail',
            name='resend_message_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID retornado pelo Resend (correlaciona webhooks)', max_length=200),
        ),
        migrations.AlterField(
            model_name='envioemail',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('aberto', 'Aberto'), ('clicado', 'Clicado'), ('erro', 'Erro'), ('bounce', 'Bounce'), ('complained', 'Marcado como spam')], db_index=True, default='enviado', max_length=20),
        ),
        migrations.CreateModel(
            name='DominioRemetente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(help_text='Ex: meuprovedor.com.br', max_length=255)),
                ('nome_amigavel', models.CharField(blank=True, help_text='Apelido pra organizar quando o tenant tem varios dominios', max_length=100)),
                ('resend_domain_id', models.CharField(blank=True, db_index=True, help_text='ID retornado pela API Resend ao criar o dominio', max_length=100)),
                ('status', models.CharField(choices=[('pendente_dns', 'Pendente — adicionar DNS'), ('validando', 'Validando DNS'), ('verificado', 'Verificado'), ('falhou', 'Falhou'), ('desabilitado', 'Desabilitado')], db_index=True, default='pendente_dns', max_length=20)),
                ('registros_dns', models.JSONField(blank=True, default=list, help_text='3 registros DNS (SPF/DKIM/DMARC) que o tenant precisa adicionar')),
                ('validado_em', models.DateTimeField(blank=True, null=True)),
                ('falha_motivo', models.TextField(blank=True)),
                ('ultima_verificacao', models.DateTimeField(blank=True, null=True)),
                ('capturar_bounces', models.BooleanField(default=True, help_text='Salvar info de bounce nos envios deste dominio')),
                ('capturar_complaints', models.BooleanField(default=True, help_text='Salvar info de complaint (spam) nos envios deste dominio')),
                ('auto_remover_lista', models.BooleanField(default=False, help_text='Remover automaticamente da lista quando bate bounce/complaint')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Dominio de Remetente',
                'verbose_name_plural': 'Dominios de Remetente',
                'db_table': 'marketing_dominio_remetente',
                'ordering': ['-criado_em'],
                'unique_together': {('tenant', 'dominio')},
            },
        ),
        migrations.CreateModel(
            name='RemetenteEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_part', models.CharField(help_text='Parte antes do @ (ex: atendimento, marketing, noreply)', max_length=64)),
                ('nome_exibicao', models.CharField(help_text='Nome que aparece como remetente (ex: Atendimento Hubtrix)', max_length=200)),
                ('reply_to', models.EmailField(blank=True, help_text='Endereco pra onde respostas vao. Vazio = ignorar.', max_length=254)),
                ('padrao', models.BooleanField(default=False, help_text='Remetente padrao do tenant (apenas 1 ativo)')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remetentes', to='emails.dominioremetente')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Remetente de Email',
                'verbose_name_plural': 'Remetentes de Email',
                'db_table': 'marketing_remetente_email',
                'ordering': ['dominio', 'local_part'],
                'unique_together': {('dominio', 'local_part')},
            },
        ),
        migrations.AddField(
            model_name='envioemail',
            name='remetente',
            field=models.ForeignKey(blank=True, help_text='Endereco usado pra enviar (vazio = remetente padrao do tenant na epoca)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='emails.remetenteemail'),
        ),
    ]
