# Generated by Django 5.2.4 on 2026-06-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_envioemail_bounce_type_envioemail_complaint_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envioemail',
            name='automacao',
            field=models.IntegerField(blank=True, db_column='automacao_id', null=True),
        ),
    ]
