# Generated by Django 5.2.4 on 2026-07-13 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relatorios', '0003_atribuir_setores_iniciais'),
        ('sistema', '0014_perfilusuario_cod_talk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descricao')),
                ('compartilhado', models.BooleanField(default=False, help_text='Se True, todos do tenant veem (so admin marca).', verbose_name='Compartilhado')),
                ('tema', models.JSONField(blank=True, default=dict, help_text='JSON: {cor_fundo, cor_texto, fonte, cor_primaria, logo_url}.', verbose_name='Tema')),
                ('config', models.JSONField(blank=True, default=dict, help_text='JSON: {canvas:{w,h,cols,rows}} e afins.', verbose_name='Config')),
                ('snapshot_em', models.DateTimeField(blank=True, help_text='Momento do ultimo "Congelar" (dados dos blocos widget).', null=True, verbose_name='Snapshot congelado em')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Deck',
                'verbose_name_plural': 'Decks',
                'db_table': 'decks_deck',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordem')),
                ('titulo', models.CharField(blank=True, default='', max_length=120, verbose_name='Titulo')),
                ('fundo', models.JSONField(blank=True, default=dict, help_text='Override por slide: {cor, imagem_url}.', verbose_name='Fundo')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas do apresentador')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='decks.deck', verbose_name='Deck')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'db_table': 'decks_slide',
                'ordering': ['deck', 'ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SlideBloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('widget', 'Widget (grafico/KPI)'), ('texto', 'Texto'), ('kpi', 'KPI em destaque'), ('imagem', 'Imagem'), ('titulo_secao', 'Titulo de secao')], default='texto', max_length=20, verbose_name='Tipo')),
                ('dados_snapshot', models.JSONField(blank=True, default=dict, help_text='{labels, series, total, meta} do builder no momento do congelar.', verbose_name='Dados congelados')),
                ('conteudo', models.JSONField(blank=True, default=dict, help_text='Por tipo: texto={html,align}, kpi={label,valor,...}, imagem={url,fit}, titulo_secao={texto,subtitulo}, widget={titulo_override,viz_override,dias,fonte}.', verbose_name='Conteudo')),
                ('layout', models.JSONField(blank=True, default=dict, help_text='Posicao na grade do slide: {x,y,w,h} (mesma forma de Widget.layout).', verbose_name='Layout')),
                ('estilo', models.JSONField(blank=True, default=dict, help_text='{cor_fundo, cor_texto, radius, sombra, align}.', verbose_name='Estilo')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='decks.slide', verbose_name='Slide')),
                ('widget', models.ForeignKey(blank=True, help_text='So pra tipo=widget. SET_NULL: se o widget for excluido, o bloco sobrevive e ainda renderiza o dados_snapshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocos_deck', to='relatorios.widget', verbose_name='Widget')),
            ],
            options={
                'verbose_name': 'Bloco de slide',
                'verbose_name_plural': 'Blocos de slide',
                'db_table': 'decks_slidebloco',
                'ordering': ['slide', 'ordem', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['tenant', 'compartilhado'], name='decks_deck_tenant__918027_idx'),
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['tenant', 'criado_por'], name='decks_deck_tenant__f8b5ab_idx'),
        ),
    ]
