# Generated by Django 5.2.4 on 2026-05-27 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_validador', '0017_coleta_tipo_residencia'),
        ('vendas_web', '0052_imagem_status_aprovado_ia'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogInteracaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('endpoint', models.CharField(choices=[('validar', 'validar'), ('proximo-passo', 'proximo-passo'), ('validar-imagem', 'validar-imagem')], db_index=True, max_length=40)),
                ('cellphone', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('question_id', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('answer', models.TextField(blank=True, default='', help_text='Resposta do cliente (em /validar)')),
                ('mensagem_resposta', models.TextField(blank=True, default='', help_text='Mensagem composta pelo engine pro cliente')),
                ('payload_in', models.JSONField(blank=True, default=dict)),
                ('payload_out', models.JSONField(blank=True, default=dict)),
                ('duracao_ms', models.IntegerField(blank=True, null=True)),
                ('valido', models.BooleanField(blank=True, null=True)),
                ('transbordou', models.BooleanField(default=False)),
                ('motivo', models.CharField(blank=True, default='', max_length=200)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacoes_ia', to='vendas_web.leadprospecto')),
            ],
            options={
                'verbose_name': 'Log Interação IA',
                'verbose_name_plural': '🤖 Logs de Interação IA',
                'db_table': 'logs_interacao_ia',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['cellphone', '-timestamp'], name='logs_intera_cellpho_a89d50_idx'), models.Index(fields=['lead', '-timestamp'], name='logs_intera_lead_id_511120_idx'), models.Index(fields=['endpoint', '-timestamp'], name='logs_intera_endpoin_b57b16_idx')],
            },
        ),
    ]
