# Generated by Django 5.2.4 on 2026-05-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_validador', '0018_log_interacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginteracaoia',
            name='endpoint',
            field=models.CharField(choices=[('validar', 'validar'), ('proximo-passo', 'proximo-passo'), ('validar-imagem', 'validar-imagem'), ('new_service', 'new_service')], db_index=True, max_length=40),
        ),
    ]
