# Generated by Django 5.2.4 on 2026-06-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_validador', '0024_retomar_ou_recomecar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginteracaoia',
            name='endpoint',
            field=models.CharField(choices=[('validar', 'validar'), ('proximo-passo', 'proximo-passo'), ('validar-imagem', 'validar-imagem'), ('new_service', 'new_service'), ('conv-turno', 'conv-turno')], db_index=True, max_length=40),
        ),
    ]
