# Generated by Django 5.2.14 on 2026-07-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_validador', '0025_log_conv_turno_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemRobo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(help_text='Identificador do ponto do fluxo (não editar)', max_length=60, unique=True)),
                ('grupo', models.CharField(choices=[('boas_vindas_coleta', 'Boas-vindas & coleta de dados'), ('confirmacoes_erros', 'Confirmações & erros'), ('menu_cliente', 'Menu do cliente'), ('recontato', 'Recontato (tempo de espera)'), ('retomada', 'Retomada de atendimento'), ('transbordo_encerramento', 'Transbordo & encerramento')], default='boas_vindas_coleta', max_length=40)),
                ('rotulo', models.CharField(max_length=140, verbose_name='Rótulo')),
                ('descricao', models.CharField(blank=True, default='', max_length=255, verbose_name='Quando é enviada')),
                ('placeholders', models.CharField(blank=True, default='', help_text='Placeholders disponíveis, separados por vírgula', max_length=200)),
                ('texto', models.TextField(blank=True, default='', verbose_name='Mensagem')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mensagem do Robô',
                'verbose_name_plural': '💬 Mensagens do Robô',
                'db_table': 'mensagens_robo',
                'ordering': ['grupo', 'ordem', 'chave'],
            },
        ),
    ]
