# Generated by Django 5.2.14 on 2026-07-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_validador', '0026_mensagemrobo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemrobo',
            name='texto_padrao',
            field=models.TextField(blank=True, default='', help_text='Texto original de fábrica — usado pelo botão "Restaurar padrão".', verbose_name='Texto padrão'),
        ),
        migrations.AlterField(
            model_name='mensagemrobo',
            name='grupo',
            field=models.CharField(choices=[('inicio', 'Início & boas-vindas'), ('boas_vindas_coleta', 'Coleta de dados (perguntas)'), ('endereco', 'Endereço'), ('planos', 'Planos & vitrine'), ('documentos', 'Documentos (fotos)'), ('agendamento', 'Agendamento da instalação'), ('confirmacoes_erros', 'Confirmações & erros'), ('menu_cliente', 'Menu do cliente'), ('recontato', 'Recontato (tempo de espera)'), ('retomada', 'Retomada de atendimento'), ('transbordo_encerramento', 'Transbordo & encerramento')], default='boas_vindas_coleta', max_length=40),
        ),
    ]
