# Generated by Django 5.2.4 on 2026-04-02 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoRegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('enviar_whatsapp', 'Enviar WhatsApp'), ('enviar_email', 'Enviar E-mail'), ('notificacao_sistema', 'Notificação no sistema'), ('criar_tarefa', 'Criar tarefa no CRM'), ('mover_estagio', 'Mover estágio no pipeline'), ('atribuir_responsavel', 'Atribuir responsável'), ('dar_pontos', 'Dar pontos no Clube'), ('webhook', 'Chamar webhook externo')], max_length=50)),
                ('configuracao', models.TextField(blank=True, help_text='Configuração da ação (template de mensagem, dados do webhook, etc.)')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('delay_ativo', models.BooleanField(default=False)),
                ('delay_valor', models.PositiveIntegerField(default=0)),
                ('delay_unidade', models.CharField(choices=[('minutos', 'Minutos'), ('horas', 'Horas'), ('dias', 'Dias')], default='minutos', max_length=10)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'db_table': 'automacoes_acaoregra',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='RegraAutomacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('evento', models.CharField(choices=[('lead_criado', 'Novo lead criado'), ('lead_qualificado', 'Lead qualificado (score mínimo)'), ('lead_sem_contato', 'Lead sem contato há X dias'), ('oportunidade_movida', 'Oportunidade movida de estágio'), ('venda_aprovada', 'Venda aprovada'), ('cliente_aniversario', 'Aniversário de cliente'), ('indicacao_convertida', 'Indicação convertida'), ('tarefa_vencida', 'Tarefa CRM vencida'), ('docs_validados', 'Documentos validados')], max_length=50)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('total_execucoes', models.PositiveIntegerField(default=0)),
                ('total_sucesso', models.PositiveIntegerField(default=0)),
                ('total_erro', models.PositiveIntegerField(default=0)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Regra de Automação',
                'verbose_name_plural': 'Regras de Automação',
                'db_table': 'automacoes_regraautomacao',
                'ordering': ['-ativa', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='LogExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro'), ('agendado', 'Agendado'), ('cancelado', 'Cancelado')], default='sucesso', max_length=20)),
                ('evento_dados', models.JSONField(blank=True, default=dict, help_text='Dados do evento que disparou a regra')),
                ('resultado', models.TextField(blank=True, help_text='Detalhes do resultado ou erro')),
                ('data_execucao', models.DateTimeField(auto_now_add=True)),
                ('data_agendada', models.DateTimeField(blank=True, help_text='Para ações com delay', null=True)),
                ('acao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='automacoes.acaoregra')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automacoes.regraautomacao')),
            ],
            options={
                'verbose_name': 'Log de Execução',
                'verbose_name_plural': 'Logs de Execução',
                'db_table': 'automacoes_logexecucao',
                'ordering': ['-data_execucao'],
            },
        ),
        migrations.CreateModel(
            name='CondicaoRegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(help_text='Ex: lead.origem, lead.score, crm.estagio', max_length=100)),
                ('operador', models.CharField(choices=[('igual', 'é igual a'), ('diferente', 'é diferente de'), ('contem', 'contém'), ('maior', 'é maior que'), ('menor', 'é menor que'), ('maior_igual', 'é maior ou igual a'), ('menor_igual', 'é menor ou igual a')], max_length=20)),
                ('valor', models.CharField(max_length=255)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condicoes', to='automacoes.regraautomacao')),
            ],
            options={
                'verbose_name': 'Condição',
                'verbose_name_plural': 'Condições',
                'db_table': 'automacoes_condicaoregra',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='acaoregra',
            name='regra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='automacoes.regraautomacao'),
        ),
    ]
