# Generated by Django 5.2.4 on 2026-04-03 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0001_initial'),
        ('crm', '0003_alter_tagcrm_nome_alter_tagcrm_unique_together'),
        ('leads', '0001_initial'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logexecucao',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_automacao', to='leads.leadprospecto'),
        ),
        migrations.AddField(
            model_name='regraautomacao',
            name='cooldown_horas',
            field=models.PositiveIntegerField(default=0, help_text='Mínimo de horas entre execuções para o mesmo lead. 0 = sem cooldown'),
        ),
        migrations.AddField(
            model_name='regraautomacao',
            name='fluxo_json',
            field=models.JSONField(blank=True, default=dict, help_text='Estado do editor Drawflow para re-import'),
        ),
        migrations.AddField(
            model_name='regraautomacao',
            name='max_execucoes_por_lead',
            field=models.PositiveIntegerField(default=0, help_text='0 = ilimitado'),
        ),
        migrations.AddField(
            model_name='regraautomacao',
            name='modo_fluxo',
            field=models.BooleanField(default=False, help_text='True = fluxograma visual, False = linear legado'),
        ),
        migrations.AddField(
            model_name='regraautomacao',
            name='periodo_limite_horas',
            field=models.PositiveIntegerField(default=24, help_text='Janela de tempo para max_execucoes_por_lead'),
        ),
        migrations.AddField(
            model_name='regraautomacao',
            name='segmento',
            field=models.ForeignKey(blank=True, help_text='Segmento para disparo em massa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automacoes', to='crm.segmentocrm'),
        ),
        migrations.AlterField(
            model_name='acaoregra',
            name='configuracao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='logexecucao',
            name='acao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='automacoes.acaoregra'),
        ),
        migrations.AlterField(
            model_name='logexecucao',
            name='data_agendada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logexecucao',
            name='evento_dados',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='logexecucao',
            name='resultado',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='regraautomacao',
            name='evento',
            field=models.CharField(choices=[('lead_criado', 'Novo lead criado'), ('lead_qualificado', 'Lead qualificado (score mínimo)'), ('lead_sem_contato', 'Lead sem contato há X dias'), ('oportunidade_movida', 'Oportunidade movida de estágio'), ('venda_aprovada', 'Venda aprovada'), ('cliente_aniversario', 'Aniversário de cliente'), ('indicacao_convertida', 'Indicação convertida'), ('tarefa_vencida', 'Tarefa CRM vencida'), ('docs_validados', 'Documentos validados'), ('lead_entrou_segmento', 'Lead entrou em um segmento'), ('disparo_segmento', 'Disparo em massa por segmento')], max_length=50),
        ),
        migrations.CreateModel(
            name='NodoFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('trigger', 'Gatilho'), ('condition', 'Condição (If/Else)'), ('action', 'Ação'), ('delay', 'Atraso')], max_length=20)),
                ('subtipo', models.CharField(blank=True, help_text='Ex: lead_criado, enviar_whatsapp, campo_check', max_length=50)),
                ('configuracao', models.JSONField(blank=True, default=dict, help_text='Config do nó: template, campo/operador/valor, delay, etc.')),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodos', to='automacoes.regraautomacao')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Nodo do Fluxo',
                'verbose_name_plural': 'Nodos do Fluxo',
                'db_table': 'automacoes_nodofluxo',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='logexecucao',
            name='nodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='automacoes.nodofluxo'),
        ),
        migrations.CreateModel(
            name='ControleExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_execucoes_periodo', models.PositiveIntegerField(default=0)),
                ('primeira_execucao_periodo', models.DateTimeField(blank=True, null=True)),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_automacao', to='leads.leadprospecto')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='automacoes.regraautomacao')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Controle de Execução',
                'verbose_name_plural': 'Controles de Execução',
                'db_table': 'automacoes_controleexecucao',
                'unique_together': {('lead', 'regra')},
            },
        ),
        migrations.CreateModel(
            name='ExecucaoPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto_json', models.JSONField(default=dict, help_text='Contexto serializado para retomar execução')),
                ('data_agendada', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('executado', 'Executado'), ('cancelado', 'Cancelado'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_execucao', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True)),
                ('acao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendentes', to='automacoes.acaoregra')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automacoes_pendentes', to='leads.leadprospecto')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendentes', to='automacoes.regraautomacao')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('nodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendentes', to='automacoes.nodofluxo')),
            ],
            options={
                'verbose_name': 'Execução Pendente',
                'verbose_name_plural': 'Execuções Pendentes',
                'db_table': 'automacoes_execucaopendente',
                'ordering': ['data_agendada'],
                'indexes': [models.Index(fields=['status', 'data_agendada'], name='automacoes__status_cb51de_idx'), models.Index(fields=['lead', 'status'], name='automacoes__lead_id_c56613_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConexaoNodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_saida', models.CharField(choices=[('default', 'Padrão'), ('true', 'Verdadeiro (Sim)'), ('false', 'Falso (Não)')], default='default', max_length=10)),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes', to='automacoes.regraautomacao')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('nodo_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='automacoes.nodofluxo')),
                ('nodo_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='automacoes.nodofluxo')),
            ],
            options={
                'verbose_name': 'Conexão',
                'verbose_name_plural': 'Conexões',
                'db_table': 'automacoes_conexaonodo',
                'unique_together': {('nodo_origem', 'nodo_destino', 'tipo_saida')},
            },
        ),
    ]
