# Generated by Django 5.2.4 on 2026-04-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0002_logexecucao_lead_regraautomacao_cooldown_horas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regraautomacao',
            name='evento',
            field=models.CharField(choices=[('lead_criado', 'Novo lead criado'), ('lead_qualificado', 'Lead qualificado (score mínimo)'), ('lead_sem_contato', 'Lead sem contato há X dias'), ('oportunidade_movida', 'Oportunidade movida de estágio'), ('venda_aprovada', 'Venda aprovada'), ('cliente_aniversario', 'Aniversário de cliente'), ('indicacao_convertida', 'Indicação convertida'), ('tarefa_vencida', 'Tarefa CRM vencida'), ('docs_validados', 'Documentos validados'), ('lead_entrou_segmento', 'Lead entrou em um segmento'), ('disparo_segmento', 'Disparo em massa por segmento'), ('mensagem_recebida', 'Mensagem recebida no inbox'), ('conversa_aberta', 'Nova conversa aberta no inbox'), ('conversa_resolvida', 'Conversa resolvida no inbox')], max_length=50),
        ),
    ]
