# Generated by Django 5.2.4 on 2026-06-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0004_alter_regraautomacao_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaoregra',
            name='tipo',
            field=models.CharField(choices=[('enviar_whatsapp', 'Enviar WhatsApp'), ('enviar_email', 'Enviar E-mail'), ('notificacao_sistema', 'Notificação no sistema'), ('criar_tarefa', 'Criar tarefa no CRM'), ('mover_estagio', 'Mover estágio no pipeline'), ('atribuir_responsavel', 'Atribuir responsável'), ('dar_pontos', 'Dar pontos no Clube'), ('webhook', 'Chamar webhook externo'), ('sincronizar_prospecto_hubsoft', 'Sincronizar prospecto HubSoft (cria/atualiza)')], max_length=50),
        ),
    ]
