# Generated by Django 5.2.4 on 2026-06-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0005_alter_acaoregra_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regraautomacao',
            name='evento',
            field=models.CharField(blank=True, choices=[('lead_criado', 'Novo lead criado'), ('lead_qualificado', 'Lead qualificado (score mínimo)'), ('lead_sem_contato', 'Lead sem contato há X dias'), ('lead_status_pendente', 'Lead atingiu status pendente (pronto pra integracao)'), ('oportunidade_movida', 'Oportunidade movida de estágio'), ('venda_aprovada', 'Venda aprovada'), ('cliente_aniversario', 'Aniversário de cliente'), ('indicacao_convertida', 'Indicação convertida'), ('tarefa_vencida', 'Tarefa CRM vencida'), ('docs_validados', 'Documentos validados'), ('lead_entrou_segmento', 'Lead entrou em um segmento'), ('disparo_segmento', 'Disparo em massa por segmento'), ('mensagem_recebida', 'Mensagem recebida no inbox'), ('conversa_aberta', 'Nova conversa aberta no inbox'), ('conversa_resolvida', 'Conversa resolvida no inbox')], default='', help_text='Definido no editor visual como nó gatilho', max_length=50),
        ),
    ]
