# Generated by Django 5.2.4 on 2025-08-08 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0002_historicocontato_converteu_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadprospecto',
            name='canal_entrada',
            field=models.CharField(blank=True, choices=[('site', 'Site'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google Ads'), ('whatsapp', 'WhatsApp'), ('indicacao', 'Indicação'), ('telefone', 'Telefone'), ('email', 'Email'), ('outros', 'Outros')], help_text='Canal por onde o lead entrou no sistema', max_length=50, null=True, verbose_name='Canal de Entrada'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='custo_aquisicao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo investido para adquirir este lead', max_digits=10, null=True, verbose_name='Custo de Aquisição'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='data_ultimo_contato',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Último Contato'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, help_text='Motivo detalhado caso tenha sido rejeitado', null=True, verbose_name='Motivo da Rejeição'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='score_qualificacao',
            field=models.IntegerField(blank=True, help_text='Score de 1 a 10 baseado na qualificação do lead', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Score de Qualificação'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='tentativas_contato',
            field=models.PositiveIntegerField(default=0, help_text='Número de tentativas de contato realizadas', verbose_name='Tentativas de Contato'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='tipo_entrada',
            field=models.CharField(blank=True, choices=[('contato_whatsapp', 'Contato WhatsApp'), ('cadastro_site', 'Cadastro Site'), ('telefone', 'Telefone'), ('formulario', 'Formulário'), ('importacao', 'Importação'), ('api_externa', 'API Externa')], help_text='Tipo específico de entrada no sistema', max_length=50, null=True, verbose_name='Tipo de Entrada'),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='data_fim_processamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Fim Processamento'),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='data_inicio_processamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Início Processamento'),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='score_conversao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Probabilidade de conversão calculada (0-100%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score de Conversão'),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='usuario_processamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuário que Processou'),
        ),
        migrations.AlterField(
            model_name='historicocontato',
            name='status',
            field=models.CharField(choices=[('fluxo_inicializado', 'Fluxo Inicializado'), ('fluxo_finalizado', 'Fluxo Finalizado'), ('transferido_humano', 'Transferido para Humano'), ('chamada_perdida', 'Chamada Perdida'), ('ocupado', 'Ocupado'), ('desligou', 'Desligou'), ('nao_atendeu', 'Não Atendeu'), ('abandonou_fluxo', 'Abandonou o Fluxo'), ('numero_invalido', 'Número Inválido'), ('erro_sistema', 'Erro do Sistema'), ('convertido_lead', 'Convertido em Lead'), ('venda_confirmada', 'Venda Confirmada'), ('venda_rejeitada', 'Venda Rejeitada'), ('venda_sem_viabilidade', 'Venda Sem Viabilidade'), ('cliente_desistiu', 'Cliente Desistiu'), ('aguardando_validacao', 'Aguardando Validação'), ('followup_agendado', 'Follow-up Agendado'), ('nao_qualificado', 'Não Qualificado')], max_length=30, verbose_name='Status do Contato'),
        ),
        migrations.AlterField(
            model_name='leadprospecto',
            name='status_api',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processado', 'Processado'), ('erro', 'Erro'), ('sucesso', 'Sucesso'), ('rejeitado', 'Rejeitado'), ('aguardando_retry', 'Aguardando Retry'), ('processamento_manual', 'Processamento Manual')], default='pendente', help_text='Status do processamento na API', max_length=20, verbose_name='Status API'),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('processado', 'Processado'), ('erro', 'Erro'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('aguardando_validacao', 'Aguardando Validação'), ('validacao_aprovada', 'Validação Aprovada'), ('validacao_rejeitada', 'Validação Rejeitada')], default='pendente', help_text='Status atual do processamento', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['canal_entrada'], name='leads_prosp_canal_e_bf753f_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['tipo_entrada'], name='leads_prosp_tipo_en_fdceb2_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['score_qualificacao'], name='leads_prosp_score_q_c74bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['data_ultimo_contato'], name='leads_prosp_data_ul_3fc6e1_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['tentativas_contato'], name='leads_prosp_tentati_f48189_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['canal_entrada', 'data_cadastro'], name='leads_prosp_canal_e_c84337_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['score_qualificacao', 'status_api'], name='leads_prosp_score_q_60b836_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['tipo_entrada', 'ativo'], name='leads_prosp_tipo_en_3d0197_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['data_ultimo_contato', 'tentativas_contato'], name='leads_prosp_data_ul_6e46eb_idx'),
        ),
        migrations.AddIndex(
            model_name='prospecto',
            index=models.Index(fields=['data_inicio_processamento'], name='prospectos_data_in_768e09_idx'),
        ),
        migrations.AddIndex(
            model_name='prospecto',
            index=models.Index(fields=['data_fim_processamento'], name='prospectos_data_fi_298986_idx'),
        ),
        migrations.AddIndex(
            model_name='prospecto',
            index=models.Index(fields=['usuario_processamento'], name='prospectos_usuario_ffb44b_idx'),
        ),
        migrations.AddIndex(
            model_name='prospecto',
            index=models.Index(fields=['score_conversao'], name='prospectos_score_c_57dabd_idx'),
        ),
        migrations.AddIndex(
            model_name='prospecto',
            index=models.Index(fields=['status', 'data_inicio_processamento'], name='prospectos_status_dd0be9_idx'),
        ),
        migrations.AddIndex(
            model_name='prospecto',
            index=models.Index(fields=['prioridade', 'data_criacao'], name='prospectos_priorid_1e3057_idx'),
        ),
        migrations.AddIndex(
            model_name='prospecto',
            index=models.Index(fields=['score_conversao', 'status'], name='prospectos_score_c_bfee71_idx'),
        ),
    ]
