# Generated by Django 5.2.4 on 2025-08-08 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0003_leadprospecto_canal_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadprospecto',
            name='email',
            field=models.EmailField(blank=True, help_text='Email válido do cliente', max_length=255, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
    ]
