# Generated by Django 5.2.4 on 2025-08-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0004_alter_leadprospecto_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadprospecto',
            name='id_hubsoft',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador do lead no Hubsoft para relacionar automaticamente com prospectos', max_length=100, null=True, verbose_name='ID Hubsoft'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['id_hubsoft'], name='leads_prosp_id_hubs_32a959_idx'),
        ),
    ]
