# Generated by Django 5.2.4 on 2025-08-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0005_leadprospecto_id_hubsoft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadprospecto',
            name='bairro',
            field=models.CharField(blank=True, help_text='Bairro do endereço', max_length=120, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='id_dia_vencimento',
            field=models.IntegerField(blank=True, help_text='Identificador do dia de vencimento no RP', null=True, verbose_name='ID Dia de Vencimento'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='id_plano_rp',
            field=models.IntegerField(blank=True, help_text='Identificador do plano no sistema RP', null=True, verbose_name='ID Plano (RP)'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='id_vendedor_rp',
            field=models.IntegerField(blank=True, help_text='Identificador do vendedor no sistema RP', null=True, verbose_name='ID Vendedor (RP)'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='numero_residencia',
            field=models.CharField(blank=True, help_text='Número do endereço', max_length=20, null=True, verbose_name='Número da Residência'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='rua',
            field=models.CharField(blank=True, help_text='Logradouro do endereço', max_length=255, null=True, verbose_name='Rua'),
        ),
    ]
