# Generated by Django 5.2.4 on 2025-09-16 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0010_opcaovencimento_planointernet_configuracaocadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrocliente',
            name='contrato_aceito',
            field=models.BooleanField(default=False, verbose_name='Contrato Aceito'),
        ),
        migrations.AddField(
            model_name='cadastrocliente',
            name='data_aceite_contrato',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aceite do Contrato'),
        ),
        migrations.AddField(
            model_name='cadastrocliente',
            name='data_envio_documentos',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio dos Documentos'),
        ),
        migrations.AddField(
            model_name='cadastrocliente',
            name='documentos_enviados',
            field=models.BooleanField(default=False, verbose_name='Documentos Enviados'),
        ),
        migrations.AddField(
            model_name='cadastrocliente',
            name='ip_aceite_contrato',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Aceite do Contrato'),
        ),
        migrations.AddField(
            model_name='cadastrocliente',
            name='tempo_leitura_contrato',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo de Leitura do Contrato (segundos)'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='background_color_1',
            field=models.CharField(default='#667eea', help_text='Cor principal ou inicial do gradiente', max_length=7, verbose_name='Cor de Background 1'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='background_color_2',
            field=models.CharField(default='#764ba2', help_text='Cor secundária ou final do gradiente', max_length=7, verbose_name='Cor de Background 2'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='background_image_url',
            field=models.URLField(blank=True, help_text='URL da imagem de fundo (se tipo = imagem)', max_length=500, null=True, verbose_name='URL da Imagem de Background'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='background_type',
            field=models.CharField(choices=[('gradient', 'Gradiente'), ('solid', 'Cor Sólida'), ('image', 'Imagem')], default='gradient', max_length=20, verbose_name='Tipo de Background'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='error_color',
            field=models.CharField(default='#e74c3c', max_length=7, verbose_name='Cor de Erro'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='exibir_contrato',
            field=models.BooleanField(default=True, help_text='Mostra contrato antes da finalização', verbose_name='Exibir Contrato'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='formatos_aceitos',
            field=models.CharField(default='jpg,jpeg,png,webp', help_text='Separados por vírgula', max_length=100, verbose_name='Formatos de Arquivo Aceitos'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='logo_url',
            field=models.URLField(default='https://i.ibb.co/q3MyCdBZ/Ativo-33.png', help_text='URL da imagem da logo', max_length=500, verbose_name='URL da Logo'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='primary_color',
            field=models.CharField(default='#667eea', help_text='Cor principal para botões e destaques', max_length=7, verbose_name='Cor Primária'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='secondary_color',
            field=models.CharField(default='#764ba2', help_text='Cor secundária para elementos', max_length=7, verbose_name='Cor Secundária'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='solicitar_documentacao',
            field=models.BooleanField(default=True, help_text='Habilita etapa de envio de documentos', verbose_name='Solicitar Documentação'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='success_color',
            field=models.CharField(default='#2ecc71', max_length=7, verbose_name='Cor de Sucesso'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='tamanho_max_arquivo_mb',
            field=models.PositiveIntegerField(default=5, verbose_name='Tamanho Máximo de Arquivo (MB)'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='tempo_minimo_leitura_segundos',
            field=models.PositiveIntegerField(default=30, help_text='Tempo mínimo antes de permitir aceite', verbose_name='Tempo Mínimo de Leitura (segundos)'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='texto_aceite_contrato',
            field=models.CharField(default='Li e concordo com os termos do contrato', max_length=200, verbose_name='Texto de Aceite do Contrato'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='texto_contrato',
            field=models.TextField(default='Ao assinar este contrato, você concorda com os termos e condições de prestação de serviços...', help_text='Texto completo do contrato a ser exibido', verbose_name='Texto do Contrato'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='texto_instrucao_doc_frente',
            field=models.TextField(default='Tire uma foto nítida da frente do seu documento', verbose_name='Instrução para Documento Frente'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='texto_instrucao_doc_verso',
            field=models.TextField(default='Tire uma foto nítida do verso do seu documento', verbose_name='Instrução para Documento Verso'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='texto_instrucao_selfie',
            field=models.TextField(default='Por favor, tire uma selfie segurando seu documento de identificação próximo ao rosto', verbose_name='Instrução para Selfie'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='titulo_contrato',
            field=models.CharField(default='Termos de Serviço e Contrato', max_length=200, verbose_name='Título do Contrato'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='contrato_aceito',
            field=models.BooleanField(default=False, help_text='Indica se o contrato foi aceito', verbose_name='Contrato Aceito'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='data_aceite_contrato',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aceite do Contrato'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='data_documentacao_completa',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Documentação Completa'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='data_documentacao_validada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Documentação Validada'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='documentacao_completa',
            field=models.BooleanField(default=False, help_text='Indica se toda documentação foi enviada', verbose_name='Documentação Completa'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='documentacao_validada',
            field=models.BooleanField(default=False, help_text='Indica se a documentação foi validada', verbose_name='Documentação Validada'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='ip_aceite_contrato',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Aceite do Contrato'),
        ),
        migrations.AlterField(
            model_name='cadastrocliente',
            name='status',
            field=models.CharField(choices=[('iniciado', 'Iniciado'), ('dados_pessoais', 'Dados Pessoais Preenchidos'), ('endereco', 'Endereço Preenchido'), ('documentacao', 'Documentação Enviada'), ('contrato', 'Contrato Aceito'), ('finalizado', 'Finalizado'), ('erro', 'Erro'), ('cancelado', 'Cancelado')], default='iniciado', max_length=20, verbose_name='Status do Cadastro'),
        ),
        migrations.CreateModel(
            name='DocumentoLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('selfie', 'Selfie com Documento'), ('doc_frente', 'Documento Frente'), ('doc_verso', 'Documento Verso'), ('comprovante_residencia', 'Comprovante de Residência'), ('contrato_assinado', 'Contrato Assinado'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo de Documento')),
                ('arquivo_base64', models.TextField(help_text='Imagem codificada em base64', verbose_name='Arquivo em Base64')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('tamanho_arquivo', models.PositiveIntegerField(verbose_name='Tamanho do Arquivo (bytes)')),
                ('formato_arquivo', models.CharField(max_length=10, verbose_name='Formato do Arquivo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('em_analise', 'Em Análise')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes_validacao', models.TextField(blank=True, null=True, verbose_name='Observações da Validação')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('data_validacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Validação')),
                ('validado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Validado Por')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='vendas_web.leadprospecto', verbose_name='Lead/Prospecto')),
            ],
            options={
                'verbose_name': 'Documento do Lead',
                'verbose_name_plural': 'Documentos do Lead',
                'db_table': 'documentos_lead',
                'ordering': ['-data_upload'],
                'indexes': [models.Index(fields=['lead', 'tipo_documento'], name='documentos__lead_id_aef551_idx'), models.Index(fields=['status'], name='documentos__status_a9c4b4_idx'), models.Index(fields=['data_upload'], name='documentos__data_up_f54585_idx')],
            },
        ),
    ]
