# Generated by Django 5.2.4 on 2025-09-18 23:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0011_cadastrocliente_contrato_aceito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questaofluxo',
            name='criterios_ia',
            field=models.JSONField(blank=True, help_text='Critérios específicos para validação: {criterio: peso}', null=True, verbose_name='Critérios de IA'),
        ),
        migrations.AddField(
            model_name='questaofluxo',
            name='estrategia_erro',
            field=models.CharField(choices=[('repetir', 'Repetir Questão'), ('pular', 'Pular Questão'), ('redirecionar', 'Redirecionar'), ('finalizar', 'Finalizar Fluxo'), ('escalar_humano', 'Escalar para Humano')], default='repetir', max_length=20, verbose_name='Estratégia de Erro'),
        ),
        migrations.AddField(
            model_name='questaofluxo',
            name='instrucoes_resposta_correta',
            field=models.TextField(blank=True, help_text='Orientações sobre como responder corretamente', null=True, verbose_name='Instruções para Resposta Correta'),
        ),
        migrations.AddField(
            model_name='questaofluxo',
            name='max_tentativas',
            field=models.PositiveIntegerField(default=3, help_text='Número máximo de tentativas antes de aplicar estratégia de erro', verbose_name='Máximo de Tentativas'),
        ),
        migrations.AddField(
            model_name='questaofluxo',
            name='mensagem_erro_padrao',
            field=models.TextField(blank=True, help_text='Mensagem exibida quando resposta é inválida', null=True, verbose_name='Mensagem de Erro Padrão'),
        ),
        migrations.AddField(
            model_name='questaofluxo',
            name='mensagem_tentativa_esgotada',
            field=models.TextField(blank=True, help_text='Mensagem quando máximo de tentativas é atingido', null=True, verbose_name='Mensagem Tentativas Esgotadas'),
        ),
        migrations.AddField(
            model_name='questaofluxo',
            name='opcoes_dinamicas_fonte',
            field=models.CharField(blank=True, choices=[('planos_internet', 'Planos de Internet'), ('opcoes_vencimento', 'Opções de Vencimento'), ('api_externa', 'API Externa'), ('query_customizada', 'Query Customizada')], max_length=50, null=True, verbose_name='Fonte de Opções Dinâmicas'),
        ),
        migrations.AddField(
            model_name='questaofluxo',
            name='prompt_ia_validacao',
            field=models.TextField(blank=True, help_text='Prompt específico para validação da resposta por IA', null=True, verbose_name='Prompt para IA'),
        ),
        migrations.AddField(
            model_name='questaofluxo',
            name='query_opcoes_dinamicas',
            field=models.TextField(blank=True, help_text='Query SQL ou configuração para buscar opções dinamicamente', null=True, verbose_name='Query para Opções Dinâmicas'),
        ),
        migrations.AddField(
            model_name='questaofluxo',
            name='questao_erro_redirecionamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questoes_erro_origem', to='vendas_web.questaofluxo', verbose_name='Questão para Redirecionamento de Erro'),
        ),
        migrations.AddField(
            model_name='questaofluxo',
            name='questao_padrao_proxima',
            field=models.ForeignKey(blank=True, help_text='Questão padrão caso resposta não tenha roteamento específico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questoes_anteriores_padrao', to='vendas_web.questaofluxo', verbose_name='Questão Padrão Próxima'),
        ),
        migrations.AddField(
            model_name='questaofluxo',
            name='roteamento_respostas',
            field=models.JSONField(blank=True, default=dict, help_text='Mapeamento de respostas para próximas questões: {resposta: questao_id}', null=True, verbose_name='Roteamento por Respostas'),
        ),
        migrations.AddField(
            model_name='questaofluxo',
            name='template_questao',
            field=models.TextField(blank=True, help_text="Template com variáveis: 'Olá {{nome}}, qual seu plano preferido?'", null=True, verbose_name='Template da Questão'),
        ),
        migrations.AddField(
            model_name='questaofluxo',
            name='variaveis_contexto',
            field=models.JSONField(blank=True, default=dict, help_text='Variáveis que podem ser usadas na questão: {nome: valor}', null=True, verbose_name='Variáveis de Contexto'),
        ),
        migrations.AddField(
            model_name='questaofluxo',
            name='webhook_n8n_pos_resposta',
            field=models.URLField(blank=True, help_text='URL do webhook N8N executado após resposta válida', null=True, verbose_name='Webhook N8N Pós-Resposta'),
        ),
        migrations.AddField(
            model_name='questaofluxo',
            name='webhook_n8n_validacao',
            field=models.URLField(blank=True, help_text='URL do webhook N8N para validação customizada', null=True, verbose_name='Webhook N8N para Validação'),
        ),
        migrations.AlterField(
            model_name='questaofluxo',
            name='tipo_questao',
            field=models.CharField(choices=[('texto', 'Texto Livre'), ('numero', 'Número'), ('email', 'Email'), ('telefone', 'Telefone'), ('cpf_cnpj', 'CPF/CNPJ'), ('cep', 'CEP'), ('endereco', 'Endereço'), ('select', 'Seleção Única'), ('multiselect', 'Seleção Múltipla'), ('data', 'Data'), ('hora', 'Hora'), ('data_hora', 'Data e Hora'), ('boolean', 'Sim/Não'), ('escala', 'Escala (1-10)'), ('arquivo', 'Upload de Arquivo'), ('planos_internet', 'Seleção de Planos Internet'), ('vencimentos', 'Seleção de Vencimentos'), ('opcoes_dinamicas', 'Opções Dinâmicas'), ('ia_validacao', 'Validação por IA'), ('condicional_complexa', 'Condicional Complexa')], default='texto', max_length=20, verbose_name='Tipo de Questão'),
        ),
        migrations.AlterField(
            model_name='questaofluxo',
            name='tipo_validacao',
            field=models.CharField(choices=[('obrigatoria', 'Obrigatória'), ('opcional', 'Opcional'), ('condicional', 'Condicional'), ('ia_assistida', 'IA Assistida'), ('validacao_customizada', 'Validação Customizada')], default='obrigatoria', max_length=25, verbose_name='Tipo de Validação'),
        ),
        migrations.CreateModel(
            name='TentativaResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentativa_numero', models.PositiveIntegerField(verbose_name='Número da Tentativa')),
                ('resposta_original', models.TextField(verbose_name='Resposta Original')),
                ('resposta_processada', models.JSONField(blank=True, null=True, verbose_name='Resposta Processada')),
                ('valida', models.BooleanField(default=False, verbose_name='Resposta Válida')),
                ('mensagem_erro', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('resultado_ia', models.JSONField(blank=True, help_text='Resultado completo da validação por IA', null=True, verbose_name='Resultado da IA')),
                ('confianca_ia', models.DecimalField(blank=True, decimal_places=4, help_text='Score de confiança da IA (0.0 a 1.0)', max_digits=5, null=True, verbose_name='Confiança da IA')),
                ('resultado_webhook', models.JSONField(blank=True, null=True, verbose_name='Resultado do Webhook N8N')),
                ('estrategia_aplicada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estratégia Aplicada')),
                ('contexto_tentativa', models.JSONField(blank=True, null=True, verbose_name='Contexto da Tentativa')),
                ('data_tentativa', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Tentativa')),
                ('tempo_resposta_segundos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo de Resposta (segundos)')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_respostas', to='vendas_web.atendimentofluxo', verbose_name='Atendimento')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='vendas_web.questaofluxo', verbose_name='Questão')),
            ],
            options={
                'verbose_name': 'Tentativa de Resposta',
                'verbose_name_plural': 'Tentativas de Resposta',
                'db_table': 'tentativas_resposta',
                'ordering': ['-data_tentativa'],
                'indexes': [models.Index(fields=['atendimento', 'questao'], name='tentativas__atendim_ae5f36_idx'), models.Index(fields=['tentativa_numero'], name='tentativas__tentati_16cc9b_idx'), models.Index(fields=['valida'], name='tentativas__valida_799a8e_idx'), models.Index(fields=['data_tentativa'], name='tentativas__data_te_32f1cf_idx')],
                'unique_together': {('atendimento', 'questao', 'tentativa_numero')},
            },
        ),
    ]
