# Generated by Django 5.2.4 on 2025-09-25 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0013_configuracaoempresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimentofluxo',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Atendimento de Fluxo', 'verbose_name_plural': '🤖 03. Atendimentos de Fluxo'},
        ),
        migrations.AlterModelOptions(
            name='cadastrocliente',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Cadastro de Cliente', 'verbose_name_plural': '📈 01. Cadastros de Clientes'},
        ),
        migrations.AlterModelOptions(
            name='configuracaocadastro',
            options={'ordering': ['-ativo', '-data_atualizacao'], 'verbose_name': 'Configuração de Cadastro', 'verbose_name_plural': '⚙️ 02. Configurações de Cadastro'},
        ),
        migrations.AlterModelOptions(
            name='configuracaoempresa',
            options={'ordering': ['-ativo', '-data_criacao'], 'verbose_name': '🏢 Configuração da Empresa', 'verbose_name_plural': '⚙️ 01. Configurações da Empresa'},
        ),
        migrations.AlterModelOptions(
            name='configuracaosistema',
            options={'ordering': ['chave'], 'verbose_name': 'Configuração do Sistema', 'verbose_name_plural': '📈 04. Configurações do Sistema'},
        ),
        migrations.AlterModelOptions(
            name='documentolead',
            options={'ordering': ['-data_upload'], 'verbose_name': 'Documento do Lead', 'verbose_name_plural': '📈 02. Documentos do Lead'},
        ),
        migrations.AlterModelOptions(
            name='fluxoatendimento',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Fluxo de Atendimento', 'verbose_name_plural': '🤖 01. Fluxos de Atendimento'},
        ),
        migrations.AlterModelOptions(
            name='historicocontato',
            options={'ordering': ['-data_hora_contato'], 'verbose_name': 'Histórico de Contato', 'verbose_name_plural': '📊 03. Histórico de Contatos'},
        ),
        migrations.AlterModelOptions(
            name='leadprospecto',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Lead/Prospecto', 'verbose_name_plural': '📊 01. Leads/Prospectos'},
        ),
        migrations.AlterModelOptions(
            name='logsistema',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Log do Sistema', 'verbose_name_plural': '📈 03. Logs do Sistema'},
        ),
        migrations.AlterModelOptions(
            name='opcaovencimento',
            options={'ordering': ['ordem_exibicao', 'dia_vencimento'], 'verbose_name': 'Opção de Vencimento', 'verbose_name_plural': '⚙️ 04. Opções de Vencimento'},
        ),
        migrations.AlterModelOptions(
            name='planointernet',
            options={'ordering': ['ordem_exibicao', 'valor_mensal'], 'verbose_name': 'Plano de Internet', 'verbose_name_plural': '⚙️ 03. Planos de Internet'},
        ),
        migrations.AlterModelOptions(
            name='prospecto',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Prospecto', 'verbose_name_plural': '📊 02. Prospectos'},
        ),
        migrations.AlterModelOptions(
            name='questaofluxo',
            options={'ordering': ['fluxo', 'indice'], 'verbose_name': 'Questão do Fluxo', 'verbose_name_plural': '🤖 02. Questões do Fluxo'},
        ),
        migrations.AlterModelOptions(
            name='respostaquestao',
            options={'ordering': ['atendimento', 'questao', '-data_resposta'], 'verbose_name': 'Resposta de Questão', 'verbose_name_plural': '🔧 01. Respostas de Questões'},
        ),
        migrations.AlterModelOptions(
            name='statusconfiguravel',
            options={'ordering': ['grupo', 'ordem', 'codigo'], 'verbose_name': 'Status Configurável', 'verbose_name_plural': '⚙️ 05. Status Configuráveis'},
        ),
        migrations.AlterModelOptions(
            name='tentativaresposta',
            options={'ordering': ['-data_tentativa'], 'verbose_name': 'Tentativa de Resposta', 'verbose_name_plural': '🔧 02. Tentativas de Resposta'},
        ),
    ]
