# Generated by Django 5.2.4 on 2025-10-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0018_add_whatsapp_config_to_tipo_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrocliente',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='rg',
            field=models.CharField(blank=True, help_text='Número do RG do cliente', max_length=30, null=True, verbose_name='RG'),
        ),
    ]
