# Generated by Django 5.2.4 on 2025-10-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0019_cadastrocliente_rg_leadprospecto_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiponotificacao',
            name='codigo',
            field=models.CharField(choices=[('lead_novo', 'Novo Lead'), ('lead_convertido', 'Lead Convertido'), ('venda_aprovada', 'Venda Aprovada'), ('venda_rejeitada', 'Venda Rejeitada'), ('prospecto_aguardando', 'Prospecto Aguardando Validação')], max_length=50, unique=True, verbose_name='Código'),
        ),
    ]
