# Generated by Django 5.2.4 on 2025-10-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0025_historicocontato_id_conta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocontato',
            name='codigo_atendimento',
            field=models.CharField(blank=True, db_index=True, help_text='Código único do atendimento', max_length=100, null=True, verbose_name='Código de Atendimento'),
        ),
        migrations.AddIndex(
            model_name='historicocontato',
            index=models.Index(fields=['codigo_atendimento'], name='historico_c_codigo__fe1f23_idx'),
        ),
    ]
