# Generated by Django 5.2.4 on 2025-11-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0026_historicocontato_codigo_atendimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadprospecto',
            name='id_origem_servico',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador do serviço específico de origem do lead', max_length=100, null=True, verbose_name='ID Origem Serviço'),
        ),
        migrations.AddIndex(
            model_name='leadprospecto',
            index=models.Index(fields=['id_origem_servico'], name='leads_prosp_id_orig_f2e894_idx'),
        ),
    ]
