# Generated by Django 5.2.4 on 2025-11-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0027_leadprospecto_id_origem_servico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaocadastro',
            name='id_origem',
            field=models.PositiveIntegerField(default=148, help_text='Identificador único do lead no sistema de origem (Facebook Ads, Google Ads, etc.)', verbose_name='ID Origem do Lead'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='id_origem_servico',
            field=models.PositiveIntegerField(default=63, help_text='Identificador do serviço específico de origem do lead', verbose_name='ID Origem do Serviço'),
        ),
        migrations.AddField(
            model_name='configuracaocadastro',
            name='id_vendedor',
            field=models.PositiveIntegerField(default=901, help_text='Identificador do vendedor responsável pelo lead', verbose_name='ID Vendedor (RP)'),
        ),
    ]
