# Generated by Django 5.2.4 on 2026-03-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0034_trocar_url_por_arquivo_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadprospecto',
            name='arquivo_pdf_conversa',
        ),
        migrations.AddField(
            model_name='leadprospecto',
            name='url_pdf_conversa',
            field=models.URLField(blank=True, help_text='Link do PDF da conversa gerado após validação dos documentos', max_length=1024, null=True, verbose_name='URL PDF da Conversa'),
        ),
        migrations.AlterField(
            model_name='leadprospecto',
            name='data_geracao_pdf',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Geração do PDF'),
        ),
    ]
