# Generated by Django 5.2.4 on 2026-03-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0038_cidade_viabilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadprospecto',
            name='status_api',
            field=models.CharField(default='pendente', help_text='Status do processamento na API', max_length=30, verbose_name='Status API'),
        ),
    ]
