# Generated by Django 5.2.4 on 2026-04-07 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0039_alter_leadprospecto_status_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoInstalacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('manha', 'Manha'), ('tarde', 'Tarde')], max_length=10)),
                ('data_instalacao', models.DateField()),
                ('horario', models.TimeField()),
                ('id_tecnico', models.IntegerField()),
                ('nome_tecnico', models.CharField(max_length=255)),
                ('id_agenda_os', models.IntegerField()),
                ('id_cliente_servico', models.IntegerField()),
                ('id_atendimento_matrix', models.IntegerField(blank=True, null=True)),
                ('id_os_matrix', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('agendado', 'Agendado'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('dados_resposta_atendimento', models.JSONField(blank=True, default=dict)),
                ('dados_resposta_os', models.JSONField(blank=True, default=dict)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_instalacao', to='vendas_web.cadastrocliente')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_instalacao', to='vendas_web.leadprospecto')),
            ],
            options={
                'verbose_name': 'Agendamento de Instalacao',
                'verbose_name_plural': 'Agendamentos de Instalacao',
                'db_table': 'agendamentos_instalacao',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
