# Generated by Django 5.2.4 on 2026-05-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0040_agendamentoinstalacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadprospecto',
            name='data_ultima_tentativa_sync_hubsoft',
            field=models.DateTimeField(blank=True, help_text='Atualizado a cada tentativa de sincronizar com Hubsoft (sucesso ou não)', null=True, verbose_name='Última tentativa de sync Hubsoft'),
        ),
    ]
