# Generated by Django 5.2.4 on 2026-05-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0048_leadprospecto_primeira_tentativa_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadprospecto',
            name='dados_confirmados',
            field=models.BooleanField(blank=True, help_text='True=confirmou tudo; False=negou (transbordo); None=ainda não perguntou', null=True, verbose_name='Dados finais confirmados pelo cliente'),
        ),
        migrations.AlterField(
            model_name='leadprospecto',
            name='data_primeira_tentativa_sync_hubsoft',
            field=models.DateTimeField(blank=True, help_text='Set apenas na 1ª tentativa. Usado pra liberar uma janela de 15min de retries antes de aplicar o backoff longo (6h) em leads não encontrados.', null=True, verbose_name='Primeira tentativa de sync Hubsoft'),
        ),
        migrations.AlterField(
            model_name='leadprospecto',
            name='endereco_confirmado',
            field=models.BooleanField(blank=True, help_text='True=confirmou ViaCEP; False=precisa preencher manualmente; None=ainda não perguntou', null=True, verbose_name='Endereço confirmado pelo cliente'),
        ),
        migrations.AlterField(
            model_name='leadprospecto',
            name='tipo_ajuste',
            field=models.CharField(blank=True, choices=[('endereco', 'Endereço'), ('dados_pessoais', 'Dados pessoais'), ('plano', 'Plano selecionado')], default='', help_text='Setado quando cliente nega dados_confirmados e indica o que quer corrigir. Após API limpar os campos correspondentes, é zerado.', max_length=20, verbose_name='Tipo de ajuste solicitado'),
        ),
    ]
