# Generated by Django 5.2.4 on 2026-05-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0049_alter_leadprospecto_dados_confirmados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadprospecto',
            name='plano_confirmado',
            field=models.BooleanField(blank=True, help_text='True=confirmou após ver descrição; False=negou (volta a perguntar); None=ainda não perguntou', null=True, verbose_name='Plano confirmado pelo cliente'),
        ),
    ]
