# Generated by Django 5.2.4 on 2026-05-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0050_plano_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadprospecto',
            name='tipo_residencia',
            field=models.CharField(blank=True, choices=[('casa_terrea', 'Casa térrea / Sobrado'), ('apartamento', 'Apartamento'), ('condominio', 'Condomínio fechado')], default='', help_text='Sub-tipo de imóvel residencial (só relevante se tipo_imovel=casa). Determina quais detalhes pedir no complemento de endereço.', max_length=20, verbose_name='Tipo de residência'),
        ),
    ]
