# Generated by Django 5.2.4 on 2026-05-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0051_tipo_residencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemleadprospecto',
            name='status_validacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado_ia', 'Aprovado pela IA (aguardando validação humana)'), ('documentos_validos', 'Documentos Válidos'), ('documentos_rejeitados', 'Documentos Rejeitados')], db_index=True, default='pendente', max_length=30, verbose_name='Status de Validação'),
        ),
    ]
