# Generated by Django 5.2.4 on 2026-05-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0052_imagem_status_aprovado_ia'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('em_coleta', 'Em coleta (conversando com cliente)'), ('aguardando_validacao', 'Aguardando validação dos documentos'), ('documentos_validos', 'Documentos validados'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], db_index=True, default='em_coleta', max_length=30)),
                ('tipo_imovel', models.CharField(blank=True, choices=[('casa', 'Casa / Residencial'), ('empresa', 'Empresa / Comercial')], max_length=20)),
                ('tipo_residencia', models.CharField(blank=True, choices=[('casa_terrea', 'Casa térrea / Sobrado'), ('apartamento', 'Apartamento'), ('condominio', 'Condomínio fechado')], default='', max_length=20)),
                ('cep', models.CharField(blank=True, default='', max_length=10)),
                ('rua', models.CharField(blank=True, default='', max_length=255)),
                ('numero_residencia', models.CharField(blank=True, default='', max_length=20)),
                ('bairro', models.CharField(blank=True, default='', max_length=120)),
                ('cidade', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(blank=True, default='', max_length=2)),
                ('endereco_confirmado', models.BooleanField(blank=True, null=True)),
                ('ponto_referencia', models.CharField(blank=True, default='', max_length=255)),
                ('id_plano_rp', models.IntegerField(blank=True, null=True)),
                ('plano_confirmado', models.BooleanField(blank=True, null=True)),
                ('id_dia_vencimento', models.IntegerField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dados_confirmados', models.BooleanField(blank=True, null=True)),
                ('tipo_ajuste', models.CharField(blank=True, choices=[('endereco', 'Endereço'), ('plano', 'Plano selecionado')], default='', max_length=20)),
                ('doc_selfie_recebida', models.BooleanField(blank=True, default=None, null=True)),
                ('doc_frente_recebida', models.BooleanField(blank=True, default=None, null=True)),
                ('doc_verso_recebida', models.BooleanField(blank=True, default=None, null=True)),
                ('turno_instalacao', models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], default='', max_length=10)),
                ('data_instalacao', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novos_servicos', to='vendas_web.leadprospecto', verbose_name='Lead (cliente Hubsoft)')),
            ],
            options={
                'verbose_name': 'Novo Serviço',
                'verbose_name_plural': 'Novos Serviços',
                'db_table': 'new_service',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImagemNewService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.URLField(max_length=1024)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('status_validacao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado_ia', 'Aprovado pela IA (aguardando validação humana)'), ('documentos_validos', 'Documentos Válidos'), ('documentos_rejeitados', 'Documentos Rejeitados')], db_index=True, default='pendente', max_length=30)),
                ('observacao_validacao', models.TextField(blank=True, default='')),
                ('data_validacao', models.DateTimeField(blank=True, null=True)),
                ('validado_por', models.CharField(blank=True, default='', max_length=150)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('new_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='vendas_web.newservice')),
            ],
            options={
                'verbose_name': 'Imagem do Novo Serviço',
                'verbose_name_plural': 'Imagens do Novo Serviço',
                'db_table': 'imagens_new_service',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddIndex(
            model_name='newservice',
            index=models.Index(fields=['lead', 'status'], name='new_service_lead_id_4cfe0a_idx'),
        ),
        migrations.AddIndex(
            model_name='imagemnewservice',
            index=models.Index(fields=['new_service'], name='imagens_new_new_ser_1c5c02_idx'),
        ),
    ]
