# Generated by Django 5.2.4 on 2026-05-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0053_new_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='newservice',
            name='hubsoft_erro',
            field=models.TextField(blank=True, default='', help_text='Última mensagem de erro do webdriver (vazio = sem erro)', verbose_name='Mensagem de erro HubSoft'),
        ),
        migrations.AddField(
            model_name='newservice',
            name='hubsoft_processado_em',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Quando o webdriver concluiu (ou tentou concluir) a contratação no HubSoft', null=True, verbose_name='Processado no HubSoft em'),
        ),
        migrations.AddField(
            model_name='newservice',
            name='hubsoft_processado_status',
            field=models.CharField(blank=True, choices=[('sucesso', 'Contratação criada no HubSoft'), ('falha', 'Falha ao criar no HubSoft'), ('dry_run', 'Dry-run (sem clicar Salvar)')], default='', max_length=20, verbose_name='Resultado HubSoft'),
        ),
        migrations.AddIndex(
            model_name='newservice',
            index=models.Index(fields=['status', 'hubsoft_processado_em'], name='new_service_status_f15d5f_idx'),
        ),
    ]
