# Generated by Django 5.2.4 on 2026-05-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0054_newservice_hubsoft_erro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newservice',
            name='data_sync_matrix',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newservice',
            name='id_atendimento_matrix',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newservice',
            name='id_cliente_servico_origem',
            field=models.IntegerField(blank=True, help_text='id_cliente_servico do Hubsoft usado para abrir Atendimento+OS', null=True),
        ),
        migrations.AddField(
            model_name='newservice',
            name='id_os_matrix',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newservice',
            name='matrix_sync_status',
            field=models.CharField(choices=[('pendente', 'Pendente — aguardando processamento'), ('processando', 'Processando'), ('sincronizado', 'Sincronizado (Atendimento + OS abertos)'), ('erro', 'Erro na sincronização')], db_index=True, default='pendente', max_length=20, verbose_name='Status sync Matrix'),
        ),
        migrations.AddField(
            model_name='newservice',
            name='tentativas_sync_matrix',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newservice',
            name='ultimo_erro_sync_matrix',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='newservice',
            index=models.Index(fields=['status', 'matrix_sync_status'], name='new_service_status_7876bd_idx'),
        ),
    ]
