# Generated by Django 5.2.4 on 2026-06-08 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0055_newservice_matrix_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradePlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('em_coleta', 'Em coleta (montagem do pedido)'), ('finalizado', 'Finalizado — pronto pra processar'), ('cancelado', 'Cancelado')], db_index=True, default='em_coleta', max_length=20)),
                ('id_cliente_servico', models.IntegerField(db_index=True, help_text='id_cliente_servico do serviço a ser migrado', verbose_name='ID Cliente Serviço (HubSoft)')),
                ('id_plano_novo', models.IntegerField(help_text='id_servico do plano de destino no HubSoft', verbose_name='ID Plano novo (HubSoft id_servico)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('hubsoft_processado_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Processado no HubSoft em')),
                ('hubsoft_processado_status', models.CharField(blank=True, choices=[('sucesso', 'Upgrade aplicado no HubSoft'), ('falha', 'Falha ao aplicar upgrade'), ('dry_run', 'Dry-run (sem clicar Salvar)')], default='', max_length=20, verbose_name='Resultado HubSoft')),
                ('hubsoft_erro', models.TextField(blank=True, default='', verbose_name='Mensagem de erro HubSoft')),
                ('lead', models.ForeignKey(blank=True, help_text='Opcional — solicitações também podem vir de fonte sem lead vinculado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrades_plano', to='vendas_web.leadprospecto', verbose_name='Lead (origem da solicitação)')),
            ],
            options={
                'verbose_name': 'Upgrade de Plano',
                'verbose_name_plural': 'Upgrades de Plano',
                'db_table': 'upgrade_plano',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', 'hubsoft_processado_em'], name='upgrade_pla_status_de26de_idx'), models.Index(fields=['id_cliente_servico'], name='upgrade_pla_id_clie_96ffc4_idx')],
            },
        ),
    ]
