# Generated by Django 5.2.4 on 2026-06-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0056_upgradeplano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxoatendimento',
            name='tipo_fluxo',
            field=models.CharField(choices=[('qualificacao', 'Qualificação de Lead'), ('vendas', 'Vendas'), ('suporte', 'Suporte'), ('onboarding', 'Onboarding'), ('pesquisa', 'Pesquisa de Satisfação'), ('customizado', 'Customizado'), ('upgrade', 'Upgrade de Plano')], default='qualificacao', max_length=20, verbose_name='Tipo de Fluxo'),
        ),
        migrations.AlterField(
            model_name='questaofluxo',
            name='opcoes_dinamicas_fonte',
            field=models.CharField(blank=True, choices=[('planos_internet', 'Planos de Internet'), ('opcoes_vencimento', 'Opções de Vencimento'), ('api_externa', 'API Externa'), ('query_customizada', 'Query Customizada'), ('servicos_ativos_cliente', 'Serviços Ativos do Cliente (HubSoft)'), ('planos_upgrade_disponiveis', 'Planos Disponíveis pra Upgrade')], max_length=50, null=True, verbose_name='Fonte de Opções Dinâmicas'),
        ),
    ]
