# Generated by Django 5.2.4 on 2026-06-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0057_alter_fluxoatendimento_tipo_fluxo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newservice',
            name='matrix_sync_status',
            field=models.CharField(choices=[('pendente', 'Pendente — aguardando processamento'), ('processando', 'Processando'), ('sincronizado', 'Sincronizado (Atendimento + OS abertos)'), ('erro', 'Erro na sincronização'), ('cancelado', 'Cancelado / ignorado (não abrir Atendimento+OS)')], db_index=True, default='pendente', max_length=20, verbose_name='Status sync Matrix'),
        ),
    ]
