# Generated by Django 5.2.4 on 2026-06-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0058_alter_newservice_matrix_sync_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canalnotificacao',
            name='codigo',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('webhook', 'Webhook'), ('painel', 'Painel (in-app)')], max_length=20, unique=True, verbose_name='Código'),
        ),
    ]
