# Generated by Django 5.2.14 on 2026-07-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0059_alter_canalnotificacao_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadprospecto',
            name='id_indicador',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Código único que identifica quem indicou este lead', max_length=100, verbose_name='ID do Indicador'),
        ),
    ]
