# Generated by Django 5.2.14 on 2026-07-02 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0060_leadprospecto_id_indicador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='Nome do Perfil')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('cor_hex', models.CharField(default='#0022fa', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('capacidades', models.JSONField(blank=True, default=list)),
                ('escopo_dados', models.CharField(choices=[('todos', 'Todos os registros'), ('pipeline', 'Registros dos pipelines que pode ver'), ('proprios', 'Apenas os atribuídos a ele')], default='proprios', max_length=12)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='perfis_acesso', to=settings.AUTH_USER_MODEL, verbose_name='Usuários')),
            ],
            options={
                'verbose_name': 'Perfil de Acesso',
                'verbose_name_plural': 'Perfis de Acesso',
                'db_table': 'perfil_acesso',
                'ordering': ['nome'],
            },
        ),
    ]
