# Generated by Django 5.2.14 on 2026-07-06 18:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0063_popular_cidades_viabilidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidadeviabilidade',
            name='bairro',
        ),
        migrations.CreateModel(
            name='BairroViabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, help_text='Nome do bairro atendido', max_length=120, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, db_index=True, help_text='CEP específico do bairro (opcional, formato: 00000-000).', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato 00000-000 ou 00000000', regex='^\\d{5}-?\\d{3}$')], verbose_name='CEP do bairro')),
                ('observacao', models.CharField(blank=True, help_text='Informação adicional sobre este bairro (opcional)', max_length=255, null=True, verbose_name='Observação')),
                ('ativo', models.BooleanField(db_index=True, default=True, help_text='Desative para suspender este bairro sem excluir', verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bairros', to='vendas_web.cidadeviabilidade', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Bairro com Viabilidade',
                'verbose_name_plural': 'Bairros com Viabilidade',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='vendas_web__nome_8c5764_idx')],
                'constraints': [models.UniqueConstraint(fields=('cidade', 'nome'), name='uniq_bairro_por_cidade')],
            },
        ),
    ]
