# Generated by Django 5.2.14 on 2026-07-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0064_bairro_viabilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadeviabilidade',
            name='atende_cidade_inteira',
            field=models.BooleanField(db_index=True, default=False, help_text='Marque se temos viabilidade em TODA a cidade, independente do bairro. Nesse caso a lista de bairros abaixo é só informativa (não restringe a venda). Deixe desmarcado se a viabilidade é restrita aos bairros cadastrados.', verbose_name='Atende a cidade inteira'),
        ),
    ]
