# Generated by Django 5.2.14 on 2026-07-06 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0065_atende_cidade_inteira'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoStatusLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status anterior')),
                ('status_novo', models.CharField(max_length=50, verbose_name='Status novo')),
                ('origem', models.CharField(blank=True, db_index=True, default='sistema', help_text='Quem disparou a mudança (ex: sistema, admin, hubsoft_sync, whatsapp_bot)', max_length=30, verbose_name='Origem')),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='vendas_web.leadprospecto', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Histórico de Status do Lead',
                'verbose_name_plural': 'Histórico de Status dos Leads',
                'ordering': ['-data_alteracao'],
                'indexes': [models.Index(fields=['lead', '-data_alteracao'], name='vendas_web__lead_id_634faa_idx')],
            },
        ),
    ]
