# Generated by Django 5.2.14 on 2026-07-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0066_historico_status_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadprospecto',
            name='nome_confirmado',
            field=models.BooleanField(default=False, help_text='True quando o nome foi COLETADO pelo fluxo (coleta_nome) ou digitado pelo operador — nome pré-preenchido (push name do WhatsApp) NÃO conta: o robô sempre pergunta o nome completo.', verbose_name='Nome confirmado'),
        ),
    ]
