# Generated by Django 5.2.14 on 2026-07-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_web', '0068_leadprospecto_origem_wifeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaocadastro',
            name='origem_lead_padrao',
            field=models.CharField(choices=[('site', 'Site'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google Ads'), ('whatsapp', 'WhatsApp'), ('indicacao', 'Indicação'), ('wifeed', 'Wifeed'), ('telefone', 'Telefone'), ('email', 'Email'), ('outros', 'Outros')], default='site', max_length=50, verbose_name='Origem Padrão do Lead'),
        ),
        migrations.AlterField(
            model_name='historicocontato',
            name='origem_contato',
            field=models.CharField(blank=True, choices=[('site', 'Site'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google Ads'), ('whatsapp', 'WhatsApp'), ('indicacao', 'Indicação'), ('wifeed', 'Wifeed'), ('telefone', 'Telefone'), ('email', 'Email'), ('outros', 'Outros')], help_text='Canal de origem do contato', max_length=50, null=True, verbose_name='Origem do Contato'),
        ),
    ]
