# Generated by Django 5.2.4 on 2026-03-31 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integracoes', '0002_alter_integracaoapi_access_token_and_more'),
        ('sistema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaChurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inadimplencia', 'Inadimplência'), ('sem_uso', 'Sem uso'), ('reclamacao', 'Reclamação'), ('contrato_expirando', 'Contrato expirando')], max_length=30)),
                ('severidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('descricao', models.TextField(blank=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integracoes.clientehubsoft')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Alerta de Churn',
                'verbose_name_plural': 'Alertas de Churn',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='AcaoRetencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('contato_whatsapp', 'Contato WhatsApp'), ('oferta_desconto', 'Oferta de desconto'), ('upgrade_plano', 'Upgrade de plano'), ('visita_tecnica', 'Visita técnica')], max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('executada', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_execucao', models.DateTimeField(blank=True, null=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='retencao.alertachurn')),
            ],
            options={
                'verbose_name': 'Ação de Retenção',
                'verbose_name_plural': 'Ações de Retenção',
            },
        ),
        migrations.CreateModel(
            name='ScoreCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=50, verbose_name='Health Score (0-100)')),
                ('fatores', models.JSONField(blank=True, default=dict, verbose_name='Fatores do Score')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integracoes.clientehubsoft')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Score de Cliente',
                'verbose_name_plural': 'Scores de Clientes',
            },
        ),
    ]
