# Generated by Django 5.2.4 on 2026-04-29 05:35

import apps.workspace.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comando', '0001_initial'),
        ('sistema', '0010_tenant_modulo_workspace_tenant_plano_workspace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PastaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('icone', models.CharField(default='bi-folder', help_text='Bootstrap Icons (bi-*)', max_length=50)),
                ('cor', models.CharField(default='#252020', help_text='Hex color — paleta v2 (tinta default)', max_length=7)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpastas', to='workspace.pastadocumento')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Pasta de Documento',
                'verbose_name_plural': 'Pastas de Documentos',
                'db_table': 'workspace_pasta_documento',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('categoria', models.CharField(choices=[('estrategia', 'Estratégia'), ('regras', 'Regras'), ('roadmap', 'Roadmap'), ('decisoes', 'Decisões'), ('entrega', 'Entrega'), ('sessao', 'Sessão'), ('contexto', 'Contexto'), ('relatorio', 'Relatório'), ('email', 'Email'), ('processo', 'Processo'), ('imagem', 'Imagem'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('conteudo', models.TextField(blank=True, help_text='Markdown')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=apps.workspace.models.documento_upload_path)),
                ('resumo', models.TextField(blank=True)),
                ('descricao', models.TextField(blank=True)),
                ('visivel_agentes', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agente_origem', models.ForeignKey(blank=True, help_text='Agente que gerou esse documento (se gerado por IA)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_criados', to='comando.agente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('pasta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='workspace.pastadocumento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'workspace_documento',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('planejamento', 'Planejamento'), ('em_andamento', 'Em andamento'), ('pausado', 'Pausado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejamento', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('objetivo', models.TextField(blank=True, verbose_name='Objetivo')),
                ('publico_alvo', models.TextField(blank=True, verbose_name='Público-alvo')),
                ('criterios_sucesso', models.TextField(blank=True, verbose_name='Critérios de sucesso')),
                ('riscos', models.TextField(blank=True, verbose_name='Riscos')),
                ('premissas', models.TextField(blank=True, verbose_name='Premissas')),
                ('stakeholders', models.TextField(blank=True, help_text='Texto livre por enquanto', verbose_name='Stakeholders')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim_prevista', models.DateField(blank=True, null=True)),
                ('orcamento', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contexto_agentes', models.TextField(blank=True, help_text='Briefing pra agentes IA usarem quando trabalharem no projeto')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'db_table': 'workspace_projeto',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='workspace.projeto')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'db_table': 'workspace_etapa',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('bloqueada', 'Bloqueada')], default='pendente', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Pra kanban drag-and-drop')),
                ('objetivo', models.TextField(blank=True)),
                ('contexto', models.TextField(blank=True)),
                ('passos', models.TextField(blank=True)),
                ('entregavel', models.TextField(blank=True)),
                ('criterios_aceite', models.TextField(blank=True)),
                ('log_execucao', models.TextField(blank=True)),
                ('nivel_delegacao', models.PositiveSmallIntegerField(default=0, help_text='0=humano, 1-2=agente IA')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por_agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_criadas', to='comando.agente')),
                ('documento_processo', models.ForeignKey(blank=True, help_text='SOP/processo associado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_processo', to='workspace.documento')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='workspace.etapa')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='workspace.projeto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_responsavel', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'db_table': 'workspace_tarefa',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_workspace', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='workspace.tarefa')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'workspace_nota',
                'ordering': ['criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tenant', 'categoria'], name='workspace_d_tenant__df33d7_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tenant', 'pasta'], name='workspace_d_tenant__52020d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['tenant', 'status'], name='workspace_p_tenant__56a6f4_idx'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['tenant', 'ativo'], name='workspace_p_tenant__f442aa_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['tenant', 'status'], name='workspace_t_tenant__7f9ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['tenant', 'responsavel'], name='workspace_t_tenant__30d8c8_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['projeto', 'status', 'ordem'], name='workspace_t_projeto_5dee65_idx'),
        ),
    ]
