# Generated by Django 5.2.4 on 2026-04-29 14:55

import apps.workspace.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_tenant_modulo_workspace_tenant_plano_workspace_and_more'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=apps.workspace.models.anexo_upload_path)),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('arquivo', 'Arquivo')], default='arquivo', max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('tamanho_bytes', models.PositiveBigIntegerField(default=0)),
                ('gerado_por_ia', models.BooleanField(default=False)),
                ('prompt_ia', models.TextField(blank=True)),
                ('modelo_ia', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_workspace', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='workspace.documento')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Anexo de Documento',
                'verbose_name_plural': 'Anexos de Documentos',
                'db_table': 'workspace_anexo_documento',
                'ordering': ['-criado_em'],
            },
        ),
    ]
