# Generated by Django 5.2.4 on 2026-04-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_anexodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='formato',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('imagem', 'Imagem'), ('pdf', 'PDF'), ('link', 'Link externo')], default='markdown', help_text='Como o conteúdo deve ser renderizado', max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='url_externa',
            field=models.URLField(blank=True, help_text='Para formato=link'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='conteudo',
            field=models.TextField(blank=True, help_text='Markdown ou HTML, conforme o formato'),
        ),
    ]
