# Generated by Django 5.2.4 on 2026-06-29 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0008_agente_memoria'),
        ('sistema', '0012_perfilusuario_login_matrix'),
        ('workspace', '0003_documento_formato_documento_url_externa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField(blank=True)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('executada', 'Executada'), ('erro', 'Erro')], db_index=True, default='pendente', max_length=20)),
                ('dados_execucao', models.JSONField(blank=True, default=dict)),
                ('resultado_execucao', models.TextField(blank=True)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('data_decisao', models.DateTimeField(blank=True, null=True)),
                ('data_execucao', models.DateTimeField(blank=True, null=True)),
                ('agente', models.ForeignKey(blank=True, help_text='Agente que propôs a ação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas', to='automacao.agente')),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_decididas', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(blank=True, help_text='Tarefa de origem (se veio do backlog)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas', to='workspace.tarefa')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'db_table': 'workspace_proposta',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='workspace_p_tenant__b4eabb_idx')],
            },
        ),
    ]
