# Generated by Django 5.2.4 on 2026-06-29 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0008_agente_memoria'),
        ('workspace', '0004_proposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='agente_origem',
            field=models.ForeignKey(blank=True, help_text='Agente que gerou esse documento (se gerado por IA)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_origem', to='automacao.agente'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='criado_por_agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_criadas', to='automacao.agente'),
        ),
    ]
