# Generated by Django 5.2.4 on 2026-03-31 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimento', '0001_initial'),
        ('leads', '0001_initial'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentofluxo',
            name='historico_contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_fluxo', to='leads.historicocontato', verbose_name='Histórico de Contato'),
        ),
        migrations.AddField(
            model_name='atendimentofluxo',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos_fluxo', to='leads.leadprospecto', verbose_name='Lead/Prospecto'),
        ),
        migrations.AddField(
            model_name='atendimentofluxo',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='fluxoatendimento',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='atendimentofluxo',
            name='fluxo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='atendimento.fluxoatendimento', verbose_name='Fluxo'),
        ),
        migrations.AddField(
            model_name='questaofluxo',
            name='fluxo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='atendimento.fluxoatendimento', verbose_name='Fluxo'),
        ),
        migrations.AddField(
            model_name='questaofluxo',
            name='questao_dependencia',
            field=models.ForeignKey(blank=True, help_text='Questão que deve ser respondida antes desta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='atendimento.questaofluxo', verbose_name='Questão de Dependência'),
        ),
        migrations.AddField(
            model_name='questaofluxo',
            name='questao_erro_redirecionamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questoes_erro_origem', to='atendimento.questaofluxo', verbose_name='Questão para Redirecionamento de Erro'),
        ),
        migrations.AddField(
            model_name='questaofluxo',
            name='questao_padrao_proxima',
            field=models.ForeignKey(blank=True, help_text='Questão padrão caso resposta não tenha roteamento específico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questoes_anteriores_padrao', to='atendimento.questaofluxo', verbose_name='Questão Padrão Próxima'),
        ),
        migrations.AddField(
            model_name='questaofluxo',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='respostaquestao',
            name='atendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_detalhadas', to='atendimento.atendimentofluxo', verbose_name='Atendimento'),
        ),
        migrations.AddField(
            model_name='respostaquestao',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='atendimento.questaofluxo', verbose_name='Questão'),
        ),
        migrations.AddField(
            model_name='respostaquestao',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='tentativaresposta',
            name='atendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_respostas', to='atendimento.atendimentofluxo', verbose_name='Atendimento'),
        ),
        migrations.AddField(
            model_name='tentativaresposta',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='atendimento.questaofluxo', verbose_name='Questão'),
        ),
        migrations.AddField(
            model_name='tentativaresposta',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant'),
        ),
        migrations.AddIndex(
            model_name='fluxoatendimento',
            index=models.Index(fields=['tipo_fluxo'], name='fluxos_aten_tipo_fl_5b8c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='fluxoatendimento',
            index=models.Index(fields=['status'], name='fluxos_aten_status_caafd0_idx'),
        ),
        migrations.AddIndex(
            model_name='fluxoatendimento',
            index=models.Index(fields=['ativo'], name='fluxos_aten_ativo_ce32a4_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimentofluxo',
            index=models.Index(fields=['lead'], name='atendimento_lead_id_393eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimentofluxo',
            index=models.Index(fields=['fluxo'], name='atendimento_fluxo_i_87c67a_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimentofluxo',
            index=models.Index(fields=['status'], name='atendimento_status_e0935a_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimentofluxo',
            index=models.Index(fields=['data_inicio'], name='atendimento_data_in_94bdf5_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimentofluxo',
            index=models.Index(fields=['questao_atual'], name='atendimento_questao_9035e4_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimentofluxo',
            index=models.Index(fields=['id_externo'], name='atendimento_id_exte_9912c3_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimentofluxo',
            index=models.Index(fields=['lead', 'status'], name='atendimento_lead_id_5f6886_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimentofluxo',
            index=models.Index(fields=['fluxo', 'status'], name='atendimento_fluxo_i_26934b_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimentofluxo',
            index=models.Index(fields=['data_inicio', 'status'], name='atendimento_data_in_993b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='questaofluxo',
            index=models.Index(fields=['fluxo', 'indice'], name='questoes_fl_fluxo_i_b10554_idx'),
        ),
        migrations.AddIndex(
            model_name='questaofluxo',
            index=models.Index(fields=['tipo_questao'], name='questoes_fl_tipo_qu_cf0996_idx'),
        ),
        migrations.AddIndex(
            model_name='questaofluxo',
            index=models.Index(fields=['ativo'], name='questoes_fl_ativo_1f73dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questaofluxo',
            unique_together={('fluxo', 'indice')},
        ),
        migrations.AddIndex(
            model_name='respostaquestao',
            index=models.Index(fields=['atendimento', 'questao'], name='respostas_q_atendim_ab85d0_idx'),
        ),
        migrations.AddIndex(
            model_name='respostaquestao',
            index=models.Index(fields=['data_resposta'], name='respostas_q_data_re_19b0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='respostaquestao',
            index=models.Index(fields=['valida'], name='respostas_q_valida_3a6321_idx'),
        ),
        migrations.AddIndex(
            model_name='tentativaresposta',
            index=models.Index(fields=['atendimento', 'questao'], name='tentativas__atendim_ae5f36_idx'),
        ),
        migrations.AddIndex(
            model_name='tentativaresposta',
            index=models.Index(fields=['tentativa_numero'], name='tentativas__tentati_16cc9b_idx'),
        ),
        migrations.AddIndex(
            model_name='tentativaresposta',
            index=models.Index(fields=['valida'], name='tentativas__valida_799a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='tentativaresposta',
            index=models.Index(fields=['data_tentativa'], name='tentativas__data_te_32f1cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tentativaresposta',
            unique_together={('atendimento', 'questao', 'tentativa_numero')},
        ),
    ]
