# Generated by Django 5.2.4 on 2026-04-06 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_initial'),
        ('sistema', '0004_funcionalidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxoatendimento',
            name='fluxo_json',
            field=models.JSONField(blank=True, default=dict, help_text='Estado do Drawflow para re-import do editor visual', verbose_name='Estado do Editor'),
        ),
        migrations.AddField(
            model_name='fluxoatendimento',
            name='modo_fluxo',
            field=models.BooleanField(default=False, help_text='True = fluxograma visual com nodos, False = questoes lineares (legado)', verbose_name='Modo Fluxo Visual'),
        ),
        migrations.CreateModel(
            name='NodoFluxoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('questao', 'Questao'), ('condicao', 'Condicao'), ('acao', 'Acao'), ('delay', 'Delay'), ('finalizacao', 'Finalizacao')], max_length=20, verbose_name='Tipo do Nodo')),
                ('subtipo', models.CharField(blank=True, help_text='Ex: texto, select, campo_check, enviar_whatsapp, webhook', max_length=50, verbose_name='Subtipo')),
                ('configuracao', models.JSONField(blank=True, default=dict, help_text='Config do nodo: titulo, opcoes, campo/operador/valor, template, delay', verbose_name='Configuracao')),
                ('pos_x', models.IntegerField(default=0, verbose_name='Posicao X')),
                ('pos_y', models.IntegerField(default=0, verbose_name='Posicao Y')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodos', to='atendimento.fluxoatendimento', verbose_name='Fluxo')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Nodo do Fluxo',
                'verbose_name_plural': 'Nodos do Fluxo',
                'db_table': 'atendimento_nodofluxo',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='atendimentofluxo',
            name='nodo_atual',
            field=models.ForeignKey(blank=True, help_text='Nodo atual no modo fluxo visual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_atuais', to='atendimento.nodofluxoatendimento', verbose_name='Nodo Atual'),
        ),
        migrations.CreateModel(
            name='ExecucaoFluxoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto_json', models.JSONField(default=dict, help_text='Contexto serializado para retomar execucao', verbose_name='Contexto')),
                ('data_agendada', models.DateTimeField(db_index=True, verbose_name='Data Agendada')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('executado', 'Executado'), ('cancelado', 'Cancelado'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_execucao', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes_pendentes', to='atendimento.atendimentofluxo', verbose_name='Atendimento')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('nodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_pendentes', to='atendimento.nodofluxoatendimento', verbose_name='Nodo')),
            ],
            options={
                'verbose_name': 'Execucao Pendente',
                'verbose_name_plural': 'Execucoes Pendentes',
                'db_table': 'atendimento_execucao_pendente',
                'ordering': ['data_agendada'],
                'indexes': [models.Index(fields=['status', 'data_agendada'], name='atendimento_status_582f4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConexaoNodoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_saida', models.CharField(choices=[('default', 'Padrao'), ('true', 'Verdadeiro (Sim)'), ('false', 'Falso (Nao)')], default='default', max_length=10, verbose_name='Tipo de Saida')),
                ('fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes', to='atendimento.fluxoatendimento', verbose_name='Fluxo')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
                ('nodo_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='atendimento.nodofluxoatendimento', verbose_name='Nodo Destino')),
                ('nodo_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='atendimento.nodofluxoatendimento', verbose_name='Nodo Origem')),
            ],
            options={
                'verbose_name': 'Conexao',
                'verbose_name_plural': 'Conexoes',
                'db_table': 'atendimento_conexaonodo',
                'unique_together': {('nodo_origem', 'nodo_destino', 'tipo_saida')},
            },
        ),
    ]
