# Generated by Django 5.2.4 on 2026-04-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0003_fluxoatendimento_fluxo_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxoatendimento',
            name='canal',
            field=models.CharField(choices=[('qualquer', 'Qualquer Canal'), ('whatsapp', 'WhatsApp'), ('site', 'Site'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google Ads'), ('telefone', 'Telefone'), ('email', 'Email'), ('indicacao', 'Indicacao'), ('manual', 'Manual (somente API)')], db_index=True, default='qualquer', help_text="Canal que dispara este fluxo automaticamente. 'Manual' = somente via API.", max_length=20, verbose_name='Canal de Ativacao'),
        ),
    ]
