# Generated by Django 5.2.4 on 2026-04-06 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0004_fluxoatendimento_canal'),
        ('leads', '0002_leadprospecto_dados_custom_campocustomizado'),
        ('sistema', '0004_funcionalidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFluxoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nodo', models.CharField(blank=True, max_length=20, verbose_name='Tipo do Nodo')),
                ('subtipo_nodo', models.CharField(blank=True, max_length=50, verbose_name='Subtipo do Nodo')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro'), ('aguardando', 'Aguardando Resposta'), ('agendado', 'Agendado (Delay)')], default='sucesso', max_length=20)),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem/Resultado')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='Dados Extras')),
                ('data_execucao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Execucao')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_fluxo', to='atendimento.atendimentofluxo', verbose_name='Atendimento')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_fluxo_atendimento', to='leads.leadprospecto', verbose_name='Lead')),
                ('nodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='atendimento.nodofluxoatendimento', verbose_name='Nodo')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Log do Fluxo',
                'verbose_name_plural': 'Logs do Fluxo',
                'db_table': 'atendimento_log_fluxo',
                'ordering': ['-data_execucao'],
                'indexes': [models.Index(fields=['atendimento', '-data_execucao'], name='atendimento_atendim_49079e_idx'), models.Index(fields=['lead', '-data_execucao'], name='atendimento_lead_id_d571e4_idx')],
            },
        ),
    ]
