# Generated by Django 5.2.4 on 2026-04-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0005_logfluxoatendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodofluxoatendimento',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('questao', 'Questao'), ('condicao', 'Condicao'), ('acao', 'Acao'), ('delay', 'Delay'), ('finalizacao', 'Finalizacao'), ('ia_classificador', 'Classificador IA'), ('ia_extrator', 'Extrator IA'), ('ia_respondedor', 'Respondedor IA'), ('ia_agente', 'Agente IA')], max_length=30, verbose_name='Tipo do Nodo'),
        ),
    ]
