# Generated by Django 5.2.4 on 2026-04-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0006_alter_nodofluxoatendimento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentofluxo',
            name='motivo_finalizacao',
            field=models.CharField(blank=True, choices=[('completado', 'Fluxo completado'), ('sem_resposta', 'Sem resposta'), ('abandonado_usuario', 'Abandonado pelo usuario'), ('transferido', 'Transferido para humano'), ('cancelado_atendente', 'Cancelado pelo atendente'), ('cancelado_sistema', 'Cancelado pelo sistema'), ('tempo_limite', 'Tempo limite excedido')], default='', max_length=30, verbose_name='Motivo da Finalizacao'),
        ),
        migrations.AddField(
            model_name='atendimentofluxo',
            name='recontato_proximo_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Proximo Recontato Em'),
        ),
        migrations.AddField(
            model_name='atendimentofluxo',
            name='recontato_tentativas',
            field=models.PositiveIntegerField(default=0, verbose_name='Tentativas de Recontato'),
        ),
        migrations.AddField(
            model_name='fluxoatendimento',
            name='recontato_ativo',
            field=models.BooleanField(default=False, help_text='Ativar recontato automatico para atendimentos parados', verbose_name='Recontato Ativo'),
        ),
        migrations.AddField(
            model_name='fluxoatendimento',
            name='recontato_config',
            field=models.JSONField(blank=True, default=dict, help_text='{"tentativas": [{"tempo_minutos": 60, "mensagem": "..."}], "usar_ia": false, "acao_final": "abandonar"}', verbose_name='Config Recontato'),
        ),
        migrations.AlterField(
            model_name='nodofluxoatendimento',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('questao', 'Questao'), ('condicao', 'Condicao'), ('acao', 'Acao'), ('delay', 'Delay'), ('finalizacao', 'Finalizacao'), ('transferir_humano', 'Transferir para Humano'), ('ia_classificador', 'Classificador IA'), ('ia_extrator', 'Extrator IA'), ('ia_respondedor', 'Respondedor IA'), ('ia_agente', 'Agente IA')], max_length=30, verbose_name='Tipo do Nodo'),
        ),
    ]
