# Generated by Django 5.2.4 on 2026-04-14 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0007_atendimentofluxo_motivo_finalizacao_and_more'),
        ('leads', '0003_alter_campocustomizado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentofluxo',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos_fluxo', to='leads.leadprospecto', verbose_name='Lead/Prospecto'),
        ),
    ]
