# Generated by Django 5.2.4 on 2026-04-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0008_alter_atendimentofluxo_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxoatendimento',
            name='base_conhecimento_ativa',
            field=models.BooleanField(default=False, help_text='Quando ativo, fallbacks de questoes consultam a base de conhecimento antes de responder', verbose_name='Base de Conhecimento'),
        ),
    ]
