# Generated by Django 5.2.4 on 2026-04-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0009_fluxoatendimento_base_conhecimento_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentofluxo',
            name='motivo_finalizacao',
            field=models.CharField(blank=True, choices=[('completado', 'Fluxo completado'), ('ganho', 'Ganho (conversao)'), ('perdido', 'Perdido (nao converteu)'), ('sem_interesse', 'Sem interesse'), ('sem_viabilidade', 'Sem viabilidade'), ('duplicado', 'Duplicado'), ('cancelado', 'Cancelado'), ('sem_resposta', 'Sem resposta'), ('abandonado_usuario', 'Abandonado pelo usuario'), ('transferido', 'Transferido para humano'), ('cancelado_atendente', 'Cancelado pelo atendente'), ('cancelado_sistema', 'Cancelado pelo sistema'), ('tempo_limite', 'Tempo limite excedido')], default='', max_length=30, verbose_name='Motivo da Finalizacao'),
        ),
    ]
