# Generated by Django 5.2.4 on 2026-04-17 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0010_alter_atendimentofluxo_motivo_finalizacao'),
        ('sistema', '0009_perfilusuario_senha_temporaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCustomizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome usado pela LLM (ex: 'consultar_cliente_hubsoft'). Sem espacos, snake_case.", max_length=100, verbose_name='Nome da Tool')),
                ('descricao', models.TextField(help_text='Explica para a LLM o que a tool faz e quando usar', verbose_name='Descricao')),
                ('parametros', models.JSONField(blank=True, default=dict, help_text='Schema dos parametros. Ex: {"pergunta": {"type": "string", "description": "..."}}', verbose_name='Parametros (JSON Schema)')),
                ('webhook_url', models.URLField(help_text='URL chamada via POST quando a LLM invoca a tool. Recebe {tool, args, contexto}.', max_length=500, verbose_name='Webhook URL')),
                ('webhook_token', models.CharField(blank=True, default='', help_text='Token enviado no header Authorization (opcional)', max_length=255, verbose_name='Token Webhook')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Tool Customizada',
                'verbose_name_plural': 'Tools Customizadas',
                'db_table': 'atendimento_tool_customizada',
                'ordering': ['nome'],
                'unique_together': {('tenant', 'nome')},
            },
        ),
    ]
