# Generated by Django 5.2.4 on 2026-04-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0011_toolcustomizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conexaonodoatendimento',
            name='tipo_saida',
            field=models.CharField(default='default', help_text='default, true, false, erro, ou nome de categoria (ia_classificador)', max_length=50, verbose_name='Tipo de Saida'),
        ),
    ]
