# Generated by Django 5.2.4 on 2026-05-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0012_alter_conexaonodoatendimento_tipo_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conexaonodoatendimento',
            name='tipo_saida',
            field=models.CharField(default='default', help_text="default, true, false, erro, timeout, ou nome de categoria (ia_classificador). 'timeout' segue automaticamente quando nodo_origem.configuracao['timeout_segundos'] expira sem resposta — disparado pelo cron check_nodo_timeouts.", max_length=50, verbose_name='Tipo de Saida'),
        ),
    ]
