# Generated by Django 5.2.4 on 2026-05-31 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0013_alter_conexaonodoatendimento_tipo_saida'),
        ('inbox', '0013_add_assumida_conversa'),
        ('leads', '0004_alter_leadprospecto_status_api'),
        ('sistema', '0010_tenant_modulo_workspace_tenant_plano_workspace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoErroResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta_bot', models.TextField(help_text="Texto da pergunta que o bot fez ao cliente (ex: 'qual seu CPF?')", verbose_name='Pergunta do bot')),
                ('resposta_cliente', models.TextField(help_text='O que o cliente respondeu (e o bot considerou invalido)', verbose_name='Resposta do cliente')),
                ('no_fluxo', models.CharField(blank=True, default='', help_text="Nome/slug do node do bot quando o erro ocorreu (ex: 'ColetaCPF')", max_length=100, verbose_name='No do fluxo')),
                ('canal', models.CharField(blank=True, default='', help_text='whatsapp / chat / sms / etc', max_length=30, verbose_name='Canal')),
                ('solucao', models.TextField(blank=True, default='', help_text='Como o erro foi resolvido (preenchido pelo curador)', verbose_name='Solucao')),
                ('resolvido', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('ocorrencias', models.PositiveIntegerField(default=1, help_text='Quantas vezes essa mesma combinacao (pergunta_bot, resposta_cliente) aconteceu', verbose_name='Ocorrencias')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('resolvido_em', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('conversa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inbox.conversa', verbose_name='Conversa')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erros_resposta', to='leads.leadprospecto', verbose_name='Lead')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='sistema.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Motivo de Erro em Resposta',
                'verbose_name_plural': 'Motivos de Erro em Respostas',
                'db_table': 'atendimento_motivo_erro_resposta',
                'ordering': ['-ocorrencias', '-criado_em'],
                'indexes': [models.Index(fields=['tenant', 'resolvido', '-criado_em'], name='merr_t_resv_dt_idx'), models.Index(fields=['tenant', 'no_fluxo'], name='merr_t_node_idx')],
            },
        ),
    ]
